# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_VogisPrint.ui'
#
# Created: Fri Jan 24 13:14:17 2014
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_VogisPrint(object):
    def setupUi(self, VogisPrint):
        VogisPrint.setObjectName(_fromUtf8("VogisPrint"))
        VogisPrint.setEnabled(True)
        VogisPrint.resize(702, 444)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VogisPrint.sizePolicy().hasHeightForWidth())
        VogisPrint.setSizePolicy(sizePolicy)
        self.groupBox_9 = QtGui.QGroupBox(VogisPrint)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 30, 651, 311))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 30, 391, 251))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_7)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 341, 211))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setToolTip(_fromUtf8(""))
        self.label.setStatusTip(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 2, 1)
        self.printScale = QtGui.QComboBox(self.gridLayoutWidget)
        self.printScale.setToolTip(_fromUtf8(""))
        self.printScale.setEditable(True)
        self.printScale.setMaxVisibleItems(16)
        self.printScale.setObjectName(_fromUtf8("printScale"))
        self.gridLayout_2.addWidget(self.printScale, 0, 1, 2, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 2, 1)
        self.printFormat = QtGui.QComboBox(self.gridLayoutWidget)
        self.printFormat.setObjectName(_fromUtf8("printFormat"))
        self.gridLayout_2.addWidget(self.printFormat, 1, 1, 2, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 2, 1)
        self.layout = QtGui.QComboBox(self.gridLayoutWidget)
        self.layout.setObjectName(_fromUtf8("layout"))
        self.gridLayout_2.addWidget(self.layout, 2, 1, 2, 1)
        self.department = QtGui.QComboBox(self.gridLayoutWidget)
        self.department.setObjectName(_fromUtf8("department"))
        self.gridLayout_2.addWidget(self.department, 6, 1, 2, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 2, 1)
        self.title = QtGui.QLineEdit(self.gridLayoutWidget)
        self.title.setText(_fromUtf8(""))
        self.title.setReadOnly(False)
        self.title.setObjectName(_fromUtf8("title"))
        self.gridLayout_2.addWidget(self.title, 3, 1, 2, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 2, 1)
        self.subtitle = QtGui.QLineEdit(self.gridLayoutWidget)
        self.subtitle.setEnabled(True)
        self.subtitle.setText(_fromUtf8(""))
        self.subtitle.setObjectName(_fromUtf8("subtitle"))
        self.gridLayout_2.addWidget(self.subtitle, 4, 1, 2, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 2, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 2, 1)
        self.person = QtGui.QLineEdit(self.gridLayoutWidget)
        self.person.setObjectName(_fromUtf8("person"))
        self.gridLayout_2.addWidget(self.person, 5, 1, 2, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_8.setGeometry(QtCore.QRect(420, 30, 201, 251))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_8)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 181, 211))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_40 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_4.addWidget(self.label_40, 0, 0, 2, 1)
        self.cuttinglines = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cuttinglines.setMinimumSize(QtCore.QSize(0, 23))
        self.cuttinglines.setText(_fromUtf8(""))
        self.cuttinglines.setObjectName(_fromUtf8("cuttinglines"))
        self.gridLayout_4.addWidget(self.cuttinglines, 0, 2, 2, 1)
        self.label_43 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_4.addWidget(self.label_43, 1, 0, 2, 1)
        self.foldingmarks = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.foldingmarks.setMinimumSize(QtCore.QSize(0, 23))
        self.foldingmarks.setText(_fromUtf8(""))
        self.foldingmarks.setObjectName(_fromUtf8("foldingmarks"))
        self.gridLayout_4.addWidget(self.foldingmarks, 1, 2, 2, 1)
        self.label_42 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_4.addWidget(self.label_42, 2, 0, 2, 1)
        self.crsdesc = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.crsdesc.setMinimumSize(QtCore.QSize(0, 23))
        self.crsdesc.setText(_fromUtf8(""))
        self.crsdesc.setObjectName(_fromUtf8("crsdesc"))
        self.gridLayout_4.addWidget(self.crsdesc, 2, 2, 2, 1)
        self.label_39 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_4.addWidget(self.label_39, 3, 0, 2, 1)
        self.legend = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.legend.setMinimumSize(QtCore.QSize(0, 23))
        self.legend.setText(_fromUtf8(""))
        self.legend.setObjectName(_fromUtf8("legend"))
        self.gridLayout_4.addWidget(self.legend, 3, 2, 2, 1)
        self.label_44 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_4.addWidget(self.label_44, 4, 0, 2, 1)
        self.grid = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.grid.setMinimumSize(QtCore.QSize(0, 23))
        self.grid.setText(_fromUtf8(""))
        self.grid.setObjectName(_fromUtf8("grid"))
        self.gridLayout_4.addWidget(self.grid, 4, 2, 2, 1)
        self.groupBox_10 = QtGui.QGroupBox(VogisPrint)
        self.groupBox_10.setGeometry(QtCore.QRect(80, 350, 511, 71))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox_10)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 480, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_3 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_4 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_3.addWidget(self.pushButton_4)

        self.retranslateUi(VogisPrint)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("pressed()")), VogisPrint.accept)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("pressed()")), VogisPrint.close)
        QtCore.QMetaObject.connectSlotsByName(VogisPrint)

    def retranslateUi(self, VogisPrint):
        VogisPrint.setWindowTitle(QtGui.QApplication.translate("VogisPrint", "VogisPrint", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("VogisPrint", "Printing Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("VogisPrint", "General Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("VogisPrint", "Output-Print-Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("VogisPrint", "Papersize", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("VogisPrint", "Layout: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("VogisPrint", "Title: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("VogisPrint", "Undertitle: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("VogisPrint", "Person: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("VogisPrint", "Department: ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("VogisPrint", "Additional Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("VogisPrint", "cutting lines: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("VogisPrint", "folding marks:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("VogisPrint", "crs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("VogisPrint", "legend: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("VogisPrint", "grid:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("VogisPrint", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("VogisPrint", "Simple map", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("VogisPrint", "mapbook (grid)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("VogisPrint", "Close", None, QtGui.QApplication.UnicodeUTF8))

