# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_VogisPrint.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VogisPrint(object):
    def setupUi(self, VogisPrint):
        VogisPrint.setObjectName("VogisPrint")
        VogisPrint.setEnabled(True)
        VogisPrint.resize(702, 444)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VogisPrint.sizePolicy().hasHeightForWidth())
        VogisPrint.setSizePolicy(sizePolicy)
        self.groupBox_9 = QtWidgets.QGroupBox(VogisPrint)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 30, 651, 311))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 30, 381, 251))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 34, 361, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setToolTip("")
        self.label.setStatusTip("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.printScale = QtWidgets.QComboBox(self.layoutWidget)
        self.printScale.setToolTip("")
        self.printScale.setEditable(True)
        self.printScale.setMaxVisibleItems(16)
        self.printScale.setObjectName("printScale")
        self.gridLayout_2.addWidget(self.printScale, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.printFormat = QtWidgets.QComboBox(self.layoutWidget)
        self.printFormat.setObjectName("printFormat")
        self.gridLayout_2.addWidget(self.printFormat, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.layout = QtWidgets.QComboBox(self.layoutWidget)
        self.layout.setObjectName("layout")
        self.gridLayout_2.addWidget(self.layout, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.title = QtWidgets.QLineEdit(self.layoutWidget)
        self.title.setText("")
        self.title.setReadOnly(False)
        self.title.setObjectName("title")
        self.gridLayout_2.addWidget(self.title, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.subtitle = QtWidgets.QLineEdit(self.layoutWidget)
        self.subtitle.setEnabled(True)
        self.subtitle.setText("")
        self.subtitle.setObjectName("subtitle")
        self.gridLayout_2.addWidget(self.subtitle, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.person = QtWidgets.QLineEdit(self.layoutWidget)
        self.person.setEnabled(True)
        self.person.setObjectName("person")
        self.gridLayout_2.addWidget(self.person, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.department = QtWidgets.QComboBox(self.layoutWidget)
        self.department.setObjectName("department")
        self.gridLayout_2.addWidget(self.department, 6, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_8.setGeometry(QtCore.QRect(420, 30, 211, 251))
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 191, 211))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 0, 0, 1, 1)
        self.cuttinglines = QtWidgets.QCheckBox(self.layoutWidget1)
        self.cuttinglines.setMinimumSize(QtCore.QSize(0, 23))
        self.cuttinglines.setStatusTip("")
        self.cuttinglines.setText("")
        self.cuttinglines.setObjectName("cuttinglines")
        self.gridLayout.addWidget(self.cuttinglines, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 1, 0, 1, 1)
        self.foldingmarks = QtWidgets.QCheckBox(self.layoutWidget1)
        self.foldingmarks.setMinimumSize(QtCore.QSize(0, 23))
        self.foldingmarks.setStatusTip("")
        self.foldingmarks.setText("")
        self.foldingmarks.setObjectName("foldingmarks")
        self.gridLayout.addWidget(self.foldingmarks, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 2, 0, 1, 1)
        self.crsdesc = QtWidgets.QCheckBox(self.layoutWidget1)
        self.crsdesc.setMinimumSize(QtCore.QSize(0, 23))
        self.crsdesc.setStatusTip("")
        self.crsdesc.setText("")
        self.crsdesc.setObjectName("crsdesc")
        self.gridLayout.addWidget(self.crsdesc, 2, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 3, 0, 1, 1)
        self.legend = QtWidgets.QCheckBox(self.layoutWidget1)
        self.legend.setMinimumSize(QtCore.QSize(0, 23))
        self.legend.setStatusTip("")
        self.legend.setText("")
        self.legend.setObjectName("legend")
        self.gridLayout.addWidget(self.legend, 3, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 4, 0, 1, 1)
        self.grid = QtWidgets.QCheckBox(self.layoutWidget1)
        self.grid.setEnabled(True)
        self.grid.setMinimumSize(QtCore.QSize(0, 23))
        self.grid.setStatusTip("")
        self.grid.setText("")
        self.grid.setAutoRepeat(False)
        self.grid.setTristate(False)
        self.grid.setObjectName("grid")
        self.gridLayout.addWidget(self.grid, 4, 1, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(VogisPrint)
        self.groupBox_10.setGeometry(QtCore.QRect(80, 350, 511, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_10)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 480, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)

        self.retranslateUi(VogisPrint)
        self.pushButton_4.pressed.connect(VogisPrint.close)
        self.pushButton_3.pressed.connect(VogisPrint.accept)
        QtCore.QMetaObject.connectSlotsByName(VogisPrint)

    def retranslateUi(self, VogisPrint):
        _translate = QtCore.QCoreApplication.translate
        VogisPrint.setWindowTitle(_translate("VogisPrint", "VogisPrint"))
        self.groupBox_9.setTitle(_translate("VogisPrint", "Printing Settings"))
        self.groupBox_7.setTitle(_translate("VogisPrint", "General Settings"))
        self.label.setText(_translate("VogisPrint", "Output-Print-Scale:"))
        self.label_2.setText(_translate("VogisPrint", "Papersize:"))
        self.label_5.setText(_translate("VogisPrint", "Layout: "))
        self.label_3.setText(_translate("VogisPrint", "Title: "))
        self.label_4.setText(_translate("VogisPrint", "Undertitle: "))
        self.label_6.setText(_translate("VogisPrint", "Person: "))
        self.label_7.setText(_translate("VogisPrint", "Department:"))
        self.groupBox_8.setTitle(_translate("VogisPrint", "Additional Settings"))
        self.label_40.setText(_translate("VogisPrint", "cutting lines: "))
        self.label_43.setText(_translate("VogisPrint", "folding marks:"))
        self.label_42.setText(_translate("VogisPrint", "crs:"))
        self.label_39.setText(_translate("VogisPrint", "legend: "))
        self.label_44.setText(_translate("VogisPrint", "grid:"))
        self.groupBox_10.setTitle(_translate("VogisPrint", "Print"))
        self.pushButton_3.setText(_translate("VogisPrint", "Simple map"))
        self.pushButton_2.setText(_translate("VogisPrint", "mapbook (grid)"))
        self.pushButton_4.setText(_translate("VogisPrint", "Close"))

