# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_verkehr.ui'
#
# Created: Fri Sep 04 08:20:03 2015
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmVerkehr(object):
    def setupUi(self, frmVerkehr):
        frmVerkehr.setObjectName(_fromUtf8("frmVerkehr"))
        frmVerkehr.resize(410, 340)
        self.toolBox = QtGui.QToolBox(frmVerkehr)
        self.toolBox.setGeometry(QtCore.QRect(10, 0, 391, 251))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 391, 116))
        self.page.setObjectName(_fromUtf8("page"))
        self.ckHauptstrassen = QtGui.QCheckBox(self.page)
        self.ckHauptstrassen.setGeometry(QtCore.QRect(30, 20, 281, 18))
        self.ckHauptstrassen.setObjectName(_fromUtf8("ckHauptstrassen"))
        self.ckButtons = QtGui.QButtonGroup(frmVerkehr)
        self.ckButtons.setObjectName(_fromUtf8("ckButtons"))
        self.ckButtons.addButton(self.ckHauptstrassen)
        self.ckGemeindestrassen = QtGui.QCheckBox(self.page)
        self.ckGemeindestrassen.setGeometry(QtCore.QRect(30, 50, 231, 18))
        self.ckGemeindestrassen.setToolTip(_fromUtf8(""))
        self.ckGemeindestrassen.setStatusTip(_fromUtf8(""))
        self.ckGemeindestrassen.setWhatsThis(_fromUtf8(""))
        self.ckGemeindestrassen.setObjectName(_fromUtf8("ckGemeindestrassen"))
        self.ckButtons.addButton(self.ckGemeindestrassen)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 391, 116))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.ckOepnv = QtGui.QCheckBox(self.page_5)
        self.ckOepnv.setGeometry(QtCore.QRect(40, 30, 271, 18))
        self.ckOepnv.setObjectName(_fromUtf8("ckOepnv"))
        self.ckButtons.addButton(self.ckOepnv)
        self.ckSeilbahn = QtGui.QCheckBox(self.page_5)
        self.ckSeilbahn.setGeometry(QtCore.QRect(40, 60, 271, 18))
        self.ckSeilbahn.setObjectName(_fromUtf8("ckSeilbahn"))
        self.ckButtons.addButton(self.ckSeilbahn)
        self.ckHindernisse = QtGui.QCheckBox(self.page_5)
        self.ckHindernisse.setGeometry(QtCore.QRect(40, 90, 271, 18))
        self.ckHindernisse.setObjectName(_fromUtf8("ckHindernisse"))
        self.ckButtons.addButton(self.ckHindernisse)
        self.ckBahn = QtGui.QCheckBox(self.page_5)
        self.ckBahn.setEnabled(True)
        self.ckBahn.setGeometry(QtCore.QRect(40, 0, 171, 18))
        self.ckBahn.setObjectName(_fromUtf8("ckBahn"))
        self.ckButtons.addButton(self.ckBahn)
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 391, 116))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.ckForstweg = QtGui.QCheckBox(self.page_2)
        self.ckForstweg.setGeometry(QtCore.QRect(70, 28, 131, 20))
        self.ckForstweg.setObjectName(_fromUtf8("ckForstweg"))
        self.ckButtons.addButton(self.ckForstweg)
        self.ckGueterweg = QtGui.QCheckBox(self.page_2)
        self.ckGueterweg.setEnabled(True)
        self.ckGueterweg.setGeometry(QtCore.QRect(70, 70, 71, 18))
        self.ckGueterweg.setObjectName(_fromUtf8("ckGueterweg"))
        self.ckButtons.addButton(self.ckGueterweg)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 391, 116))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.ckWanderwege = QtGui.QCheckBox(self.page_3)
        self.ckWanderwege.setGeometry(QtCore.QRect(40, 20, 141, 18))
        self.ckWanderwege.setObjectName(_fromUtf8("ckWanderwege"))
        self.ckButtons.addButton(self.ckWanderwege)
        self.ckWinterwanderwege = QtGui.QCheckBox(self.page_3)
        self.ckWinterwanderwege.setGeometry(QtCore.QRect(40, 60, 161, 18))
        self.ckWinterwanderwege.setObjectName(_fromUtf8("ckWinterwanderwege"))
        self.ckButtons.addButton(self.ckWinterwanderwege)
        self.btnWegtafeln = QtGui.QPushButton(self.page_3)
        self.btnWegtafeln.setGeometry(QtCore.QRect(230, 20, 75, 23))
        self.btnWegtafeln.setObjectName(_fromUtf8("btnWegtafeln"))
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 391, 116))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.ckMountainbike = QtGui.QCheckBox(self.page_4)
        self.ckMountainbike.setGeometry(QtCore.QRect(60, 80, 141, 18))
        self.ckMountainbike.setObjectName(_fromUtf8("ckMountainbike"))
        self.ckButtons.addButton(self.ckMountainbike)
        self.ckLandesradrouten = QtGui.QCheckBox(self.page_4)
        self.ckLandesradrouten.setGeometry(QtCore.QRect(60, 20, 141, 18))
        self.ckLandesradrouten.setObjectName(_fromUtf8("ckLandesradrouten"))
        self.ckButtons.addButton(self.ckLandesradrouten)
        self.ckLrr_beschildert = QtGui.QCheckBox(self.page_4)
        self.ckLrr_beschildert.setGeometry(QtCore.QRect(60, 50, 171, 18))
        self.ckLrr_beschildert.setObjectName(_fromUtf8("ckLrr_beschildert"))
        self.ckButtons.addButton(self.ckLrr_beschildert)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.btnRadAbbrechen = QtGui.QPushButton(frmVerkehr)
        self.btnRadAbbrechen.setGeometry(QtCore.QRect(250, 290, 91, 23))
        self.btnRadAbbrechen.setObjectName(_fromUtf8("btnRadAbbrechen"))
        self.btnRadLaden = QtGui.QPushButton(frmVerkehr)
        self.btnRadLaden.setGeometry(QtCore.QRect(60, 290, 101, 23))
        self.btnRadLaden.setObjectName(_fromUtf8("btnRadLaden"))
        self.line = QtGui.QFrame(frmVerkehr)
        self.line.setGeometry(QtCore.QRect(0, 260, 411, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))

        self.retranslateUi(frmVerkehr)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnRadLaden, QtCore.SIGNAL(_fromUtf8("clicked()")), frmVerkehr.lade_daten)
        QtCore.QObject.connect(self.btnRadAbbrechen, QtCore.SIGNAL(_fromUtf8("clicked()")), frmVerkehr.abbrechen)
        QtCore.QObject.connect(self.btnWegtafeln, QtCore.SIGNAL(_fromUtf8("clicked()")), frmVerkehr.suche_wegtafeln)
        QtCore.QMetaObject.connectSlotsByName(frmVerkehr)

    def retranslateUi(self, frmVerkehr):
        frmVerkehr.setWindowTitle(QtGui.QApplication.translate("frmVerkehr", "Verkehr, Transport, Tourismus", None, QtGui.QApplication.UnicodeUTF8))
        self.ckHauptstrassen.setText(QtGui.QApplication.translate("frmVerkehr", "Autobahn, Schnellstraßen, Landesstraßen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckGemeindestrassen.setText(QtGui.QApplication.translate("frmVerkehr", "Örtliches Straßennetz (Gemeindestraßen)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("frmVerkehr", "Strassen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckOepnv.setText(QtGui.QApplication.translate("frmVerkehr", "Öffentlicher Personenverkehr (ÖPNV)", None, QtGui.QApplication.UnicodeUTF8))
        self.ckSeilbahn.setText(QtGui.QApplication.translate("frmVerkehr", "Seilbahnen und Aufstiegshilfen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckHindernisse.setText(QtGui.QApplication.translate("frmVerkehr", "Flughindernisse", None, QtGui.QApplication.UnicodeUTF8))
        self.ckBahn.setText(QtGui.QApplication.translate("frmVerkehr", "Bahnlinien", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), QtGui.QApplication.translate("frmVerkehr", "Öffentlicher Verkehr, Seilbahnen, Flughindernisse", None, QtGui.QApplication.UnicodeUTF8))
        self.ckForstweg.setText(QtGui.QApplication.translate("frmVerkehr", "Forstwege", None, QtGui.QApplication.UnicodeUTF8))
        self.ckGueterweg.setText(QtGui.QApplication.translate("frmVerkehr", "Güterwege", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("frmVerkehr", "Forst- und Güterwege", None, QtGui.QApplication.UnicodeUTF8))
        self.ckWanderwege.setText(QtGui.QApplication.translate("frmVerkehr", "Wanderwege", None, QtGui.QApplication.UnicodeUTF8))
        self.ckWinterwanderwege.setText(QtGui.QApplication.translate("frmVerkehr", "Winterwanderwege", None, QtGui.QApplication.UnicodeUTF8))
        self.btnWegtafeln.setText(QtGui.QApplication.translate("frmVerkehr", "Wegtafeln", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("frmVerkehr", "Wanderwege", None, QtGui.QApplication.UnicodeUTF8))
        self.ckMountainbike.setText(QtGui.QApplication.translate("frmVerkehr", "Mountainbikerouten", None, QtGui.QApplication.UnicodeUTF8))
        self.ckLandesradrouten.setText(QtGui.QApplication.translate("frmVerkehr", "Landesradrouten", None, QtGui.QApplication.UnicodeUTF8))
        self.ckLrr_beschildert.setText(QtGui.QApplication.translate("frmVerkehr", "Landesradrouten beschildert", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), QtGui.QApplication.translate("frmVerkehr", "Radwege und Mountainbikerouten", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRadAbbrechen.setText(QtGui.QApplication.translate("frmVerkehr", "Schließen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRadLaden.setText(QtGui.QApplication.translate("frmVerkehr", "Daten laden", None, QtGui.QApplication.UnicodeUTF8))

