# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_gstsuche.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmGstsuche(object):
    def setupUi(self, frmGstsuche):
        frmGstsuche.setObjectName("frmGstsuche")
        frmGstsuche.resize(421, 835)
        frmGstsuche.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox = QtWidgets.QGroupBox(frmGstsuche)
        self.groupBox.setGeometry(QtCore.QRect(30, 740, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btUrmappe = QtWidgets.QPushButton(self.groupBox)
        self.btUrmappe.setGeometry(QtCore.QRect(40, 30, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btUrmappe.setFont(font)
        self.btUrmappe.setObjectName("btUrmappe")
        self.groupBox_2 = QtWidgets.QGroupBox(frmGstsuche)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 650, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btObjektdaten = QtWidgets.QPushButton(self.groupBox_2)
        self.btObjektdaten.setGeometry(QtCore.QRect(40, 30, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btObjektdaten.setFont(font)
        self.btObjektdaten.setObjectName("btObjektdaten")
        self.gbDkm = QtWidgets.QGroupBox(frmGstsuche)
        self.gbDkm.setGeometry(QtCore.QRect(30, 10, 361, 631))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbDkm.setFont(font)
        self.gbDkm.setObjectName("gbDkm")
        self.groupBox_3 = QtWidgets.QGroupBox(self.gbDkm)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 30, 321, 201))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btGmdChoice = QtWidgets.QPushButton(self.groupBox_3)
        self.btGmdChoice.setGeometry(QtCore.QRect(150, 130, 31, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btGmdChoice.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btGmdChoice.setFont(font)
        self.btGmdChoice.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btGmdChoice.setCheckable(True)
        self.btGmdChoice.setChecked(False)
        self.btGmdChoice.setObjectName("btGmdChoice")
        self.lstPolgem = QtWidgets.QListView(self.groupBox_3)
        self.lstPolgem.setGeometry(QtCore.QRect(10, 20, 131, 131))
        self.lstPolgem.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Austria))
        self.lstPolgem.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.lstPolgem.setTabKeyNavigation(False)
        self.lstPolgem.setObjectName("lstPolgem")
        self.lstKatgem = QtWidgets.QListView(self.groupBox_3)
        self.lstKatgem.setGeometry(QtCore.QRect(150, 20, 161, 101))
        self.lstKatgem.setTabKeyNavigation(False)
        self.lstKatgem.setObjectName("lstKatgem")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 130, 78, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rbKG = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbKG.setObjectName("rbKG")
        self.verticalLayout_3.addWidget(self.rbKG)
        self.rbName = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbName.setChecked(True)
        self.rbName.setObjectName("rbName")
        self.verticalLayout_3.addWidget(self.rbName)
        self.btnVorarlberg = QtWidgets.QPushButton(self.groupBox_3)
        self.btnVorarlberg.setGeometry(QtCore.QRect(24, 160, 111, 23))
        self.btnVorarlberg.setObjectName("btnVorarlberg")
        self.groupBox_4 = QtWidgets.QGroupBox(self.gbDkm)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 240, 321, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.txtGstnr = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtGstnr.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.txtGstnr.setObjectName("txtGstnr")
        self.btnGstsuche = QtWidgets.QPushButton(self.groupBox_4)
        self.btnGstsuche.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.btnGstsuche.setObjectName("btnGstsuche")
        self.gefunden = QtWidgets.QLineEdit(self.groupBox_4)
        self.gefunden.setGeometry(QtCore.QRect(10, 60, 291, 21))
        self.gefunden.setFrame(False)
        self.gefunden.setReadOnly(True)
        self.gefunden.setObjectName("gefunden")
        self.groupBox_5 = QtWidgets.QGroupBox(self.gbDkm)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 340, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.btnAlles = QtWidgets.QPushButton(self.groupBox_5)
        self.btnAlles.setGeometry(QtCore.QRect(30, 20, 121, 23))
        self.btnAlles.setObjectName("btnAlles")
        self.btnStandard = QtWidgets.QPushButton(self.groupBox_5)
        self.btnStandard.setGeometry(QtCore.QRect(170, 20, 121, 23))
        self.btnStandard.setObjectName("btnStandard")
        self.groupBox_6 = QtWidgets.QGroupBox(self.gbDkm)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 390, 321, 181))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 10, 139, 157))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.auswahlBoxen = QtWidgets.QButtonGroup(frmGstsuche)
        self.auswahlBoxen.setObjectName("auswahlBoxen")
        self.auswahlBoxen.setExclusive(False)
        self.auswahlBoxen.addButton(self.checkBox_2)
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.auswahlBoxen.addButton(self.checkBox_4)
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.auswahlBoxen.addButton(self.checkBox_9)
        self.verticalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.auswahlBoxen.addButton(self.checkBox_10)
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_13 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.auswahlBoxen.addButton(self.checkBox_13)
        self.verticalLayout_2.addWidget(self.checkBox_13)
        self.checkBox_11 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_11")
        self.auswahlBoxen.addButton(self.checkBox_11)
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_14 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName("checkBox_14")
        self.auswahlBoxen.addButton(self.checkBox_14)
        self.verticalLayout_2.addWidget(self.checkBox_14)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 113, 157))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.auswahlBoxen.addButton(self.checkBox)
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.auswahlBoxen.addButton(self.checkBox_3)
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.auswahlBoxen.addButton(self.checkBox_6)
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.auswahlBoxen.addButton(self.checkBox_5)
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_12 = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.auswahlBoxen.addButton(self.checkBox_12)
        self.verticalLayout.addWidget(self.checkBox_12)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.auswahlBoxen.addButton(self.checkBox_8)
        self.verticalLayout.addWidget(self.checkBox_8)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.auswahlBoxen.addButton(self.checkBox_7)
        self.verticalLayout.addWidget(self.checkBox_7)
        self.btAbbrechen = QtWidgets.QPushButton(self.gbDkm)
        self.btAbbrechen.setGeometry(QtCore.QRect(220, 580, 91, 31))
        self.btAbbrechen.setObjectName("btAbbrechen")
        self.pushButton = QtWidgets.QPushButton(self.gbDkm)
        self.pushButton.setGeometry(QtCore.QRect(60, 580, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.gbDkm.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()

        self.retranslateUi(frmGstsuche)
        self.btGmdChoice.clicked.connect(frmGstsuche.gmd_choice_toggled)
        self.lstPolgem.clicked['QModelIndex'].connect(frmGstsuche.auswahlaenderung)
        self.pushButton.clicked.connect(frmGstsuche.ladeGemeinde)
        self.btnGstsuche.clicked.connect(frmGstsuche.gstsuche)
        self.lstKatgem.clicked['QModelIndex'].connect(frmGstsuche.gstsuche_aktivieren)
        self.btnAlles.clicked.connect(frmGstsuche.alles_auswaehlen)
        self.btnStandard.clicked.connect(frmGstsuche.standard_auswaehlen)
        self.btAbbrechen.clicked.connect(frmGstsuche.closeEvent)
        self.btUrmappe.clicked.connect(frmGstsuche.ladeurmappe)
        self.btObjektdaten.clicked.connect(frmGstsuche.ladeobjekte)
        self.rbName.clicked.connect(frmGstsuche.sort)
        self.rbKG.clicked.connect(frmGstsuche.sort)
        self.btnVorarlberg.clicked.connect(frmGstsuche.landesflaeche)
        QtCore.QMetaObject.connectSlotsByName(frmGstsuche)
        frmGstsuche.setTabOrder(self.lstPolgem, self.lstKatgem)
        frmGstsuche.setTabOrder(self.lstKatgem, self.btGmdChoice)
        frmGstsuche.setTabOrder(self.btGmdChoice, self.btAbbrechen)
        frmGstsuche.setTabOrder(self.btAbbrechen, self.btUrmappe)
        frmGstsuche.setTabOrder(self.btUrmappe, self.btObjektdaten)
        frmGstsuche.setTabOrder(self.btObjektdaten, self.pushButton)
        frmGstsuche.setTabOrder(self.pushButton, self.txtGstnr)
        frmGstsuche.setTabOrder(self.txtGstnr, self.btnGstsuche)
        frmGstsuche.setTabOrder(self.btnGstsuche, self.gefunden)
        frmGstsuche.setTabOrder(self.gefunden, self.btnAlles)
        frmGstsuche.setTabOrder(self.btnAlles, self.btnStandard)
        frmGstsuche.setTabOrder(self.btnStandard, self.checkBox_2)
        frmGstsuche.setTabOrder(self.checkBox_2, self.checkBox_4)
        frmGstsuche.setTabOrder(self.checkBox_4, self.checkBox_9)
        frmGstsuche.setTabOrder(self.checkBox_9, self.checkBox_10)
        frmGstsuche.setTabOrder(self.checkBox_10, self.checkBox_13)
        frmGstsuche.setTabOrder(self.checkBox_13, self.checkBox_11)
        frmGstsuche.setTabOrder(self.checkBox_11, self.checkBox)
        frmGstsuche.setTabOrder(self.checkBox, self.checkBox_3)
        frmGstsuche.setTabOrder(self.checkBox_3, self.checkBox_6)
        frmGstsuche.setTabOrder(self.checkBox_6, self.checkBox_5)
        frmGstsuche.setTabOrder(self.checkBox_5, self.checkBox_12)
        frmGstsuche.setTabOrder(self.checkBox_12, self.checkBox_8)
        frmGstsuche.setTabOrder(self.checkBox_8, self.checkBox_7)

    def retranslateUi(self, frmGstsuche):
        _translate = QtCore.QCoreApplication.translate
        frmGstsuche.setWindowTitle(_translate("frmGstsuche", "DKM,Objektdaten, Urmappe"))
        self.groupBox.setTitle(_translate("frmGstsuche", "Historischer Kataster"))
        self.btUrmappe.setText(_translate("frmGstsuche", "Urmappe 1857"))
        self.groupBox_2.setTitle(_translate("frmGstsuche", "Objektdaten Gemeinden/VKW/VEG"))
        self.btObjektdaten.setText(_translate("frmGstsuche", "Gebäudehaupt- und Nebenkonturen"))
        self.gbDkm.setTitle(_translate("frmGstsuche", "Digitale Katastralmappe (Stand: dd.mm.yyyy)"))
        self.groupBox_3.setTitle(_translate("frmGstsuche", "Auswahl Gemeinde / Landesfläche Vlbg."))
        self.btGmdChoice.setText(_translate("frmGstsuche", "+"))
        self.rbKG.setText(_translate("frmGstsuche", "nach KGNR"))
        self.rbName.setText(_translate("frmGstsuche", "nach Name"))
        self.btnVorarlberg.setText(_translate("frmGstsuche", "Landesfläche Vlbg."))
        self.groupBox_4.setTitle(_translate("frmGstsuche", "Grundstückssuche in"))
        self.btnGstsuche.setText(_translate("frmGstsuche", "Suchen"))
        self.groupBox_5.setTitle(_translate("frmGstsuche", "DKM Ebenen"))
        self.btnAlles.setText(_translate("frmGstsuche", "Alle auswählen"))
        self.btnStandard.setText(_translate("frmGstsuche", "Standardauswahl"))
        self.checkBox_2.setText(_translate("frmGstsuche", "Grundstück Nr"))
        self.checkBox_4.setText(_translate("frmGstsuche", "Nutzungsflächen Umriss"))
        self.checkBox_9.setText(_translate("frmGstsuche", "Sonstige Grenzen"))
        self.checkBox_10.setText(_translate("frmGstsuche", "Sonstige Symbole"))
        self.checkBox_13.setText(_translate("frmGstsuche", "Grenzpunkt Symbole"))
        self.checkBox_11.setText(_translate("frmGstsuche", "Sonstige Texte"))
        self.checkBox_14.setText(_translate("frmGstsuche", "Festpunkt Symbole"))
        self.checkBox.setText(_translate("frmGstsuche", "Grundstücke"))
        self.checkBox_3.setText(_translate("frmGstsuche", "Nutzungsflächen"))
        self.checkBox_6.setText(_translate("frmGstsuche", "Gebäudeflächen"))
        self.checkBox_5.setText(_translate("frmGstsuche", "Nutzungs Symbole"))
        self.checkBox_12.setText(_translate("frmGstsuche", "Grenzpunkt Nr"))
        self.checkBox_8.setText(_translate("frmGstsuche", "Grenzpunkt Infos"))
        self.checkBox_7.setText(_translate("frmGstsuche", "Festpunkte"))
        self.btAbbrechen.setText(_translate("frmGstsuche", "Schließen"))
        self.pushButton.setText(_translate("frmGstsuche", "DKM laden"))

