# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_blattschnitte.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmBlattschnitte(object):
    def setupUi(self, frmBlattschnitte):
        frmBlattschnitte.setObjectName("frmBlattschnitte")
        frmBlattschnitte.resize(293, 504)
        self.ButtonBlattschnitteOk = QtWidgets.QPushButton(frmBlattschnitte)
        self.ButtonBlattschnitteOk.setGeometry(QtCore.QRect(20, 450, 111, 31))
        self.ButtonBlattschnitteOk.setObjectName("ButtonBlattschnitteOk")
        self.ButtonBlattschnitteCancel = QtWidgets.QPushButton(frmBlattschnitte)
        self.ButtonBlattschnitteCancel.setGeometry(QtCore.QRect(160, 450, 111, 31))
        self.ButtonBlattschnitteCancel.setObjectName("ButtonBlattschnitteCancel")
        self.frame = QtWidgets.QFrame(frmBlattschnitte)
        self.frame.setGeometry(QtCore.QRect(20, 20, 251, 341))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 22, 144, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkButtonsGroup = QtWidgets.QButtonGroup(frmBlattschnitte)
        self.checkButtonsGroup.setObjectName("checkButtonsGroup")
        self.checkButtonsGroup.setExclusive(False)
        self.checkButtonsGroup.addButton(self.checkBox)
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkButtonsGroup.addButton(self.checkBox_2)
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkButtonsGroup.addButton(self.checkBox_3)
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkButtonsGroup.addButton(self.checkBox_4)
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkButtonsGroup.addButton(self.checkBox_5)
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkButtonsGroup.addButton(self.checkBox_6)
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkButtonsGroup.addButton(self.checkBox_7)
        self.verticalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkButtonsGroup.addButton(self.checkBox_8)
        self.verticalLayout.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkButtonsGroup.addButton(self.checkBox_9)
        self.verticalLayout.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkButtonsGroup.addButton(self.checkBox_10)
        self.verticalLayout.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkButtonsGroup.addButton(self.checkBox_11)
        self.verticalLayout.addWidget(self.checkBox_11)
        self.frame_2 = QtWidgets.QFrame(frmBlattschnitte)
        self.frame_2.setGeometry(QtCore.QRect(20, 380, 251, 61))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.radioButton = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton.setGeometry(QtCore.QRect(40, 10, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 30, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(frmBlattschnitte)
        self.ButtonBlattschnitteOk.clicked.connect(frmBlattschnitte.accept)
        self.ButtonBlattschnitteCancel.clicked.connect(frmBlattschnitte.close)
        QtCore.QMetaObject.connectSlotsByName(frmBlattschnitte)

    def retranslateUi(self, frmBlattschnitte):
        _translate = QtCore.QCoreApplication.translate
        frmBlattschnitte.setWindowTitle(_translate("frmBlattschnitte", "Blattschnitte"))
        self.ButtonBlattschnitteOk.setText(_translate("frmBlattschnitte", "Themen laden"))
        self.ButtonBlattschnitteCancel.setText(_translate("frmBlattschnitte", "Schließen"))
        self.checkBox.setText(_translate("frmBlattschnitte", "Blattschnitt ÖK"))
        self.checkBox_2.setText(_translate("frmBlattschnitte", "Blattschnitt 50000"))
        self.checkBox_3.setText(_translate("frmBlattschnitte", "Blattschnitt 25000"))
        self.checkBox_4.setText(_translate("frmBlattschnitte", "Blattschnitt 20000"))
        self.checkBox_5.setText(_translate("frmBlattschnitte", "Blattschnitt 10000"))
        self.checkBox_6.setText(_translate("frmBlattschnitte", "Blattschnitt 5000"))
        self.checkBox_7.setText(_translate("frmBlattschnitte", "Blattschnitt 2500"))
        self.checkBox_8.setText(_translate("frmBlattschnitte", "Blattschnitt 2000"))
        self.checkBox_9.setText(_translate("frmBlattschnitte", "Blattschnitt 1000"))
        self.checkBox_10.setText(_translate("frmBlattschnitte", "Blattschnitt Urmappe"))
        self.checkBox_11.setText(_translate("frmBlattschnitte", "Koordinatennetz"))
        self.radioButton.setText(_translate("frmBlattschnitte", "Mit Nummerierung"))
        self.radioButton_2.setText(_translate("frmBlattschnitte", "Ohne Nummerierung"))

