# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_adresssuche_pg.ui'
#
# Created: Wed Jul 13 08:19:46 2016
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmAdresssuche(object):
    def setupUi(self, frmAdresssuche):
        frmAdresssuche.setObjectName(_fromUtf8("frmAdresssuche"))
        frmAdresssuche.resize(481, 549)
        self.schliessen = QtGui.QPushButton(frmAdresssuche)
        self.schliessen.setGeometry(QtCore.QRect(170, 500, 151, 31))
        self.schliessen.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.schliessen.setAutoDefault(False)
        self.schliessen.setObjectName(_fromUtf8("schliessen"))
        self.groupBox = QtGui.QGroupBox(frmAdresssuche)
        self.groupBox.setGeometry(QtCore.QRect(20, 400, 441, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.ButtonAdressenOk = QtGui.QPushButton(self.groupBox)
        self.ButtonAdressenOk.setGeometry(QtCore.QRect(240, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ButtonAdressenOk.setFont(font)
        self.ButtonAdressenOk.setAutoDefault(False)
        self.ButtonAdressenOk.setObjectName(_fromUtf8("ButtonAdressenOk"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 20, 138, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.buttonGroup = QtGui.QButtonGroup(frmAdresssuche)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.checkBox_3)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 50, 155, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.buttonGroup.addButton(self.checkBox_2)
        self.groupBox_2 = QtGui.QGroupBox(frmAdresssuche)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 441, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.laden = QtGui.QPushButton(self.groupBox_2)
        self.laden.setGeometry(QtCore.QRect(20, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.laden.setFont(font)
        self.laden.setAutoDefault(False)
        self.laden.setObjectName(_fromUtf8("laden"))
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(310, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 30, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.leStrasse = QtGui.QLineEdit(self.groupBox_3)
        self.leStrasse.setGeometry(QtCore.QRect(10, 20, 381, 21))
        self.leStrasse.setObjectName(_fromUtf8("leStrasse"))
        self.treeAdressen = QtGui.QTreeView(self.groupBox_2)
        self.treeAdressen.setGeometry(QtCore.QRect(20, 120, 401, 192))
        self.treeAdressen.setObjectName(_fromUtf8("treeAdressen"))
        self.treeAdressen.header().setVisible(False)
        self.btnEinklappen = QtGui.QPushButton(self.groupBox_2)
        self.btnEinklappen.setGeometry(QtCore.QRect(20, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnEinklappen.setFont(font)
        self.btnEinklappen.setObjectName(_fromUtf8("btnEinklappen"))

        self.retranslateUi(frmAdresssuche)
        QtCore.QObject.connect(self.laden, QtCore.SIGNAL(_fromUtf8("clicked()")), frmAdresssuche.accept)
        QtCore.QObject.connect(self.schliessen, QtCore.SIGNAL(_fromUtf8("clicked()")), frmAdresssuche.closeEvent)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), frmAdresssuche.adrClear)
        QtCore.QObject.connect(self.ButtonAdressenOk, QtCore.SIGNAL(_fromUtf8("clicked()")), frmAdresssuche.themenLaden)
        QtCore.QMetaObject.connectSlotsByName(frmAdresssuche)

    def retranslateUi(self, frmAdresssuche):
        frmAdresssuche.setWindowTitle(QtGui.QApplication.translate("frmAdresssuche", "Adresssuche", None, QtGui.QApplication.UnicodeUTF8))
        self.schliessen.setText(QtGui.QApplication.translate("frmAdresssuche", "Fenster Schließen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmAdresssuche", "Adresslayer laden", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonAdressenOk.setText(QtGui.QApplication.translate("frmAdresssuche", "Thema laden", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("frmAdresssuche", "Adressen Gemeinde", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("frmAdresssuche", "Adressen Landesfläche", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmAdresssuche", "Adressen suchen und anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.laden.setText(QtGui.QApplication.translate("frmAdresssuche", "in View darstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("frmAdresssuche", "in View löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("frmAdresssuche", "Strassensuche Landesweit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEinklappen.setText(QtGui.QApplication.translate("frmAdresssuche", "alles einklappen", None, QtGui.QApplication.UnicodeUTF8))

