# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_klima.ui'
#
# Created: Fri Jan 31 09:41:53 2014
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmKlima(object):
    def setupUi(self, frmKlima):
        frmKlima.setObjectName(_fromUtf8("frmKlima"))
        frmKlima.resize(359, 587)
        self.ButtonBlattschnitteOk = QtGui.QPushButton(frmKlima)
        self.ButtonBlattschnitteOk.setEnabled(True)
        self.ButtonBlattschnitteOk.setGeometry(QtCore.QRect(10, 480, 101, 23))
        self.ButtonBlattschnitteOk.setObjectName(_fromUtf8("ButtonBlattschnitteOk"))
        self.ButtonBlattschnitteCancel = QtGui.QPushButton(frmKlima)
        self.ButtonBlattschnitteCancel.setEnabled(True)
        self.ButtonBlattschnitteCancel.setGeometry(QtCore.QRect(110, 530, 131, 23))
        self.ButtonBlattschnitteCancel.setObjectName(_fromUtf8("ButtonBlattschnitteCancel"))
        self.toolBox = QtGui.QToolBox(frmKlima)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 331, 451))
        self.toolBox.setFrameShape(QtGui.QFrame.Box)
        self.toolBox.setFrameShadow(QtGui.QFrame.Sunken)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.tbTemp = QtGui.QWidget()
        self.tbTemp.setGeometry(QtCore.QRect(0, 0, 329, 179))
        self.tbTemp.setObjectName(_fromUtf8("tbTemp"))
        self.ckTempMaxJahresmittel = QtGui.QCheckBox(self.tbTemp)
        self.ckTempMaxJahresmittel.setGeometry(QtCore.QRect(10, 30, 238, 17))
        self.ckTempMaxJahresmittel.setObjectName(_fromUtf8("ckTempMaxJahresmittel"))
        self.ckButtons = QtGui.QButtonGroup(frmKlima)
        self.ckButtons.setObjectName(_fromUtf8("ckButtons"))
        self.ckButtons.addButton(self.ckTempMaxJahresmittel)
        self.ckTempJahresmittel = QtGui.QCheckBox(self.tbTemp)
        self.ckTempJahresmittel.setGeometry(QtCore.QRect(10, 0, 176, 17))
        self.ckTempJahresmittel.setObjectName(_fromUtf8("ckTempJahresmittel"))
        self.ckButtons.addButton(self.ckTempJahresmittel)
        self.ckHeisstage = QtGui.QCheckBox(self.tbTemp)
        self.ckHeisstage.setGeometry(QtCore.QRect(10, 60, 238, 17))
        self.ckHeisstage.setObjectName(_fromUtf8("ckHeisstage"))
        self.ckButtons.addButton(self.ckHeisstage)
        self.ckEistage = QtGui.QCheckBox(self.tbTemp)
        self.ckEistage.setGeometry(QtCore.QRect(10, 90, 238, 17))
        self.ckEistage.setObjectName(_fromUtf8("ckEistage"))
        self.ckButtons.addButton(self.ckEistage)
        self.ckHeizgrad = QtGui.QCheckBox(self.tbTemp)
        self.ckHeizgrad.setGeometry(QtCore.QRect(10, 120, 238, 17))
        self.ckHeizgrad.setObjectName(_fromUtf8("ckHeizgrad"))
        self.ckButtons.addButton(self.ckHeizgrad)
        self.ckVegetationsperiode = QtGui.QCheckBox(self.tbTemp)
        self.ckVegetationsperiode.setGeometry(QtCore.QRect(10, 150, 238, 17))
        self.ckVegetationsperiode.setObjectName(_fromUtf8("ckVegetationsperiode"))
        self.ckButtons.addButton(self.ckVegetationsperiode)
        self.toolBox.addItem(self.tbTemp, _fromUtf8(""))
        self.tbFeuchte = QtGui.QWidget()
        self.tbFeuchte.setGeometry(QtCore.QRect(0, 0, 329, 179))
        self.tbFeuchte.setObjectName(_fromUtf8("tbFeuchte"))
        self.toolBox.addItem(self.tbFeuchte, _fromUtf8(""))
        self.tabBew = QtGui.QWidget()
        self.tabBew.setGeometry(QtCore.QRect(0, 0, 329, 179))
        self.tabBew.setObjectName(_fromUtf8("tabBew"))
        self.toolBox.addItem(self.tabBew, _fromUtf8(""))
        self.tabNs = QtGui.QWidget()
        self.tabNs.setGeometry(QtCore.QRect(0, 0, 329, 179))
        self.tabNs.setObjectName(_fromUtf8("tabNs"))
        self.widget = QtGui.QWidget(self.tabNs)
        self.widget.setGeometry(QtCore.QRect(10, 10, 246, 65))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ckNsJahrGesamt = QtGui.QCheckBox(self.widget)
        self.ckNsJahrGesamt.setObjectName(_fromUtf8("ckNsJahrGesamt"))
        self.ckButtons.addButton(self.ckNsJahrGesamt)
        self.verticalLayout.addWidget(self.ckNsJahrGesamt)
        self.ckNTage1mm = QtGui.QCheckBox(self.widget)
        self.ckNTage1mm.setObjectName(_fromUtf8("ckNTage1mm"))
        self.ckButtons.addButton(self.ckNTage1mm)
        self.verticalLayout.addWidget(self.ckNTage1mm)
        self.ckNTage10mm = QtGui.QCheckBox(self.widget)
        self.ckNTage10mm.setObjectName(_fromUtf8("ckNTage10mm"))
        self.ckButtons.addButton(self.ckNTage10mm)
        self.verticalLayout.addWidget(self.ckNTage10mm)
        self.toolBox.addItem(self.tabNs, _fromUtf8(""))
        self.tabSchnee = QtGui.QWidget()
        self.tabSchnee.setGeometry(QtCore.QRect(0, 0, 329, 179))
        self.tabSchnee.setObjectName(_fromUtf8("tabSchnee"))
        self.toolBox.addItem(self.tabSchnee, _fromUtf8(""))
        self.tabVerd = QtGui.QWidget()
        self.tabVerd.setGeometry(QtCore.QRect(0, 0, 329, 179))
        self.tabVerd.setObjectName(_fromUtf8("tabVerd"))
        self.toolBox.addItem(self.tabVerd, _fromUtf8(""))
        self.tabDruck = QtGui.QWidget()
        self.tabDruck.setGeometry(QtCore.QRect(0, 0, 329, 179))
        self.tabDruck.setObjectName(_fromUtf8("tabDruck"))
        self.toolBox.addItem(self.tabDruck, _fromUtf8(""))
        self.tabWind = QtGui.QWidget()
        self.tabWind.setGeometry(QtCore.QRect(0, 0, 329, 179))
        self.tabWind.setObjectName(_fromUtf8("tabWind"))
        self.toolBox.addItem(self.tabWind, _fromUtf8(""))
        self.tabSolar = QtGui.QWidget()
        self.tabSolar.setGeometry(QtCore.QRect(0, 0, 329, 179))
        self.tabSolar.setObjectName(_fromUtf8("tabSolar"))
        self.toolBox.addItem(self.tabSolar, _fromUtf8(""))
        self.tabKomb = QtGui.QWidget()
        self.tabKomb.setGeometry(QtCore.QRect(0, 0, 329, 179))
        self.tabKomb.setObjectName(_fromUtf8("tabKomb"))
        self.toolBox.addItem(self.tabKomb, _fromUtf8(""))
        self.btnKartePDF = QtGui.QPushButton(frmKlima)
        self.btnKartePDF.setGeometry(QtCore.QRect(120, 480, 101, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnKartePDF.sizePolicy().hasHeightForWidth())
        self.btnKartePDF.setSizePolicy(sizePolicy)
        self.btnKartePDF.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnKartePDF.setObjectName(_fromUtf8("btnKartePDF"))
        self.btnBeschreibungPDF = QtGui.QPushButton(frmKlima)
        self.btnBeschreibungPDF.setGeometry(QtCore.QRect(230, 480, 121, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBeschreibungPDF.sizePolicy().hasHeightForWidth())
        self.btnBeschreibungPDF.setSizePolicy(sizePolicy)
        self.btnBeschreibungPDF.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnBeschreibungPDF.setObjectName(_fromUtf8("btnBeschreibungPDF"))

        self.retranslateUi(frmKlima)
        QtCore.QObject.connect(self.ButtonBlattschnitteOk, QtCore.SIGNAL(_fromUtf8("clicked()")), frmKlima.accept)
        QtCore.QObject.connect(self.ButtonBlattschnitteCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), frmKlima.close)
        QtCore.QObject.connect(self.btnKartePDF, QtCore.SIGNAL(_fromUtf8("clicked()")), frmKlima.Kartebutton)
        QtCore.QObject.connect(self.btnBeschreibungPDF, QtCore.SIGNAL(_fromUtf8("clicked()")), frmKlima.Kartebutton)
        QtCore.QMetaObject.connectSlotsByName(frmKlima)

    def retranslateUi(self, frmKlima):
        frmKlima.setWindowTitle(QtGui.QApplication.translate("frmKlima", "Klima", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonBlattschnitteOk.setText(QtGui.QApplication.translate("frmKlima", "Themen laden", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonBlattschnitteCancel.setText(QtGui.QApplication.translate("frmKlima", "Schließen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckTempMaxJahresmittel.setText(QtGui.QApplication.translate("frmKlima", "Mittleres Jahresmaximum der Lufttemperatur", None, QtGui.QApplication.UnicodeUTF8))
        self.ckTempJahresmittel.setText(QtGui.QApplication.translate("frmKlima", "Jahresmittel der Lufttemperatur", None, QtGui.QApplication.UnicodeUTF8))
        self.ckHeisstage.setText(QtGui.QApplication.translate("frmKlima", "Mittlere Zahl von heissen Tagen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckEistage.setText(QtGui.QApplication.translate("frmKlima", "Mittlere Zahl von Eistagen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckHeizgrad.setText(QtGui.QApplication.translate("frmKlima", "Mittlere jährliche Heizgradtagszahl", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVegetationsperiode.setText(QtGui.QApplication.translate("frmKlima", "Dauer der Vegetationsperiode", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tbTemp), QtGui.QApplication.translate("frmKlima", "Temperatur", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tbFeuchte), QtGui.QApplication.translate("frmKlima", "Feuchte", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabBew), QtGui.QApplication.translate("frmKlima", "Bewölkung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckNsJahrGesamt.setText(QtGui.QApplication.translate("frmKlima", "Jahresniederschlagssumme", None, QtGui.QApplication.UnicodeUTF8))
        self.ckNTage1mm.setText(QtGui.QApplication.translate("frmKlima", "Anzahl der Tage mit mind. 1 mm Niederschlag", None, QtGui.QApplication.UnicodeUTF8))
        self.ckNTage10mm.setText(QtGui.QApplication.translate("frmKlima", "Anzahl der Tage mit mind. 10 mm Niederschlag", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabNs), QtGui.QApplication.translate("frmKlima", "Niederschlag", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabSchnee), QtGui.QApplication.translate("frmKlima", "Schnee", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabVerd), QtGui.QApplication.translate("frmKlima", "Verdunstung", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabDruck), QtGui.QApplication.translate("frmKlima", "Luftdruck", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabWind), QtGui.QApplication.translate("frmKlima", "Wind", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabSolar), QtGui.QApplication.translate("frmKlima", "Solare Einstrahlung", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabKomb), QtGui.QApplication.translate("frmKlima", "Kombi-Grössen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnKartePDF.setText(QtGui.QApplication.translate("frmKlima", "PDF Karte laden", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBeschreibungPDF.setText(QtGui.QApplication.translate("frmKlima", "Beschreibung laden", None, QtGui.QApplication.UnicodeUTF8))

