# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_topokarten.ui'
#
# Created: Wed Nov 07 11:37:48 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmTopokarten(object):
    def setupUi(self, frmTopokarten):
        frmTopokarten.setObjectName(_fromUtf8("frmTopokarten"))
        frmTopokarten.resize(382, 524)
        self.ButtonTopokartenOk = QtGui.QPushButton(frmTopokarten)
        self.ButtonTopokartenOk.setGeometry(QtCore.QRect(30, 470, 121, 23))
        self.ButtonTopokartenOk.setObjectName(_fromUtf8("ButtonTopokartenOk"))
        self.ButtonTopokartenCancel = QtGui.QPushButton(frmTopokarten)
        self.ButtonTopokartenCancel.setGeometry(QtCore.QRect(220, 470, 121, 23))
        self.ButtonTopokartenCancel.setObjectName(_fromUtf8("ButtonTopokartenCancel"))
        self.toolBox = QtGui.QToolBox(frmTopokarten)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 361, 441))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 361, 387))
        self.page.setObjectName(_fromUtf8("page"))
        self.groupBox_2 = QtGui.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 310, 281, 61))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.checkButtonsGroup = QtGui.QButtonGroup(frmTopokarten)
        self.checkButtonsGroup.setObjectName(_fromUtf8("checkButtonsGroup"))
        self.checkButtonsGroup.addButton(self.radioButton_11)
        self.verticalLayout_2.addWidget(self.radioButton_11)
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(40, 10, 281, 293))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkButtonsGroup.addButton(self.checkBox)
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkButtonsGroup.addButton(self.checkBox_2)
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkButtonsGroup.addButton(self.checkBox_3)
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkButtonsGroup.addButton(self.checkBox_4)
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkButtonsGroup.addButton(self.checkBox_5)
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkButtonsGroup.addButton(self.checkBox_6)
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkButtonsGroup.addButton(self.checkBox_7)
        self.verticalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.checkButtonsGroup.addButton(self.checkBox_8)
        self.verticalLayout.addWidget(self.checkBox_8)
        self.checkBox_9 = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.checkButtonsGroup.addButton(self.checkBox_9)
        self.verticalLayout.addWidget(self.checkBox_9)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.page_2)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 30, 265, 261))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 219, 212))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_12 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.checkButtonsGroup.addButton(self.checkBox_12)
        self.verticalLayout_3.addWidget(self.checkBox_12)
        self.checkBox_15 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.checkButtonsGroup.addButton(self.checkBox_15)
        self.verticalLayout_3.addWidget(self.checkBox_15)
        self.checkBox_17 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_17.setFont(font)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.checkButtonsGroup.addButton(self.checkBox_17)
        self.verticalLayout_3.addWidget(self.checkBox_17)
        self.checkBox_26 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_26.setFont(font)
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.checkButtonsGroup.addButton(self.checkBox_26)
        self.verticalLayout_3.addWidget(self.checkBox_26)
        self.checkBox_29 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_29.setFont(font)
        self.checkBox_29.setObjectName(_fromUtf8("checkBox_29"))
        self.checkButtonsGroup.addButton(self.checkBox_29)
        self.verticalLayout_3.addWidget(self.checkBox_29)
        self.checkBox_30 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_30.setFont(font)
        self.checkBox_30.setObjectName(_fromUtf8("checkBox_30"))
        self.checkButtonsGroup.addButton(self.checkBox_30)
        self.verticalLayout_3.addWidget(self.checkBox_30)
        self.checkBox_31 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_31.setFont(font)
        self.checkBox_31.setObjectName(_fromUtf8("checkBox_31"))
        self.checkButtonsGroup.addButton(self.checkBox_31)
        self.verticalLayout_3.addWidget(self.checkBox_31)
        self.checkBox_32 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_32.setFont(font)
        self.checkBox_32.setObjectName(_fromUtf8("checkBox_32"))
        self.checkButtonsGroup.addButton(self.checkBox_32)
        self.verticalLayout_3.addWidget(self.checkBox_32)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))

        self.retranslateUi(frmTopokarten)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.ButtonTopokartenOk, QtCore.SIGNAL(_fromUtf8("clicked()")), frmTopokarten.accept)
        QtCore.QObject.connect(self.ButtonTopokartenCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), frmTopokarten.close)
        QtCore.QMetaObject.connectSlotsByName(frmTopokarten)

    def retranslateUi(self, frmTopokarten):
        frmTopokarten.setWindowTitle(QtGui.QApplication.translate("frmTopokarten", "Topographische Karten", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonTopokartenOk.setText(QtGui.QApplication.translate("frmTopokarten", "Themen laden", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonTopokartenCancel.setText(QtGui.QApplication.translate("frmTopokarten", "Schließen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmTopokarten", "Sonstiges", "aaaa", QtGui.QApplication.UnicodeUTF8))
        self.radioButton_11.setText(QtGui.QApplication.translate("frmTopokarten", "Namen ÖK50", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmTopokarten", "Topographische Karten", "aaaa", QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("frmTopokarten", "Topogr. Karte (VoGIS)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("frmTopokarten", "Topogr. Karte Winter (VoGIS)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("frmTopokarten", "Topogr. Karte PDF-Ebenen (VoGIS)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("frmTopokarten", "Topogr. Karte (Verkehrsverbund)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("frmTopokarten", "ÖK 1:50.000 Vlbg. (BEV)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("frmTopokarten", "ÖK 1:50.000 Vlbg. + Umg. (BEV)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("frmTopokarten", "Heimatkarte 1:100.000 (FreytagBerndt)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("frmTopokarten", "ÖK 1:200.000  (BEV)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("frmTopokarten", "ÖK 1:500.000  (BEV)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("frmTopokarten", "Topographische Karten", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("frmTopokarten", "Historische Karten", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("frmTopokarten", "Urmappe:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_15.setText(QtGui.QApplication.translate("frmTopokarten", "3. Landesaufnahme 1871 - 1872:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_17.setText(QtGui.QApplication.translate("frmTopokarten", "Reambulierte 3. LA 1887:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_26.setText(QtGui.QApplication.translate("frmTopokarten", "Spezialkarten 1908-15 / 1934-37:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_29.setText(QtGui.QApplication.translate("frmTopokarten", "Provisorische ÖK 1946-47:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_30.setText(QtGui.QApplication.translate("frmTopokarten", "ÖK50 1953-67:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_31.setText(QtGui.QApplication.translate("frmTopokarten", "ÖK50 1961-74:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_32.setText(QtGui.QApplication.translate("frmTopokarten", "ÖK50 1971-80:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("frmTopokarten", "Historische Karten", None, QtGui.QApplication.UnicodeUTF8))

