# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_naturschutz.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmNaturschutz(object):
    def setupUi(self, frmNaturschutz):
        frmNaturschutz.setObjectName("frmNaturschutz")
        frmNaturschutz.resize(567, 422)
        self.toolBox = QtWidgets.QToolBox(frmNaturschutz)
        self.toolBox.setGeometry(QtCore.QRect(6, 10, 561, 311))
        self.toolBox.setObjectName("toolBox")
        self.gebietsschutz = QtWidgets.QWidget()
        self.gebietsschutz.setGeometry(QtCore.QRect(0, 0, 561, 230))
        self.gebietsschutz.setObjectName("gebietsschutz")
        self.layoutWidget = QtWidgets.QWidget(self.gebietsschutz)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 10, 282, 188))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ckNatura2000 = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckNatura2000.setObjectName("ckNatura2000")
        self.ckButtons = QtWidgets.QButtonGroup(frmNaturschutz)
        self.ckButtons.setObjectName("ckButtons")
        self.ckButtons.addButton(self.ckNatura2000)
        self.gridLayout.addWidget(self.ckNatura2000, 0, 0, 1, 1)
        self.ckNaturschutzgebiete = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckNaturschutzgebiete.setObjectName("ckNaturschutzgebiete")
        self.ckButtons.addButton(self.ckNaturschutzgebiete)
        self.gridLayout.addWidget(self.ckNaturschutzgebiete, 1, 0, 1, 1)
        self.ckLandschaftsschutzgebiete = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckLandschaftsschutzgebiete.setObjectName("ckLandschaftsschutzgebiete")
        self.ckButtons.addButton(self.ckLandschaftsschutzgebiete)
        self.gridLayout.addWidget(self.ckLandschaftsschutzgebiete, 2, 0, 1, 1)
        self.ckPflanzenschutzgebiete = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckPflanzenschutzgebiete.setObjectName("ckPflanzenschutzgebiete")
        self.ckButtons.addButton(self.ckPflanzenschutzgebiete)
        self.gridLayout.addWidget(self.ckPflanzenschutzgebiete, 3, 0, 1, 1)
        self.ckGeschLandschaftsteil = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckGeschLandschaftsteil.setObjectName("ckGeschLandschaftsteil")
        self.ckButtons.addButton(self.ckGeschLandschaftsteil)
        self.gridLayout.addWidget(self.ckGeschLandschaftsteil, 4, 0, 1, 1)
        self.ckBiosphaerenpark = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckBiosphaerenpark.setObjectName("ckBiosphaerenpark")
        self.ckButtons.addButton(self.ckBiosphaerenpark)
        self.gridLayout.addWidget(self.ckBiosphaerenpark, 5, 0, 1, 1)
        self.ckRuhezone = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckRuhezone.setObjectName("ckRuhezone")
        self.ckButtons.addButton(self.ckRuhezone)
        self.gridLayout.addWidget(self.ckRuhezone, 6, 0, 1, 1)
        self.ckOertlichesSchutzgebiet = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckOertlichesSchutzgebiet.setObjectName("ckOertlichesSchutzgebiet")
        self.ckButtons.addButton(self.ckOertlichesSchutzgebiet)
        self.gridLayout.addWidget(self.ckOertlichesSchutzgebiet, 7, 0, 1, 1)
        self.toolBox.addItem(self.gebietsschutz, "")
        self.inventar = QtWidgets.QWidget()
        self.inventar.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.inventar.setObjectName("inventar")
        self.ckBiotopinventar = QtWidgets.QCheckBox(self.inventar)
        self.ckBiotopinventar.setGeometry(QtCore.QRect(50, 20, 171, 18))
        self.ckBiotopinventar.setObjectName("ckBiotopinventar")
        self.ckButtons.addButton(self.ckBiotopinventar)
        self.groupBox = QtWidgets.QGroupBox(self.inventar)
        self.groupBox.setGeometry(QtCore.QRect(70, 70, 401, 141))
        self.groupBox.setObjectName("groupBox")
        self.btnGemeindebericht = QtWidgets.QPushButton(self.groupBox)
        self.btnGemeindebericht.setGeometry(QtCore.QRect(30, 90, 141, 31))
        self.btnGemeindebericht.setObjectName("btnGemeindebericht")
        self.btnA3Plaene = QtWidgets.QPushButton(self.groupBox)
        self.btnA3Plaene.setGeometry(QtCore.QRect(210, 90, 141, 31))
        self.btnA3Plaene.setObjectName("btnA3Plaene")
        self.cmbGemeinden = QtWidgets.QComboBox(self.groupBox)
        self.cmbGemeinden.setGeometry(QtCore.QRect(30, 30, 191, 22))
        self.cmbGemeinden.setObjectName("cmbGemeinden")
        self.btGmdChoice = QtWidgets.QPushButton(self.groupBox)
        self.btGmdChoice.setGeometry(QtCore.QRect(300, 30, 31, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btGmdChoice.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btGmdChoice.setFont(font)
        self.btGmdChoice.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btGmdChoice.setCheckable(True)
        self.btGmdChoice.setChecked(False)
        self.btGmdChoice.setObjectName("btGmdChoice")
        self.toolBox.addItem(self.inventar, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_2.setObjectName("page_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(71, 31, 179, 88))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ckStreuwiesen_2000 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ckStreuwiesen_2000.setObjectName("ckStreuwiesen_2000")
        self.ckButtons.addButton(self.ckStreuwiesen_2000)
        self.gridLayout_2.addWidget(self.ckStreuwiesen_2000, 1, 0, 1, 1)
        self.ckNaturdenkmale = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ckNaturdenkmale.setObjectName("ckNaturdenkmale")
        self.ckButtons.addButton(self.ckNaturdenkmale)
        self.gridLayout_2.addWidget(self.ckNaturdenkmale, 2, 0, 1, 1)
        self.ckStreuwiesen_2014 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ckStreuwiesen_2014.setObjectName("ckStreuwiesen_2014")
        self.ckButtons.addButton(self.ckStreuwiesen_2014)
        self.gridLayout_2.addWidget(self.ckStreuwiesen_2014, 0, 0, 1, 1)
        self.ckAmphibienzugstellen = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ckAmphibienzugstellen.setObjectName("ckAmphibienzugstellen")
        self.ckButtons.addButton(self.ckAmphibienzugstellen)
        self.gridLayout_2.addWidget(self.ckAmphibienzugstellen, 3, 0, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.line = QtWidgets.QFrame(frmNaturschutz)
        self.line.setGeometry(QtCore.QRect(0, 340, 571, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btnLaden = QtWidgets.QPushButton(frmNaturschutz)
        self.btnLaden.setGeometry(QtCore.QRect(60, 370, 151, 23))
        self.btnLaden.setObjectName("btnLaden")
        self.btnAbbrechen = QtWidgets.QPushButton(frmNaturschutz)
        self.btnAbbrechen.setGeometry(QtCore.QRect(330, 370, 141, 23))
        self.btnAbbrechen.setObjectName("btnAbbrechen")

        self.retranslateUi(frmNaturschutz)
        self.toolBox.setCurrentIndex(0)
        self.btnLaden.clicked.connect(frmNaturschutz.datenladen)
        self.btnAbbrechen.clicked.connect(frmNaturschutz.closeEvent)
        self.btnGemeindebericht.clicked.connect(frmNaturschutz.gemeindebericht)
        self.btnA3Plaene.clicked.connect(frmNaturschutz.a3plaene)
        self.btGmdChoice.clicked.connect(frmNaturschutz.gmd_choice_toggled)
        self.cmbGemeinden.currentIndexChanged['QString'].connect(frmNaturschutz.auswahlaenderung)
        QtCore.QMetaObject.connectSlotsByName(frmNaturschutz)

    def retranslateUi(self, frmNaturschutz):
        _translate = QtCore.QCoreApplication.translate
        frmNaturschutz.setWindowTitle(_translate("frmNaturschutz", "Naturschutz"))
        self.ckNatura2000.setText(_translate("frmNaturschutz", "NATURA 2000 (Europaschutzgebiet)"))
        self.ckNaturschutzgebiete.setText(_translate("frmNaturschutz", "Naturschutzgebiete (inkl. Streuwiesenbiotopverbund)"))
        self.ckLandschaftsschutzgebiete.setText(_translate("frmNaturschutz", "Landschaftsschutzgebiete"))
        self.ckPflanzenschutzgebiete.setText(_translate("frmNaturschutz", "Pflanzenschutzgebiete"))
        self.ckGeschLandschaftsteil.setText(_translate("frmNaturschutz", "Geschützter Landschaftsteil"))
        self.ckBiosphaerenpark.setText(_translate("frmNaturschutz", "Biosphärenparks"))
        self.ckRuhezone.setText(_translate("frmNaturschutz", "Ruhezone"))
        self.ckOertlichesSchutzgebiet.setText(_translate("frmNaturschutz", "Örtliches Schutzgebiet"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.gebietsschutz), _translate("frmNaturschutz", "Gebietsschutz"))
        self.ckBiotopinventar.setText(_translate("frmNaturschutz", "Biotopinventar 2009"))
        self.groupBox.setTitle(_translate("frmNaturschutz", "Infos (als PDF)"))
        self.btnGemeindebericht.setText(_translate("frmNaturschutz", "Gemeindebericht"))
        self.btnA3Plaene.setText(_translate("frmNaturschutz", "A3 Pläne"))
        self.btGmdChoice.setText(_translate("frmNaturschutz", "+"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.inventar), _translate("frmNaturschutz", "Inventar"))
        self.ckStreuwiesen_2000.setText(_translate("frmNaturschutz", "Evaluierung Streuwiesen (2000)"))
        self.ckNaturdenkmale.setText(_translate("frmNaturschutz", "Naturdenkmale"))
        self.ckStreuwiesen_2014.setText(_translate("frmNaturschutz", "Evaluierung Streuwiesen (2014)"))
        self.ckAmphibienzugstellen.setText(_translate("frmNaturschutz", "Amphibienzugstellen"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("frmNaturschutz", "Projekte"))
        self.btnLaden.setText(_translate("frmNaturschutz", "Themen laden"))
        self.btnAbbrechen.setText(_translate("frmNaturschutz", "Schließen"))

