# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_gstsuche.ui'
#
# Created: Fri Feb 06 09:14:50 2015
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmGstsuche(object):
    def setupUi(self, frmGstsuche):
        frmGstsuche.setObjectName(_fromUtf8("frmGstsuche"))
        frmGstsuche.resize(421, 835)
        frmGstsuche.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox = QtGui.QGroupBox(frmGstsuche)
        self.groupBox.setGeometry(QtCore.QRect(30, 740, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.btUrmappe = QtGui.QPushButton(self.groupBox)
        self.btUrmappe.setGeometry(QtCore.QRect(40, 30, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btUrmappe.setFont(font)
        self.btUrmappe.setObjectName(_fromUtf8("btUrmappe"))
        self.groupBox_2 = QtGui.QGroupBox(frmGstsuche)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 650, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.btObjektdaten = QtGui.QPushButton(self.groupBox_2)
        self.btObjektdaten.setGeometry(QtCore.QRect(40, 30, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btObjektdaten.setFont(font)
        self.btObjektdaten.setObjectName(_fromUtf8("btObjektdaten"))
        self.gbDkm = QtGui.QGroupBox(frmGstsuche)
        self.gbDkm.setGeometry(QtCore.QRect(30, 10, 361, 631))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbDkm.setFont(font)
        self.gbDkm.setObjectName(_fromUtf8("gbDkm"))
        self.groupBox_3 = QtGui.QGroupBox(self.gbDkm)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 30, 321, 201))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.btGmdChoice = QtGui.QPushButton(self.groupBox_3)
        self.btGmdChoice.setGeometry(QtCore.QRect(150, 130, 31, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btGmdChoice.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btGmdChoice.setFont(font)
        self.btGmdChoice.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btGmdChoice.setCheckable(True)
        self.btGmdChoice.setChecked(False)
        self.btGmdChoice.setObjectName(_fromUtf8("btGmdChoice"))
        self.lstPolgem = QtGui.QListView(self.groupBox_3)
        self.lstPolgem.setGeometry(QtCore.QRect(10, 20, 131, 131))
        self.lstPolgem.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Austria))
        self.lstPolgem.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.lstPolgem.setTabKeyNavigation(False)
        self.lstPolgem.setObjectName(_fromUtf8("lstPolgem"))
        self.lstKatgem = QtGui.QListView(self.groupBox_3)
        self.lstKatgem.setGeometry(QtCore.QRect(150, 20, 161, 101))
        self.lstKatgem.setTabKeyNavigation(False)
        self.lstKatgem.setObjectName(_fromUtf8("lstKatgem"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 130, 78, 42))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.rbKG = QtGui.QRadioButton(self.layoutWidget)
        self.rbKG.setObjectName(_fromUtf8("rbKG"))
        self.verticalLayout_3.addWidget(self.rbKG)
        self.rbName = QtGui.QRadioButton(self.layoutWidget)
        self.rbName.setChecked(True)
        self.rbName.setObjectName(_fromUtf8("rbName"))
        self.verticalLayout_3.addWidget(self.rbName)
        self.btnVorarlberg = QtGui.QPushButton(self.groupBox_3)
        self.btnVorarlberg.setGeometry(QtCore.QRect(24, 160, 111, 23))
        self.btnVorarlberg.setObjectName(_fromUtf8("btnVorarlberg"))
        self.groupBox_4 = QtGui.QGroupBox(self.gbDkm)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 240, 321, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.txtGstnr = QtGui.QLineEdit(self.groupBox_4)
        self.txtGstnr.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.txtGstnr.setObjectName(_fromUtf8("txtGstnr"))
        self.btnGstsuche = QtGui.QPushButton(self.groupBox_4)
        self.btnGstsuche.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.btnGstsuche.setObjectName(_fromUtf8("btnGstsuche"))
        self.gefunden = QtGui.QLineEdit(self.groupBox_4)
        self.gefunden.setGeometry(QtCore.QRect(10, 60, 291, 21))
        self.gefunden.setFrame(False)
        self.gefunden.setReadOnly(True)
        self.gefunden.setObjectName(_fromUtf8("gefunden"))
        self.groupBox_5 = QtGui.QGroupBox(self.gbDkm)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 340, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.btnAlles = QtGui.QPushButton(self.groupBox_5)
        self.btnAlles.setGeometry(QtCore.QRect(30, 20, 121, 23))
        self.btnAlles.setObjectName(_fromUtf8("btnAlles"))
        self.btnStandard = QtGui.QPushButton(self.groupBox_5)
        self.btnStandard.setGeometry(QtCore.QRect(170, 20, 121, 23))
        self.btnStandard.setObjectName(_fromUtf8("btnStandard"))
        self.groupBox_6 = QtGui.QGroupBox(self.gbDkm)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 390, 321, 181))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 10, 139, 157))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBox_2 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.auswahlBoxen = QtGui.QButtonGroup(frmGstsuche)
        self.auswahlBoxen.setObjectName(_fromUtf8("auswahlBoxen"))
        self.auswahlBoxen.addButton(self.checkBox_2)
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_4 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.auswahlBoxen.addButton(self.checkBox_4)
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_9 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.auswahlBoxen.addButton(self.checkBox_9)
        self.verticalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_10 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.auswahlBoxen.addButton(self.checkBox_10)
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_13 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.auswahlBoxen.addButton(self.checkBox_13)
        self.verticalLayout_2.addWidget(self.checkBox_13)
        self.checkBox_11 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.auswahlBoxen.addButton(self.checkBox_11)
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_14 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.auswahlBoxen.addButton(self.checkBox_14)
        self.verticalLayout_2.addWidget(self.checkBox_14)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 113, 157))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBox = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.auswahlBoxen.addButton(self.checkBox)
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_3 = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.auswahlBoxen.addButton(self.checkBox_3)
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_6 = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.auswahlBoxen.addButton(self.checkBox_6)
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_5 = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.auswahlBoxen.addButton(self.checkBox_5)
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_12 = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.auswahlBoxen.addButton(self.checkBox_12)
        self.verticalLayout.addWidget(self.checkBox_12)
        self.checkBox_8 = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.auswahlBoxen.addButton(self.checkBox_8)
        self.verticalLayout.addWidget(self.checkBox_8)
        self.checkBox_7 = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.auswahlBoxen.addButton(self.checkBox_7)
        self.verticalLayout.addWidget(self.checkBox_7)
        self.btAbbrechen = QtGui.QPushButton(self.gbDkm)
        self.btAbbrechen.setGeometry(QtCore.QRect(220, 580, 91, 31))
        self.btAbbrechen.setObjectName(_fromUtf8("btAbbrechen"))
        self.pushButton = QtGui.QPushButton(self.gbDkm)
        self.pushButton.setGeometry(QtCore.QRect(60, 580, 91, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))

        self.retranslateUi(frmGstsuche)
        QtCore.QObject.connect(self.btGmdChoice, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGstsuche.gmd_choice_toggled)
        QtCore.QObject.connect(self.lstPolgem, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), frmGstsuche.auswahlaenderung)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGstsuche.ladeGemeinde)
        QtCore.QObject.connect(self.btnGstsuche, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGstsuche.gstsuche)
        QtCore.QObject.connect(self.lstKatgem, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), frmGstsuche.gstsuche_aktivieren)
        QtCore.QObject.connect(self.btnAlles, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGstsuche.alles_auswaehlen)
        QtCore.QObject.connect(self.btnStandard, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGstsuche.standard_auswaehlen)
        QtCore.QObject.connect(self.btAbbrechen, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGstsuche.closeEvent)
        QtCore.QObject.connect(self.btUrmappe, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGstsuche.ladeurmappe)
        QtCore.QObject.connect(self.btObjektdaten, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGstsuche.ladeobjekte)
        QtCore.QObject.connect(self.rbName, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGstsuche.sort)
        QtCore.QObject.connect(self.rbKG, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGstsuche.sort)
        QtCore.QObject.connect(self.btnVorarlberg, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGstsuche.landesflaeche)
        QtCore.QMetaObject.connectSlotsByName(frmGstsuche)
        frmGstsuche.setTabOrder(self.lstPolgem, self.lstKatgem)
        frmGstsuche.setTabOrder(self.lstKatgem, self.btGmdChoice)
        frmGstsuche.setTabOrder(self.btGmdChoice, self.btAbbrechen)
        frmGstsuche.setTabOrder(self.btAbbrechen, self.btUrmappe)
        frmGstsuche.setTabOrder(self.btUrmappe, self.btObjektdaten)
        frmGstsuche.setTabOrder(self.btObjektdaten, self.pushButton)
        frmGstsuche.setTabOrder(self.pushButton, self.txtGstnr)
        frmGstsuche.setTabOrder(self.txtGstnr, self.btnGstsuche)
        frmGstsuche.setTabOrder(self.btnGstsuche, self.gefunden)
        frmGstsuche.setTabOrder(self.gefunden, self.btnAlles)
        frmGstsuche.setTabOrder(self.btnAlles, self.btnStandard)
        frmGstsuche.setTabOrder(self.btnStandard, self.checkBox_2)
        frmGstsuche.setTabOrder(self.checkBox_2, self.checkBox_4)
        frmGstsuche.setTabOrder(self.checkBox_4, self.checkBox_9)
        frmGstsuche.setTabOrder(self.checkBox_9, self.checkBox_10)
        frmGstsuche.setTabOrder(self.checkBox_10, self.checkBox_13)
        frmGstsuche.setTabOrder(self.checkBox_13, self.checkBox_11)
        frmGstsuche.setTabOrder(self.checkBox_11, self.checkBox)
        frmGstsuche.setTabOrder(self.checkBox, self.checkBox_3)
        frmGstsuche.setTabOrder(self.checkBox_3, self.checkBox_6)
        frmGstsuche.setTabOrder(self.checkBox_6, self.checkBox_5)
        frmGstsuche.setTabOrder(self.checkBox_5, self.checkBox_12)
        frmGstsuche.setTabOrder(self.checkBox_12, self.checkBox_8)
        frmGstsuche.setTabOrder(self.checkBox_8, self.checkBox_7)

    def retranslateUi(self, frmGstsuche):
        frmGstsuche.setWindowTitle(QtGui.QApplication.translate("frmGstsuche", "DKM,Objektdaten, Urmappe", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmGstsuche", "Historischer Kataster", None, QtGui.QApplication.UnicodeUTF8))
        self.btUrmappe.setText(QtGui.QApplication.translate("frmGstsuche", "Urmappe 1857", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmGstsuche", "Objektdaten Gemeinden/VKW/VEG", None, QtGui.QApplication.UnicodeUTF8))
        self.btObjektdaten.setText(QtGui.QApplication.translate("frmGstsuche", "Gebäudehaupt- und Nebenkonturen", None, QtGui.QApplication.UnicodeUTF8))
        self.gbDkm.setTitle(QtGui.QApplication.translate("frmGstsuche", "Digitale Katastralmappe (DKM)     Stand: dd.mm.yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("frmGstsuche", "Auswahl Gemeinde / Landesfläche Vlbg.", None, QtGui.QApplication.UnicodeUTF8))
        self.btGmdChoice.setText(QtGui.QApplication.translate("frmGstsuche", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.rbKG.setText(QtGui.QApplication.translate("frmGstsuche", "nach KGNR", None, QtGui.QApplication.UnicodeUTF8))
        self.rbName.setText(QtGui.QApplication.translate("frmGstsuche", "nach Name", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVorarlberg.setText(QtGui.QApplication.translate("frmGstsuche", "Landesfläche Vlbg.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("frmGstsuche", "Grundstückssuche in", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGstsuche.setText(QtGui.QApplication.translate("frmGstsuche", "Suchen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("frmGstsuche", "DKM Ebenen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAlles.setText(QtGui.QApplication.translate("frmGstsuche", "Alle auswählen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStandard.setText(QtGui.QApplication.translate("frmGstsuche", "Standardauswahl", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("frmGstsuche", "Grundstück Nr", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("frmGstsuche", "Nutzungsflächen Umriss", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("frmGstsuche", "Sonstige Grenzen", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("frmGstsuche", "Sonstige Symbole", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setText(QtGui.QApplication.translate("frmGstsuche", "Grenzpunkt Symbole", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("frmGstsuche", "Sonstige Texte", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_14.setText(QtGui.QApplication.translate("frmGstsuche", "Festpunkt Symbole", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("frmGstsuche", "Grundstücke", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("frmGstsuche", "Nutzungsflächen", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("frmGstsuche", "Gebäudeflächen", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("frmGstsuche", "Nutzungs Symbole", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("frmGstsuche", "Grenzpunkt Nr", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("frmGstsuche", "Grenzpunkt Infos", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("frmGstsuche", "Festpunkte", None, QtGui.QApplication.UnicodeUTF8))
        self.btAbbrechen.setText(QtGui.QApplication.translate("frmGstsuche", "Schließen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("frmGstsuche", "DKM laden", None, QtGui.QApplication.UnicodeUTF8))

