# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_geologie.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmGeologie(object):
    def setupUi(self, frmGeologie):
        frmGeologie.setObjectName("frmGeologie")
        frmGeologie.resize(813, 638)
        self.ButtonGeolgoieOk = QtWidgets.QPushButton(frmGeologie)
        self.ButtonGeolgoieOk.setGeometry(QtCore.QRect(236, 588, 121, 23))
        self.ButtonGeolgoieOk.setObjectName("ButtonGeolgoieOk")
        self.ButtonGeologieCancel = QtWidgets.QPushButton(frmGeologie)
        self.ButtonGeologieCancel.setGeometry(QtCore.QRect(436, 588, 121, 23))
        self.ButtonGeologieCancel.setObjectName("ButtonGeologieCancel")
        self.tabWidget = QtWidgets.QTabWidget(frmGeologie)
        self.tabWidget.setGeometry(QtCore.QRect(32, 24, 757, 537))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(176, 40, 345, 449))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(12, 30, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkButtonsGroup = QtWidgets.QButtonGroup(frmGeologie)
        self.checkButtonsGroup.setObjectName("checkButtonsGroup")
        self.checkButtonsGroup.addButton(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(12, 60, 272, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkButtonsGroup.addButton(self.checkBox_2)
        self.Button_Legend_Geologie_2007 = QtWidgets.QPushButton(self.groupBox)
        self.Button_Legend_Geologie_2007.setEnabled(True)
        self.Button_Legend_Geologie_2007.setGeometry(QtCore.QRect(280, 30, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Legend_Geologie_2007.sizePolicy().hasHeightForWidth())
        self.Button_Legend_Geologie_2007.setSizePolicy(sizePolicy)
        self.Button_Legend_Geologie_2007.setBaseSize(QtCore.QSize(23, 23))
        self.Button_Legend_Geologie_2007.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/VogisMenu/icons/gui-rv.info.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Legend_Geologie_2007.setIcon(icon)
        self.Button_Legend_Geologie_2007.setObjectName("Button_Legend_Geologie_2007")
        self.Button_Legend_Tektonisch_1998 = QtWidgets.QPushButton(self.groupBox)
        self.Button_Legend_Tektonisch_1998.setEnabled(True)
        self.Button_Legend_Tektonisch_1998.setGeometry(QtCore.QRect(280, 60, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Legend_Tektonisch_1998.sizePolicy().hasHeightForWidth())
        self.Button_Legend_Tektonisch_1998.setSizePolicy(sizePolicy)
        self.Button_Legend_Tektonisch_1998.setBaseSize(QtCore.QSize(23, 23))
        self.Button_Legend_Tektonisch_1998.setText("")
        self.Button_Legend_Tektonisch_1998.setIcon(icon)
        self.Button_Legend_Tektonisch_1998.setObjectName("Button_Legend_Tektonisch_1998")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(31, 90, 130, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Profilschintt_Vorarlberg = QtWidgets.QPushButton(self.groupBox)
        self.Profilschintt_Vorarlberg.setEnabled(True)
        self.Profilschintt_Vorarlberg.setGeometry(QtCore.QRect(280, 92, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profilschintt_Vorarlberg.sizePolicy().hasHeightForWidth())
        self.Profilschintt_Vorarlberg.setSizePolicy(sizePolicy)
        self.Profilschintt_Vorarlberg.setBaseSize(QtCore.QSize(23, 23))
        self.Profilschintt_Vorarlberg.setText("")
        self.Profilschintt_Vorarlberg.setIcon(icon)
        self.Profilschintt_Vorarlberg.setObjectName("Profilschintt_Vorarlberg")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(12, 128, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkButtonsGroup.addButton(self.checkBox_3)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(12, 176, 219, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkButtonsGroup.addButton(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(12, 200, 180, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkButtonsGroup.addButton(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(12, 224, 209, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkButtonsGroup.addButton(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setEnabled(True)
        self.checkBox_8.setGeometry(QtCore.QRect(11, 296, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkButtonsGroup.addButton(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_9.setGeometry(QtCore.QRect(11, 320, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkButtonsGroup.addButton(self.checkBox_9)
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_23.setGeometry(QtCore.QRect(11, 356, 116, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_23.setFont(font)
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkButtonsGroup.addButton(self.checkBox_23)
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_25.setGeometry(QtCore.QRect(11, 392, 270, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_25.setFont(font)
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkButtonsGroup.addButton(self.checkBox_25)
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_24.setEnabled(True)
        self.checkBox_24.setGeometry(QtCore.QRect(11, 416, 309, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_24.setFont(font)
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkButtonsGroup.addButton(self.checkBox_24)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_11.setGeometry(QtCore.QRect(12, 248, 269, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkButtonsGroup.addButton(self.checkBox_11)
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_19.setGeometry(QtCore.QRect(12, 152, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_19.setFont(font)
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkButtonsGroup.addButton(self.checkBox_19)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(164, 28, 429, 461))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 30, 397, 417))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkButtonsGroup2 = QtWidgets.QButtonGroup(frmGeologie)
        self.checkButtonsGroup2.setObjectName("checkButtonsGroup2")
        self.checkButtonsGroup2.addButton(self.checkBox_4)
        self.gridLayout.addWidget(self.checkBox_4, 0, 0, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkButtonsGroup2.addButton(self.checkBox_10)
        self.gridLayout.addWidget(self.checkBox_10, 1, 0, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkButtonsGroup2.addButton(self.checkBox_12)
        self.gridLayout.addWidget(self.checkBox_12, 2, 0, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkButtonsGroup2.addButton(self.checkBox_13)
        self.gridLayout.addWidget(self.checkBox_13, 3, 0, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkButtonsGroup2.addButton(self.checkBox_14)
        self.gridLayout.addWidget(self.checkBox_14, 4, 0, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkButtonsGroup2.addButton(self.checkBox_15)
        self.gridLayout.addWidget(self.checkBox_15, 5, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_16.setFont(font)
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkButtonsGroup2.addButton(self.checkBox_16)
        self.gridLayout.addWidget(self.checkBox_16, 6, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_17.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_17.setFont(font)
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkButtonsGroup2.addButton(self.checkBox_17)
        self.gridLayout.addWidget(self.checkBox_17, 7, 0, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_18.setFont(font)
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkButtonsGroup2.addButton(self.checkBox_18)
        self.gridLayout.addWidget(self.checkBox_18, 8, 0, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_26.setFont(font)
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkButtonsGroup2.addButton(self.checkBox_26)
        self.gridLayout.addWidget(self.checkBox_26, 9, 0, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_27.setFont(font)
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkButtonsGroup2.addButton(self.checkBox_27)
        self.gridLayout.addWidget(self.checkBox_27, 10, 0, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_28.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_28.setFont(font)
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkButtonsGroup2.addButton(self.checkBox_28)
        self.gridLayout.addWidget(self.checkBox_28, 11, 0, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_29.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_29.setFont(font)
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkButtonsGroup2.addButton(self.checkBox_29)
        self.gridLayout.addWidget(self.checkBox_29, 12, 0, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_30.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_30.setFont(font)
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkButtonsGroup2.addButton(self.checkBox_30)
        self.gridLayout.addWidget(self.checkBox_30, 13, 0, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_33.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_33.setFont(font)
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkButtonsGroup2.addButton(self.checkBox_33)
        self.gridLayout.addWidget(self.checkBox_33, 14, 0, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_37.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_37.setFont(font)
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkButtonsGroup2.addButton(self.checkBox_37)
        self.gridLayout.addWidget(self.checkBox_37, 5, 1, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_38.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_38.setFont(font)
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkButtonsGroup2.addButton(self.checkBox_38)
        self.gridLayout.addWidget(self.checkBox_38, 6, 1, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_36.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_36.setFont(font)
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkButtonsGroup2.addButton(self.checkBox_36)
        self.gridLayout.addWidget(self.checkBox_36, 4, 1, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_35.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_35.setFont(font)
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkButtonsGroup2.addButton(self.checkBox_35)
        self.gridLayout.addWidget(self.checkBox_35, 3, 1, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_31.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_31.setFont(font)
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkButtonsGroup2.addButton(self.checkBox_31)
        self.gridLayout.addWidget(self.checkBox_31, 2, 1, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_34.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_34.setFont(font)
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkButtonsGroup2.addButton(self.checkBox_34)
        self.gridLayout.addWidget(self.checkBox_34, 1, 1, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_32.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_32.setFont(font)
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkButtonsGroup2.addButton(self.checkBox_32)
        self.gridLayout.addWidget(self.checkBox_32, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(180, 36, 345, 397))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_20.setGeometry(QtCore.QRect(13, 40, 272, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_20.setFont(font)
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkButtonsGroup3 = QtWidgets.QButtonGroup(frmGeologie)
        self.checkButtonsGroup3.setObjectName("checkButtonsGroup3")
        self.checkButtonsGroup3.addButton(self.checkBox_20)
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_21.setGeometry(QtCore.QRect(13, 64, 165, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_21.setFont(font)
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkButtonsGroup3.addButton(self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_22.setGeometry(QtCore.QRect(13, 88, 219, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_22.setFont(font)
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkButtonsGroup3.addButton(self.checkBox_22)
        self.checkBox_39 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_39.setGeometry(QtCore.QRect(13, 112, 180, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_39.setFont(font)
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkButtonsGroup3.addButton(self.checkBox_39)
        self.checkBox_40 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_40.setGeometry(QtCore.QRect(13, 136, 209, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_40.setFont(font)
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkButtonsGroup3.addButton(self.checkBox_40)
        self.checkBox_41 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_41.setGeometry(QtCore.QRect(13, 160, 279, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_41.setFont(font)
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkButtonsGroup3.addButton(self.checkBox_41)
        self.checkBox_42 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_42.setEnabled(True)
        self.checkBox_42.setGeometry(QtCore.QRect(12, 184, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_42.setFont(font)
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkButtonsGroup3.addButton(self.checkBox_42)
        self.checkBox_43 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_43.setGeometry(QtCore.QRect(12, 208, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_43.setFont(font)
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkButtonsGroup3.addButton(self.checkBox_43)
        self.checkBox_44 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_44.setGeometry(QtCore.QRect(12, 232, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_44.setFont(font)
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkButtonsGroup3.addButton(self.checkBox_44)
        self.checkBox_45 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_45.setGeometry(QtCore.QRect(12, 256, 270, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_45.setFont(font)
        self.checkBox_45.setObjectName("checkBox_45")
        self.checkButtonsGroup3.addButton(self.checkBox_45)
        self.checkBox_46 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_46.setEnabled(True)
        self.checkBox_46.setGeometry(QtCore.QRect(12, 280, 309, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_46.setFont(font)
        self.checkBox_46.setObjectName("checkBox_46")
        self.checkButtonsGroup3.addButton(self.checkBox_46)
        self.checkBox_47 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_47.setEnabled(True)
        self.checkBox_47.setGeometry(QtCore.QRect(12, 304, 309, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_47.setFont(font)
        self.checkBox_47.setObjectName("checkBox_47")
        self.checkButtonsGroup3.addButton(self.checkBox_47)
        self.checkBox_48 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_48.setEnabled(True)
        self.checkBox_48.setGeometry(QtCore.QRect(12, 328, 309, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_48.setFont(font)
        self.checkBox_48.setObjectName("checkBox_48")
        self.checkButtonsGroup3.addButton(self.checkBox_48)
        self.checkBox_49 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_49.setEnabled(True)
        self.checkBox_49.setGeometry(QtCore.QRect(12, 352, 309, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_49.setFont(font)
        self.checkBox_49.setObjectName("checkBox_49")
        self.checkButtonsGroup3.addButton(self.checkBox_49)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(12, 28, 169, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(208, 168, 213, 169))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.checkBox_55 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_55.setGeometry(QtCore.QRect(13, 24, 257, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_55.setFont(font)
        self.checkBox_55.setObjectName("checkBox_55")
        self.checkBox_56 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_56.setGeometry(QtCore.QRect(13, 48, 165, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_56.setFont(font)
        self.checkBox_56.setObjectName("checkBox_56")
        self.checkBox_57 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_57.setGeometry(QtCore.QRect(13, 72, 219, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_57.setFont(font)
        self.checkBox_57.setObjectName("checkBox_57")
        self.checkBox_58 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_58.setGeometry(QtCore.QRect(13, 96, 180, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_58.setFont(font)
        self.checkBox_58.setObjectName("checkBox_58")
        self.checkBox_59 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_59.setGeometry(QtCore.QRect(13, 120, 209, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_59.setFont(font)
        self.checkBox_59.setObjectName("checkBox_59")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(13, 24, 133, 116))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_50 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_50.setFont(font)
        self.checkBox_50.setObjectName("checkBox_50")
        self.checkButtonsGroup4 = QtWidgets.QButtonGroup(frmGeologie)
        self.checkButtonsGroup4.setObjectName("checkButtonsGroup4")
        self.checkButtonsGroup4.addButton(self.checkBox_50)
        self.verticalLayout_3.addWidget(self.checkBox_50)
        self.checkBox_51 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_51.setFont(font)
        self.checkBox_51.setObjectName("checkBox_51")
        self.checkButtonsGroup4.addButton(self.checkBox_51)
        self.verticalLayout_3.addWidget(self.checkBox_51)
        self.checkBox_52 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_52.setFont(font)
        self.checkBox_52.setObjectName("checkBox_52")
        self.checkButtonsGroup4.addButton(self.checkBox_52)
        self.verticalLayout_3.addWidget(self.checkBox_52)
        self.checkBox_53 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_53.setFont(font)
        self.checkBox_53.setObjectName("checkBox_53")
        self.checkButtonsGroup4.addButton(self.checkBox_53)
        self.verticalLayout_3.addWidget(self.checkBox_53)
        self.checkBox_54 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_54.setFont(font)
        self.checkBox_54.setObjectName("checkBox_54")
        self.checkButtonsGroup4.addButton(self.checkBox_54)
        self.verticalLayout_3.addWidget(self.checkBox_54)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(364, 28, 137, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(208, 168, 213, 169))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.checkBox_65 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_65.setGeometry(QtCore.QRect(13, 24, 257, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_65.setFont(font)
        self.checkBox_65.setObjectName("checkBox_65")
        self.checkBox_66 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_66.setGeometry(QtCore.QRect(13, 48, 165, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_66.setFont(font)
        self.checkBox_66.setObjectName("checkBox_66")
        self.checkBox_67 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_67.setGeometry(QtCore.QRect(13, 72, 219, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_67.setFont(font)
        self.checkBox_67.setObjectName("checkBox_67")
        self.checkBox_68 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_68.setGeometry(QtCore.QRect(13, 96, 180, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_68.setFont(font)
        self.checkBox_68.setObjectName("checkBox_68")
        self.checkBox_69 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_69.setGeometry(QtCore.QRect(13, 120, 209, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_69.setFont(font)
        self.checkBox_69.setObjectName("checkBox_69")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget2.setGeometry(QtCore.QRect(13, 24, 99, 116))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_60 = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_60.setFont(font)
        self.checkBox_60.setObjectName("checkBox_60")
        self.checkButtonsGroup4.addButton(self.checkBox_60)
        self.verticalLayout_4.addWidget(self.checkBox_60)
        self.checkBox_61 = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_61.setFont(font)
        self.checkBox_61.setObjectName("checkBox_61")
        self.checkButtonsGroup4.addButton(self.checkBox_61)
        self.verticalLayout_4.addWidget(self.checkBox_61)
        self.checkBox_62 = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_62.setFont(font)
        self.checkBox_62.setObjectName("checkBox_62")
        self.checkButtonsGroup4.addButton(self.checkBox_62)
        self.verticalLayout_4.addWidget(self.checkBox_62)
        self.checkBox_63 = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_63.setFont(font)
        self.checkBox_63.setObjectName("checkBox_63")
        self.checkButtonsGroup4.addButton(self.checkBox_63)
        self.verticalLayout_4.addWidget(self.checkBox_63)
        self.checkBox_64 = QtWidgets.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_64.setFont(font)
        self.checkBox_64.setObjectName("checkBox_64")
        self.checkButtonsGroup4.addButton(self.checkBox_64)
        self.verticalLayout_4.addWidget(self.checkBox_64)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(192, 28, 153, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(208, 168, 213, 169))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.checkBox_75 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_75.setGeometry(QtCore.QRect(13, 24, 257, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_75.setFont(font)
        self.checkBox_75.setObjectName("checkBox_75")
        self.checkBox_76 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_76.setGeometry(QtCore.QRect(13, 48, 165, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_76.setFont(font)
        self.checkBox_76.setObjectName("checkBox_76")
        self.checkBox_77 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_77.setGeometry(QtCore.QRect(13, 72, 219, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_77.setFont(font)
        self.checkBox_77.setObjectName("checkBox_77")
        self.checkBox_78 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_78.setGeometry(QtCore.QRect(13, 96, 180, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_78.setFont(font)
        self.checkBox_78.setObjectName("checkBox_78")
        self.checkBox_79 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_79.setGeometry(QtCore.QRect(13, 120, 209, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_79.setFont(font)
        self.checkBox_79.setObjectName("checkBox_79")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget3.setGeometry(QtCore.QRect(13, 24, 94, 116))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_70 = QtWidgets.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_70.setFont(font)
        self.checkBox_70.setObjectName("checkBox_70")
        self.checkButtonsGroup4.addButton(self.checkBox_70)
        self.verticalLayout_5.addWidget(self.checkBox_70)
        self.checkBox_71 = QtWidgets.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_71.setFont(font)
        self.checkBox_71.setObjectName("checkBox_71")
        self.checkButtonsGroup4.addButton(self.checkBox_71)
        self.verticalLayout_5.addWidget(self.checkBox_71)
        self.checkBox_72 = QtWidgets.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_72.setFont(font)
        self.checkBox_72.setObjectName("checkBox_72")
        self.checkButtonsGroup4.addButton(self.checkBox_72)
        self.verticalLayout_5.addWidget(self.checkBox_72)
        self.checkBox_73 = QtWidgets.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_73.setFont(font)
        self.checkBox_73.setObjectName("checkBox_73")
        self.checkButtonsGroup4.addButton(self.checkBox_73)
        self.verticalLayout_5.addWidget(self.checkBox_73)
        self.checkBox_74 = QtWidgets.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_74.setFont(font)
        self.checkBox_74.setObjectName("checkBox_74")
        self.checkButtonsGroup4.addButton(self.checkBox_74)
        self.verticalLayout_5.addWidget(self.checkBox_74)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_10.setGeometry(QtCore.QRect(528, 28, 177, 345))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget4.setGeometry(QtCore.QRect(13, 24, 126, 308))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_80 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_80.setFont(font)
        self.checkBox_80.setObjectName("checkBox_80")
        self.checkButtonsGroup4.addButton(self.checkBox_80)
        self.verticalLayout_2.addWidget(self.checkBox_80)
        self.checkBox_81 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_81.setFont(font)
        self.checkBox_81.setObjectName("checkBox_81")
        self.checkButtonsGroup4.addButton(self.checkBox_81)
        self.verticalLayout_2.addWidget(self.checkBox_81)
        self.checkBox_82 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_82.setFont(font)
        self.checkBox_82.setObjectName("checkBox_82")
        self.checkButtonsGroup4.addButton(self.checkBox_82)
        self.verticalLayout_2.addWidget(self.checkBox_82)
        self.checkBox_83 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_83.setFont(font)
        self.checkBox_83.setObjectName("checkBox_83")
        self.checkButtonsGroup4.addButton(self.checkBox_83)
        self.verticalLayout_2.addWidget(self.checkBox_83)
        self.checkBox_84 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_84.setFont(font)
        self.checkBox_84.setObjectName("checkBox_84")
        self.checkButtonsGroup4.addButton(self.checkBox_84)
        self.verticalLayout_2.addWidget(self.checkBox_84)
        self.checkBox_85 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_85.setFont(font)
        self.checkBox_85.setObjectName("checkBox_85")
        self.checkButtonsGroup4.addButton(self.checkBox_85)
        self.verticalLayout_2.addWidget(self.checkBox_85)
        self.checkBox_86 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_86.setFont(font)
        self.checkBox_86.setObjectName("checkBox_86")
        self.checkButtonsGroup4.addButton(self.checkBox_86)
        self.verticalLayout_2.addWidget(self.checkBox_86)
        self.checkBox_87 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_87.setFont(font)
        self.checkBox_87.setObjectName("checkBox_87")
        self.checkButtonsGroup4.addButton(self.checkBox_87)
        self.verticalLayout_2.addWidget(self.checkBox_87)
        self.checkBox_88 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_88.setFont(font)
        self.checkBox_88.setObjectName("checkBox_88")
        self.checkButtonsGroup4.addButton(self.checkBox_88)
        self.verticalLayout_2.addWidget(self.checkBox_88)
        self.checkBox_89 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_89.setFont(font)
        self.checkBox_89.setObjectName("checkBox_89")
        self.checkButtonsGroup4.addButton(self.checkBox_89)
        self.verticalLayout_2.addWidget(self.checkBox_89)
        self.checkBox_90 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_90.setFont(font)
        self.checkBox_90.setObjectName("checkBox_90")
        self.checkButtonsGroup4.addButton(self.checkBox_90)
        self.verticalLayout_2.addWidget(self.checkBox_90)
        self.checkBox_91 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_91.setFont(font)
        self.checkBox_91.setObjectName("checkBox_91")
        self.checkButtonsGroup4.addButton(self.checkBox_91)
        self.verticalLayout_2.addWidget(self.checkBox_91)
        self.checkBox_92 = QtWidgets.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_92.setFont(font)
        self.checkBox_92.setObjectName("checkBox_92")
        self.checkButtonsGroup4.addButton(self.checkBox_92)
        self.verticalLayout_2.addWidget(self.checkBox_92)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_11.setGeometry(QtCore.QRect(72, 20, 549, 473))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_11)
        self.layoutWidget5.setGeometry(QtCore.QRect(356, 28, 164, 428))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_122 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_122.setFont(font)
        self.checkBox_122.setObjectName("checkBox_122")
        self.checkButtonsGroup5 = QtWidgets.QButtonGroup(frmGeologie)
        self.checkButtonsGroup5.setObjectName("checkButtonsGroup5")
        self.checkButtonsGroup5.addButton(self.checkBox_122)
        self.verticalLayout_6.addWidget(self.checkBox_122)
        self.checkBox_123 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_123.setFont(font)
        self.checkBox_123.setObjectName("checkBox_123")
        self.checkButtonsGroup5.addButton(self.checkBox_123)
        self.verticalLayout_6.addWidget(self.checkBox_123)
        self.checkBox_124 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_124.setFont(font)
        self.checkBox_124.setObjectName("checkBox_124")
        self.checkButtonsGroup5.addButton(self.checkBox_124)
        self.verticalLayout_6.addWidget(self.checkBox_124)
        self.checkBox_125 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_125.setFont(font)
        self.checkBox_125.setObjectName("checkBox_125")
        self.checkButtonsGroup5.addButton(self.checkBox_125)
        self.verticalLayout_6.addWidget(self.checkBox_125)
        self.checkBox_126 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_126.setFont(font)
        self.checkBox_126.setObjectName("checkBox_126")
        self.checkButtonsGroup5.addButton(self.checkBox_126)
        self.verticalLayout_6.addWidget(self.checkBox_126)
        self.checkBox_127 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_127.setFont(font)
        self.checkBox_127.setObjectName("checkBox_127")
        self.checkButtonsGroup5.addButton(self.checkBox_127)
        self.verticalLayout_6.addWidget(self.checkBox_127)
        self.checkBox_128 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_128.setFont(font)
        self.checkBox_128.setObjectName("checkBox_128")
        self.checkButtonsGroup5.addButton(self.checkBox_128)
        self.verticalLayout_6.addWidget(self.checkBox_128)
        self.checkBox_129 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_129.setFont(font)
        self.checkBox_129.setObjectName("checkBox_129")
        self.checkButtonsGroup5.addButton(self.checkBox_129)
        self.verticalLayout_6.addWidget(self.checkBox_129)
        self.checkBox_130 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_130.setFont(font)
        self.checkBox_130.setObjectName("checkBox_130")
        self.checkButtonsGroup5.addButton(self.checkBox_130)
        self.verticalLayout_6.addWidget(self.checkBox_130)
        self.checkBox_131 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_131.setFont(font)
        self.checkBox_131.setObjectName("checkBox_131")
        self.checkButtonsGroup5.addButton(self.checkBox_131)
        self.verticalLayout_6.addWidget(self.checkBox_131)
        self.checkBox_132 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_132.setFont(font)
        self.checkBox_132.setObjectName("checkBox_132")
        self.checkButtonsGroup5.addButton(self.checkBox_132)
        self.verticalLayout_6.addWidget(self.checkBox_132)
        self.checkBox_133 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_133.setFont(font)
        self.checkBox_133.setObjectName("checkBox_133")
        self.checkButtonsGroup5.addButton(self.checkBox_133)
        self.verticalLayout_6.addWidget(self.checkBox_133)
        self.checkBox_134 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_134.setFont(font)
        self.checkBox_134.setObjectName("checkBox_134")
        self.checkButtonsGroup5.addButton(self.checkBox_134)
        self.verticalLayout_6.addWidget(self.checkBox_134)
        self.checkBox_135 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_135.setFont(font)
        self.checkBox_135.setObjectName("checkBox_135")
        self.checkButtonsGroup5.addButton(self.checkBox_135)
        self.verticalLayout_6.addWidget(self.checkBox_135)
        self.checkBox_136 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_136.setFont(font)
        self.checkBox_136.setObjectName("checkBox_136")
        self.checkButtonsGroup5.addButton(self.checkBox_136)
        self.verticalLayout_6.addWidget(self.checkBox_136)
        self.checkBox_137 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_137.setFont(font)
        self.checkBox_137.setObjectName("checkBox_137")
        self.checkButtonsGroup5.addButton(self.checkBox_137)
        self.verticalLayout_6.addWidget(self.checkBox_137)
        self.checkBox_138 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_138.setFont(font)
        self.checkBox_138.setObjectName("checkBox_138")
        self.checkButtonsGroup5.addButton(self.checkBox_138)
        self.verticalLayout_6.addWidget(self.checkBox_138)
        self.checkBox_139 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_139.setFont(font)
        self.checkBox_139.setObjectName("checkBox_139")
        self.checkButtonsGroup5.addButton(self.checkBox_139)
        self.verticalLayout_6.addWidget(self.checkBox_139)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_11)
        self.layoutWidget6.setGeometry(QtCore.QRect(40, 92, 200, 361))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkBox_108 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_108.setFont(font)
        self.checkBox_108.setObjectName("checkBox_108")
        self.checkButtonsGroup5.addButton(self.checkBox_108)
        self.verticalLayout_7.addWidget(self.checkBox_108)
        self.checkBox_109 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_109.setFont(font)
        self.checkBox_109.setObjectName("checkBox_109")
        self.checkButtonsGroup5.addButton(self.checkBox_109)
        self.verticalLayout_7.addWidget(self.checkBox_109)
        self.checkBox_110 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_110.setFont(font)
        self.checkBox_110.setObjectName("checkBox_110")
        self.checkButtonsGroup5.addButton(self.checkBox_110)
        self.verticalLayout_7.addWidget(self.checkBox_110)
        self.checkBox_111 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_111.setFont(font)
        self.checkBox_111.setObjectName("checkBox_111")
        self.checkButtonsGroup5.addButton(self.checkBox_111)
        self.verticalLayout_7.addWidget(self.checkBox_111)
        self.checkBox_112 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_112.setFont(font)
        self.checkBox_112.setObjectName("checkBox_112")
        self.checkButtonsGroup5.addButton(self.checkBox_112)
        self.verticalLayout_7.addWidget(self.checkBox_112)
        self.checkBox_113 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_113.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_113.sizePolicy().hasHeightForWidth())
        self.checkBox_113.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_113.setFont(font)
        self.checkBox_113.setObjectName("checkBox_113")
        self.checkButtonsGroup5.addButton(self.checkBox_113)
        self.verticalLayout_7.addWidget(self.checkBox_113)
        self.checkBox_114 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_114.setFont(font)
        self.checkBox_114.setObjectName("checkBox_114")
        self.checkButtonsGroup5.addButton(self.checkBox_114)
        self.verticalLayout_7.addWidget(self.checkBox_114)
        self.checkBox_115 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_115.setFont(font)
        self.checkBox_115.setObjectName("checkBox_115")
        self.checkButtonsGroup5.addButton(self.checkBox_115)
        self.verticalLayout_7.addWidget(self.checkBox_115)
        self.checkBox_116 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_116.setFont(font)
        self.checkBox_116.setObjectName("checkBox_116")
        self.checkButtonsGroup5.addButton(self.checkBox_116)
        self.verticalLayout_7.addWidget(self.checkBox_116)
        self.checkBox_117 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_117.setFont(font)
        self.checkBox_117.setObjectName("checkBox_117")
        self.checkButtonsGroup5.addButton(self.checkBox_117)
        self.verticalLayout_7.addWidget(self.checkBox_117)
        self.checkBox_118 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_118.setFont(font)
        self.checkBox_118.setObjectName("checkBox_118")
        self.checkButtonsGroup5.addButton(self.checkBox_118)
        self.verticalLayout_7.addWidget(self.checkBox_118)
        self.checkBox_119 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_119.setFont(font)
        self.checkBox_119.setObjectName("checkBox_119")
        self.checkButtonsGroup5.addButton(self.checkBox_119)
        self.verticalLayout_7.addWidget(self.checkBox_119)
        self.checkBox_120 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_120.setFont(font)
        self.checkBox_120.setObjectName("checkBox_120")
        self.checkButtonsGroup5.addButton(self.checkBox_120)
        self.verticalLayout_7.addWidget(self.checkBox_120)
        self.checkBox_121 = QtWidgets.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_121.setFont(font)
        self.checkBox_121.setObjectName("checkBox_121")
        self.checkButtonsGroup5.addButton(self.checkBox_121)
        self.verticalLayout_7.addWidget(self.checkBox_121)
        self.Button_Legend_Geomorpg_Orig = QtWidgets.QPushButton(self.groupBox_11)
        self.Button_Legend_Geomorpg_Orig.setEnabled(True)
        self.Button_Legend_Geomorpg_Orig.setGeometry(QtCore.QRect(40, 28, 21, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Legend_Geomorpg_Orig.sizePolicy().hasHeightForWidth())
        self.Button_Legend_Geomorpg_Orig.setSizePolicy(sizePolicy)
        self.Button_Legend_Geomorpg_Orig.setBaseSize(QtCore.QSize(23, 23))
        self.Button_Legend_Geomorpg_Orig.setText("")
        self.Button_Legend_Geomorpg_Orig.setIcon(icon)
        self.Button_Legend_Geomorpg_Orig.setObjectName("Button_Legend_Geomorpg_Orig")
        self.label_3 = QtWidgets.QLabel(self.groupBox_11)
        self.label_3.setGeometry(QtCore.QRect(76, 56, 153, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_11)
        self.label_2.setGeometry(QtCore.QRect(76, 32, 153, 18))
        self.label_2.setObjectName("label_2")
        self.Button_Legend_Geomorph_Deutsch = QtWidgets.QPushButton(self.groupBox_11)
        self.Button_Legend_Geomorph_Deutsch.setEnabled(True)
        self.Button_Legend_Geomorph_Deutsch.setGeometry(QtCore.QRect(40, 52, 21, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Legend_Geomorph_Deutsch.sizePolicy().hasHeightForWidth())
        self.Button_Legend_Geomorph_Deutsch.setSizePolicy(sizePolicy)
        self.Button_Legend_Geomorph_Deutsch.setBaseSize(QtCore.QSize(23, 23))
        self.Button_Legend_Geomorph_Deutsch.setText("")
        self.Button_Legend_Geomorph_Deutsch.setIcon(icon)
        self.Button_Legend_Geomorph_Deutsch.setObjectName("Button_Legend_Geomorph_Deutsch")
        self.tabWidget.addTab(self.tab_5, "")

        self.retranslateUi(frmGeologie)
        self.tabWidget.setCurrentIndex(0)
        self.ButtonGeolgoieOk.clicked.connect(frmGeologie.accept)
        self.ButtonGeologieCancel.clicked.connect(frmGeologie.close)
        self.Button_Legend_Geologie_2007.clicked.connect(frmGeologie.clicked)
        self.Button_Legend_Tektonisch_1998.clicked.connect(frmGeologie.clicked)
        self.Profilschintt_Vorarlberg.clicked.connect(frmGeologie.clicked)
        self.Button_Legend_Geomorpg_Orig.clicked.connect(frmGeologie.clicked)
        self.Button_Legend_Geomorph_Deutsch.clicked.connect(frmGeologie.clicked)
        QtCore.QMetaObject.connectSlotsByName(frmGeologie)

    def retranslateUi(self, frmGeologie):
        _translate = QtCore.QCoreApplication.translate
        frmGeologie.setWindowTitle(_translate("frmGeologie", "Geologie"))
        self.ButtonGeolgoieOk.setText(_translate("frmGeologie", "Themen laden"))
        self.ButtonGeologieCancel.setText(_translate("frmGeologie", "Schließen"))
        self.groupBox.setTitle(_translate("frmGeologie", "Allgemein"))
        self.checkBox.setText(_translate("frmGeologie", "Geologische Karte Vorarlberg (GBA, 2007)"))
        self.checkBox_2.setText(_translate("frmGeologie", "Geologische_Tektonische Karte (GBA, 1998)"))
        self.label.setText(_translate("frmGeologie", "Profilschnitt Vorarlberg"))
        self.checkBox_3.setText(_translate("frmGeologie", "Bohrprofile"))
        self.checkBox_5.setText(_translate("frmGeologie", "Geologische Detailuntersuchungen"))
        self.checkBox_6.setText(_translate("frmGeologie", "Geologische Karte (Richter)"))
        self.checkBox_7.setText(_translate("frmGeologie", "Geologie Rheintal (Starck, 1970)"))
        self.checkBox_8.setText(_translate("frmGeologie", "Gefahrenhinweiskarte (GBA, 2006)"))
        self.checkBox_9.setText(_translate("frmGeologie", "Georisken Montafon (Bertle, 1995)"))
        self.checkBox_23.setText(_translate("frmGeologie", "Geotop-Inventar"))
        self.checkBox_25.setText(_translate("frmGeologie", "Grundwasser-Chemismus Rheintal (Starck)"))
        self.checkBox_24.setText(_translate("frmGeologie", "Grundwasser-Schichten_Linien Rheintal (nur VIIa)"))
        self.checkBox_11.setText(_translate("frmGeologie", "Historische Übersichtskarte (Schmidt 1839-1841)"))
        self.checkBox_19.setText(_translate("frmGeologie", "Ereigniskataster (Starck, 1974-2003)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmGeologie", "Allgemein"))
        self.groupBox_2.setTitle(_translate("frmGeologie", "Geologische Gebietskarten"))
        self.checkBox_4.setText(_translate("frmGeologie", "Übersichtskarten"))
        self.checkBox_10.setText(_translate("frmGeologie", "Arlberggebiet (GBA, 1932)"))
        self.checkBox_12.setText(_translate("frmGeologie", "Bezau (GBA, Manuskript)"))
        self.checkBox_13.setText(_translate("frmGeologie", "Bregenz (GBA, 1982)"))
        self.checkBox_14.setText(_translate("frmGeologie", "Dornbirn Nord (GBA, 1994)"))
        self.checkBox_15.setText(_translate("frmGeologie", "Dornbirn Süd (GBA, 1982)"))
        self.checkBox_16.setText(_translate("frmGeologie", "Flexenpass (Doert und Helmcke, 1975)"))
        self.checkBox_17.setText(_translate("frmGeologie", "Heiterwand (Tirol) (GBA, 1932)"))
        self.checkBox_18.setText(_translate("frmGeologie", "Klostertal (Helmcke, 1972)"))
        self.checkBox_26.setText(_translate("frmGeologie", "Klostertaler Alpen (GBA, 1932)"))
        self.checkBox_27.setText(_translate("frmGeologie", "Liechtenstein (RFL, 1985)"))
        self.checkBox_28.setText(_translate("frmGeologie", "Mittelberg (GBA, 1990)"))
        self.checkBox_29.setText(_translate("frmGeologie", "Parseiergruppe (Tirol)  (GBA, 1932)"))
        self.checkBox_30.setText(_translate("frmGeologie", "Partenen Ost (GBA, 1980)"))
        self.checkBox_33.setText(_translate("frmGeologie", "Partenen West (GBA, 1980)"))
        self.checkBox_37.setText(_translate("frmGeologie", "Walgau (GBA, 1967)"))
        self.checkBox_38.setText(_translate("frmGeologie", "Walsertal (Otte und Helmcke)"))
        self.checkBox_36.setText(_translate("frmGeologie", "Vorderwald (Muheim, 1934)"))
        self.checkBox_35.setText(_translate("frmGeologie", "Sulzberg (GBA, 1984)"))
        self.checkBox_31.setText(_translate("frmGeologie", "Stuben (GBA, 1937)"))
        self.checkBox_34.setText(_translate("frmGeologie", "Schönenbach"))
        self.checkBox_32.setText(_translate("frmGeologie", "Rätikon (GBA)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmGeologie", "Geologische Gebietskarten"))
        self.groupBox_3.setTitle(_translate("frmGeologie", "Geologische Detailkarten"))
        self.checkBox_20.setText(_translate("frmGeologie", "Ausser Montafon (Bertha, 1978)"))
        self.checkBox_21.setText(_translate("frmGeologie", "Dalaas (Koehler, 1977)"))
        self.checkBox_22.setText(_translate("frmGeologie", "Davenna (Kasper, 1990)"))
        self.checkBox_39.setText(_translate("frmGeologie", "Firstkette (Golde, 1993)"))
        self.checkBox_40.setText(_translate("frmGeologie", "Gafadura (Post, 1996)"))
        self.checkBox_41.setText(_translate("frmGeologie", "Gargellen (Bertle, 1972)"))
        self.checkBox_42.setText(_translate("frmGeologie", "Gopfberg (Oberhauser M., 1993)"))
        self.checkBox_43.setText(_translate("frmGeologie", "Rätikon östlich (Steinacher, 2004)"))
        self.checkBox_44.setText(_translate("frmGeologie", "Rätikon östlich (Mayerl, 2005)"))
        self.checkBox_45.setText(_translate("frmGeologie", "Sibratsgfäll (Haak, 1995)"))
        self.checkBox_46.setText(_translate("frmGeologie", "Tschagguns - Mauren (Bertle, 1995)"))
        self.checkBox_47.setText(_translate("frmGeologie", "Tschöppa (Bertle, 1992)"))
        self.checkBox_48.setText(_translate("frmGeologie", "Winterstaude (Oberhauser)"))
        self.checkBox_49.setText(_translate("frmGeologie", "Winterstaude (Alexander)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmGeologie", "Geologische Detailkarten"))
        self.groupBox_4.setTitle(_translate("frmGeologie", "Geologie"))
        self.groupBox_5.setTitle(_translate("frmGeologie", "Geologie"))
        self.checkBox_55.setText(_translate("frmGeologie", "Alberschwende"))
        self.checkBox_56.setText(_translate("frmGeologie", "Au"))
        self.checkBox_57.setText(_translate("frmGeologie", "Faschina"))
        self.checkBox_58.setText(_translate("frmGeologie", "Hochtannberg/Arlberg"))
        self.checkBox_59.setText(_translate("frmGeologie", "Sibratsgfaell"))
        self.checkBox_50.setText(_translate("frmGeologie", "Alberschwende"))
        self.checkBox_51.setText(_translate("frmGeologie", "Au"))
        self.checkBox_52.setText(_translate("frmGeologie", "Faschina"))
        self.checkBox_53.setText(_translate("frmGeologie", "Hochtannberg/Arlberg"))
        self.checkBox_54.setText(_translate("frmGeologie", "Sibratsgfäll"))
        self.groupBox_6.setTitle(_translate("frmGeologie", "Rutschung"))
        self.groupBox_7.setTitle(_translate("frmGeologie", "Geologie"))
        self.checkBox_65.setText(_translate("frmGeologie", "Alberschwende"))
        self.checkBox_66.setText(_translate("frmGeologie", "Au"))
        self.checkBox_67.setText(_translate("frmGeologie", "Faschina"))
        self.checkBox_68.setText(_translate("frmGeologie", "Hochtannberg/Arlberg"))
        self.checkBox_69.setText(_translate("frmGeologie", "Sibratsgfaell"))
        self.checkBox_60.setText(_translate("frmGeologie", "Alberschwende"))
        self.checkBox_61.setText(_translate("frmGeologie", "Faschina"))
        self.checkBox_62.setText(_translate("frmGeologie", "Hochtannberg"))
        self.checkBox_63.setText(_translate("frmGeologie", "Schoppernau"))
        self.checkBox_64.setText(_translate("frmGeologie", "Walgau"))
        self.groupBox_8.setTitle(_translate("frmGeologie", "Steinschlag"))
        self.groupBox_9.setTitle(_translate("frmGeologie", "Geologie"))
        self.checkBox_75.setText(_translate("frmGeologie", "Alberschwende"))
        self.checkBox_76.setText(_translate("frmGeologie", "Au"))
        self.checkBox_77.setText(_translate("frmGeologie", "Faschina"))
        self.checkBox_78.setText(_translate("frmGeologie", "Hochtannberg/Arlberg"))
        self.checkBox_79.setText(_translate("frmGeologie", "Sibratsgfaell"))
        self.checkBox_70.setText(_translate("frmGeologie", "Hochtannberg"))
        self.checkBox_71.setText(_translate("frmGeologie", "Klostertal"))
        self.checkBox_72.setText(_translate("frmGeologie", "Mellau"))
        self.checkBox_73.setText(_translate("frmGeologie", "Schröcken"))
        self.checkBox_74.setText(_translate("frmGeologie", "Walgau"))
        self.groupBox_10.setTitle(_translate("frmGeologie", "Geotechnik"))
        self.checkBox_80.setText(_translate("frmGeologie", "Alberschwende Nord"))
        self.checkBox_81.setText(_translate("frmGeologie", "Alberschwende Süd"))
        self.checkBox_82.setText(_translate("frmGeologie", "Au"))
        self.checkBox_83.setText(_translate("frmGeologie", "Flexenpass"))
        self.checkBox_84.setText(_translate("frmGeologie", "Ippacherwald"))
        self.checkBox_85.setText(_translate("frmGeologie", "Lech"))
        self.checkBox_86.setText(_translate("frmGeologie", "Mellau"))
        self.checkBox_87.setText(_translate("frmGeologie", "Schoppernau"))
        self.checkBox_88.setText(_translate("frmGeologie", "Schröcken"))
        self.checkBox_89.setText(_translate("frmGeologie", "Schwarzachtobel"))
        self.checkBox_90.setText(_translate("frmGeologie", "Sibratsgfäll"))
        self.checkBox_91.setText(_translate("frmGeologie", "Warth"))
        self.checkBox_92.setText(_translate("frmGeologie", "Warth/Saloberkopf"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmGeologie", "Georisiko-Karten (AGK)"))
        self.groupBox_11.setTitle(_translate("frmGeologie", "Geomophologische Karten (Uni-Amsterdam)"))
        self.checkBox_122.setText(_translate("frmGeologie", "Blatt Hopfreben:"))
        self.checkBox_123.setText(_translate("frmGeologie", "Blatt Ludesch:"))
        self.checkBox_124.setText(_translate("frmGeologie", "Blatt Marul:"))
        self.checkBox_125.setText(_translate("frmGeologie", "Blatt Mellau:"))
        self.checkBox_126.setText(_translate("frmGeologie", "Blatt Mellenspitze:"))
        self.checkBox_127.setText(_translate("frmGeologie", "Blatt Mittleres Silbertal:"))
        self.checkBox_128.setText(_translate("frmGeologie", "Blatt Nenzinger Himmel:"))
        self.checkBox_129.setText(_translate("frmGeologie", "Blatt Rellstal-Golm:"))
        self.checkBox_130.setText(_translate("frmGeologie", "Blatt Rellstal-Zimba:"))
        self.checkBox_131.setText(_translate("frmGeologie", "Blatt Satteins:"))
        self.checkBox_132.setText(_translate("frmGeologie", "Blatt Schnepfau:"))
        self.checkBox_133.setText(_translate("frmGeologie", "Blatt Schnifis:"))
        self.checkBox_134.setText(_translate("frmGeologie", "Blatt Schoppernau:"))
        self.checkBox_135.setText(_translate("frmGeologie", "Blatt Schönenbach:"))
        self.checkBox_136.setText(_translate("frmGeologie", "Blatt Silbertal:"))
        self.checkBox_137.setText(_translate("frmGeologie", "Blatt Sonntag:"))
        self.checkBox_138.setText(_translate("frmGeologie", "Blatt St. Gallenkirch:"))
        self.checkBox_139.setText(_translate("frmGeologie", "Blatt Zitterklapfen:"))
        self.checkBox_108.setText(_translate("frmGeologie", "Blatt Au:"))
        self.checkBox_109.setText(_translate("frmGeologie", "Blatt Bartholomäberg:"))
        self.checkBox_110.setText(_translate("frmGeologie", "Blatt Bezau:"))
        self.checkBox_111.setText(_translate("frmGeologie", "Blatt Bizau:"))
        self.checkBox_112.setText(_translate("frmGeologie", "Blatt Brand-Nord:"))
        self.checkBox_113.setText(_translate("frmGeologie", "Blatt Brand-Süd:"))
        self.checkBox_114.setText(_translate("frmGeologie", "Blatt Damüls:"))
        self.checkBox_115.setText(_translate("frmGeologie", "Blatt Damülser Mittagsspitze:"))
        self.checkBox_116.setText(_translate("frmGeologie", "Blatt Diedamskopf:"))
        self.checkBox_117.setText(_translate("frmGeologie", "Blatt Dunza-Tschengla:"))
        self.checkBox_118.setText(_translate("frmGeologie", "Blatt Fundelkopf:"))
        self.checkBox_119.setText(_translate("frmGeologie", "Blatt Gampberg:"))
        self.checkBox_120.setText(_translate("frmGeologie", "Blatt Gurtis:"))
        self.checkBox_121.setText(_translate("frmGeologie", "Blatt Klaus-Weiler:"))
        self.label_3.setText(_translate("frmGeologie", "Geomorph. Legende (Deutsch)"))
        self.label_2.setText(_translate("frmGeologie", "Geomorph. Legende (Orginal)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmGeologie", "Geomorphologische Karten (Uni Amsterdam)"))

import resources_rc
