# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_topokarten.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmTopokarten(object):
    def setupUi(self, frmTopokarten):
        frmTopokarten.setObjectName("frmTopokarten")
        frmTopokarten.resize(382, 524)
        self.ButtonTopokartenOk = QtWidgets.QPushButton(frmTopokarten)
        self.ButtonTopokartenOk.setGeometry(QtCore.QRect(30, 470, 121, 23))
        self.ButtonTopokartenOk.setObjectName("ButtonTopokartenOk")
        self.ButtonTopokartenCancel = QtWidgets.QPushButton(frmTopokarten)
        self.ButtonTopokartenCancel.setGeometry(QtCore.QRect(220, 470, 121, 23))
        self.ButtonTopokartenCancel.setObjectName("ButtonTopokartenCancel")
        self.toolBox = QtWidgets.QToolBox(frmTopokarten)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 361, 441))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 361, 387))
        self.page.setObjectName("page")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 310, 281, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setObjectName("radioButton_11")
        self.checkButtonsGroup = QtWidgets.QButtonGroup(frmTopokarten)
        self.checkButtonsGroup.setObjectName("checkButtonsGroup")
        self.checkButtonsGroup.addButton(self.radioButton_11)
        self.verticalLayout_2.addWidget(self.radioButton_11)
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(40, 10, 281, 293))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkButtonsGroup.addButton(self.checkBox)
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkButtonsGroup.addButton(self.checkBox_2)
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkButtonsGroup.addButton(self.checkBox_3)
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkButtonsGroup.addButton(self.checkBox_4)
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkButtonsGroup.addButton(self.checkBox_5)
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkButtonsGroup.addButton(self.checkBox_6)
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkButtonsGroup.addButton(self.checkBox_7)
        self.verticalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkButtonsGroup.addButton(self.checkBox_8)
        self.verticalLayout.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkButtonsGroup.addButton(self.checkBox_9)
        self.verticalLayout.addWidget(self.checkBox_9)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_2.setObjectName("page_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 30, 265, 261))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 219, 212))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_12 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkButtonsGroup.addButton(self.checkBox_12)
        self.verticalLayout_3.addWidget(self.checkBox_12)
        self.checkBox_15 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkButtonsGroup.addButton(self.checkBox_15)
        self.verticalLayout_3.addWidget(self.checkBox_15)
        self.checkBox_17 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_17.setFont(font)
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkButtonsGroup.addButton(self.checkBox_17)
        self.verticalLayout_3.addWidget(self.checkBox_17)
        self.checkBox_26 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_26.setFont(font)
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkButtonsGroup.addButton(self.checkBox_26)
        self.verticalLayout_3.addWidget(self.checkBox_26)
        self.checkBox_29 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_29.setFont(font)
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkButtonsGroup.addButton(self.checkBox_29)
        self.verticalLayout_3.addWidget(self.checkBox_29)
        self.checkBox_30 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_30.setFont(font)
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkButtonsGroup.addButton(self.checkBox_30)
        self.verticalLayout_3.addWidget(self.checkBox_30)
        self.checkBox_31 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_31.setFont(font)
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkButtonsGroup.addButton(self.checkBox_31)
        self.verticalLayout_3.addWidget(self.checkBox_31)
        self.checkBox_32 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_32.setFont(font)
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkButtonsGroup.addButton(self.checkBox_32)
        self.verticalLayout_3.addWidget(self.checkBox_32)
        self.toolBox.addItem(self.page_2, "")

        self.retranslateUi(frmTopokarten)
        self.toolBox.setCurrentIndex(0)
        self.ButtonTopokartenOk.clicked.connect(frmTopokarten.accept)
        self.ButtonTopokartenCancel.clicked.connect(frmTopokarten.close)
        QtCore.QMetaObject.connectSlotsByName(frmTopokarten)

    def retranslateUi(self, frmTopokarten):
        _translate = QtCore.QCoreApplication.translate
        frmTopokarten.setWindowTitle(_translate("frmTopokarten", "Topographische Karten"))
        self.ButtonTopokartenOk.setText(_translate("frmTopokarten", "Themen laden"))
        self.ButtonTopokartenCancel.setText(_translate("frmTopokarten", "Schließen"))
        self.groupBox_2.setTitle(_translate("frmTopokarten", "Sonstiges", "aaaa"))
        self.radioButton_11.setText(_translate("frmTopokarten", "Namen ÖK50"))
        self.groupBox.setTitle(_translate("frmTopokarten", "Topographische Karten", "aaaa"))
        self.checkBox.setText(_translate("frmTopokarten", "Topogr. Karte (VoGIS)"))
        self.checkBox_2.setText(_translate("frmTopokarten", "Topogr. Karte Winter (VoGIS)"))
        self.checkBox_3.setText(_translate("frmTopokarten", "Topogr. Karte PDF-Ebenen (VoGIS)"))
        self.checkBox_4.setText(_translate("frmTopokarten", "Topogr. Karte (Verkehrsverbund)"))
        self.checkBox_5.setText(_translate("frmTopokarten", "ÖK 1:50.000 Vlbg. (BEV)"))
        self.checkBox_6.setText(_translate("frmTopokarten", "ÖK 1:50.000 Vlbg. + Umg. (BEV)"))
        self.checkBox_7.setText(_translate("frmTopokarten", "Heimatkarte 1:100.000 (FreytagBerndt)"))
        self.checkBox_8.setText(_translate("frmTopokarten", "ÖK 1:200.000  (BEV)"))
        self.checkBox_9.setText(_translate("frmTopokarten", "ÖK 1:500.000  (BEV)"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("frmTopokarten", "Topographische Karten"))
        self.groupBox_3.setTitle(_translate("frmTopokarten", "Historische Karten"))
        self.checkBox_12.setText(_translate("frmTopokarten", "Urmappe:"))
        self.checkBox_15.setText(_translate("frmTopokarten", "3. Landesaufnahme 1871 - 1872:"))
        self.checkBox_17.setText(_translate("frmTopokarten", "Reambulierte 3. LA 1887:"))
        self.checkBox_26.setText(_translate("frmTopokarten", "Spezialkarten 1908-15 / 1934-37:"))
        self.checkBox_29.setText(_translate("frmTopokarten", "Provisorische ÖK 1946-47:"))
        self.checkBox_30.setText(_translate("frmTopokarten", "ÖK50 1953-67:"))
        self.checkBox_31.setText(_translate("frmTopokarten", "ÖK50 1961-74:"))
        self.checkBox_32.setText(_translate("frmTopokarten", "ÖK50 1971-80:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("frmTopokarten", "Historische Karten"))

