# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_raumplanung.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmRaumplanung(object):
    def setupUi(self, frmRaumplanung):
        frmRaumplanung.setObjectName("frmRaumplanung")
        frmRaumplanung.resize(308, 333)
        self.ButtonBlattschnitteOk = QtWidgets.QPushButton(frmRaumplanung)
        self.ButtonBlattschnitteOk.setGeometry(QtCore.QRect(30, 290, 101, 23))
        self.ButtonBlattschnitteOk.setObjectName("ButtonBlattschnitteOk")
        self.ButtonBlattschnitteCancel = QtWidgets.QPushButton(frmRaumplanung)
        self.ButtonBlattschnitteCancel.setGeometry(QtCore.QRect(160, 290, 101, 23))
        self.ButtonBlattschnitteCancel.setObjectName("ButtonBlattschnitteCancel")
        self.layoutWidget = QtWidgets.QWidget(frmRaumplanung)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 20, 195, 249))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ckFundzonen = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckFundzonen.setEnabled(True)
        self.ckFundzonen.setObjectName("ckFundzonen")
        self.ckButtons = QtWidgets.QButtonGroup(frmRaumplanung)
        self.ckButtons.setObjectName("ckButtons")
        self.ckButtons.setExclusive(False)
        self.ckButtons.addButton(self.ckFundzonen)
        self.verticalLayout.addWidget(self.ckFundzonen)
        self.ckBauflaechen = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckBauflaechen.setEnabled(True)
        self.ckBauflaechen.setObjectName("ckBauflaechen")
        self.ckButtons.addButton(self.ckBauflaechen)
        self.verticalLayout.addWidget(self.ckBauflaechen)
        self.ckBlauzone = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckBlauzone.setEnabled(True)
        self.ckBlauzone.setObjectName("ckBlauzone")
        self.ckButtons.addButton(self.ckBlauzone)
        self.verticalLayout.addWidget(self.ckBlauzone)
        self.ckEignungEkz = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckEignungEkz.setEnabled(True)
        self.ckEignungEkz.setObjectName("ckEignungEkz")
        self.ckButtons.addButton(self.ckEignungEkz)
        self.verticalLayout.addWidget(self.ckEignungEkz)
        self.ckEkz = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckEkz.setEnabled(True)
        self.ckEkz.setObjectName("ckEkz")
        self.ckButtons.addButton(self.ckEkz)
        self.verticalLayout.addWidget(self.ckEkz)
        self.ckGruenzone = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckGruenzone.setEnabled(True)
        self.ckGruenzone.setObjectName("ckGruenzone")
        self.ckButtons.addButton(self.ckGruenzone)
        self.verticalLayout.addWidget(self.ckGruenzone)
        self.ckMaisaess = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckMaisaess.setEnabled(True)
        self.ckMaisaess.setObjectName("ckMaisaess")
        self.ckButtons.addButton(self.ckMaisaess)
        self.verticalLayout.addWidget(self.ckMaisaess)
        self.ckMauerinventar = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckMauerinventar.setEnabled(True)
        self.ckMauerinventar.setObjectName("ckMauerinventar")
        self.ckButtons.addButton(self.ckMauerinventar)
        self.verticalLayout.addWidget(self.ckMauerinventar)
        self.ckRohstoffplan = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckRohstoffplan.setEnabled(True)
        self.ckRohstoffplan.setObjectName("ckRohstoffplan")
        self.ckButtons.addButton(self.ckRohstoffplan)
        self.verticalLayout.addWidget(self.ckRohstoffplan)
        self.ckSeveso = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckSeveso.setEnabled(True)
        self.ckSeveso.setObjectName("ckSeveso")
        self.ckButtons.addButton(self.ckSeveso)
        self.verticalLayout.addWidget(self.ckSeveso)
        self.ckWeisszone = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckWeisszone.setEnabled(True)
        self.ckWeisszone.setObjectName("ckWeisszone")
        self.ckButtons.addButton(self.ckWeisszone)
        self.verticalLayout.addWidget(self.ckWeisszone)

        self.retranslateUi(frmRaumplanung)
        self.ButtonBlattschnitteOk.clicked.connect(frmRaumplanung.accept)
        self.ButtonBlattschnitteCancel.clicked.connect(frmRaumplanung.close)
        QtCore.QMetaObject.connectSlotsByName(frmRaumplanung)

    def retranslateUi(self, frmRaumplanung):
        _translate = QtCore.QCoreApplication.translate
        frmRaumplanung.setWindowTitle(_translate("frmRaumplanung", "Raumplanung"))
        self.ButtonBlattschnitteOk.setText(_translate("frmRaumplanung", "Themen laden"))
        self.ButtonBlattschnitteCancel.setText(_translate("frmRaumplanung", "Schließen"))
        self.ckFundzonen.setText(_translate("frmRaumplanung", "Archäologische Fundzonen"))
        self.ckBauflaechen.setText(_translate("frmRaumplanung", "Bauflächen-Nutzung"))
        self.ckBlauzone.setText(_translate("frmRaumplanung", "Blauzone"))
        self.ckEignungEkz.setText(_translate("frmRaumplanung", "Eignungszonen für Einkaufszentren"))
        self.ckEkz.setText(_translate("frmRaumplanung", "Einkaufszentren"))
        self.ckGruenzone.setText(_translate("frmRaumplanung", "Grünzone"))
        self.ckMaisaess.setText(_translate("frmRaumplanung", "Maisäß Gebietsausweisung"))
        self.ckMauerinventar.setText(_translate("frmRaumplanung", "Mauerinventar"))
        self.ckRohstoffplan.setText(_translate("frmRaumplanung", "Rohstoffplan"))
        self.ckSeveso.setText(_translate("frmRaumplanung", "Seveso II Richtlinie"))
        self.ckWeisszone.setText(_translate("frmRaumplanung", "Weißzone"))

