# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_blattschnitte.ui'
#
# Created: Wed Jun 27 15:34:42 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmBlattschnitte(object):
    def setupUi(self, frmBlattschnitte):
        frmBlattschnitte.setObjectName(_fromUtf8("frmBlattschnitte"))
        frmBlattschnitte.resize(293, 504)
        self.ButtonBlattschnitteOk = QtGui.QPushButton(frmBlattschnitte)
        self.ButtonBlattschnitteOk.setGeometry(QtCore.QRect(20, 450, 111, 31))
        self.ButtonBlattschnitteOk.setObjectName(_fromUtf8("ButtonBlattschnitteOk"))
        self.ButtonBlattschnitteCancel = QtGui.QPushButton(frmBlattschnitte)
        self.ButtonBlattschnitteCancel.setGeometry(QtCore.QRect(160, 450, 111, 31))
        self.ButtonBlattschnitteCancel.setObjectName(_fromUtf8("ButtonBlattschnitteCancel"))
        self.frame = QtGui.QFrame(frmBlattschnitte)
        self.frame.setGeometry(QtCore.QRect(20, 20, 251, 341))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget = QtGui.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 22, 144, 301))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBox = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkButtonsGroup = QtGui.QButtonGroup(frmBlattschnitte)
        self.checkButtonsGroup.setObjectName(_fromUtf8("checkButtonsGroup"))
        self.checkButtonsGroup.addButton(self.checkBox)
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkButtonsGroup.addButton(self.checkBox_2)
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkButtonsGroup.addButton(self.checkBox_3)
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkButtonsGroup.addButton(self.checkBox_4)
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkButtonsGroup.addButton(self.checkBox_5)
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkButtonsGroup.addButton(self.checkBox_6)
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkButtonsGroup.addButton(self.checkBox_7)
        self.verticalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.checkButtonsGroup.addButton(self.checkBox_8)
        self.verticalLayout.addWidget(self.checkBox_8)
        self.checkBox_9 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.checkButtonsGroup.addButton(self.checkBox_9)
        self.verticalLayout.addWidget(self.checkBox_9)
        self.checkBox_10 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.checkButtonsGroup.addButton(self.checkBox_10)
        self.verticalLayout.addWidget(self.checkBox_10)
        self.checkBox_11 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.checkButtonsGroup.addButton(self.checkBox_11)
        self.verticalLayout.addWidget(self.checkBox_11)
        self.frame_2 = QtGui.QFrame(frmBlattschnitte)
        self.frame_2.setGeometry(QtCore.QRect(20, 380, 251, 61))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.radioButton = QtGui.QRadioButton(self.frame_2)
        self.radioButton.setGeometry(QtCore.QRect(40, 10, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 30, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))

        self.retranslateUi(frmBlattschnitte)
        QtCore.QObject.connect(self.ButtonBlattschnitteOk, QtCore.SIGNAL(_fromUtf8("clicked()")), frmBlattschnitte.accept)
        QtCore.QObject.connect(self.ButtonBlattschnitteCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), frmBlattschnitte.close)
        QtCore.QMetaObject.connectSlotsByName(frmBlattschnitte)

    def retranslateUi(self, frmBlattschnitte):
        frmBlattschnitte.setWindowTitle(QtGui.QApplication.translate("frmBlattschnitte", "Blattschnitte", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonBlattschnitteOk.setText(QtGui.QApplication.translate("frmBlattschnitte", "Themen laden", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonBlattschnitteCancel.setText(QtGui.QApplication.translate("frmBlattschnitte", "Schließen", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("frmBlattschnitte", "Blattschnitt ÖK", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("frmBlattschnitte", "Blattschnitt 50000", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("frmBlattschnitte", "Blattschnitt 25000", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("frmBlattschnitte", "Blattschnitt 20000", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("frmBlattschnitte", "Blattschnitt 10000", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("frmBlattschnitte", "Blattschnitt 5000", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("frmBlattschnitte", "Blattschnitt 2500", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("frmBlattschnitte", "Blattschnitt 2000", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("frmBlattschnitte", "Blattschnitt 1000", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("frmBlattschnitte", "Blattschnitt Urmappe", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("frmBlattschnitte", "Koordinatennetz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("frmBlattschnitte", "Mit Nummerierung", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("frmBlattschnitte", "Ohne Nummerierung", None, QtGui.QApplication.UnicodeUTF8))

