# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_gfz.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmGFZ(object):
    def setupUi(self, frmGFZ):
        frmGFZ.setObjectName("frmGFZ")
        frmGFZ.resize(354, 595)
        self.btnAbbrechen = QtWidgets.QPushButton(frmGFZ)
        self.btnAbbrechen.setGeometry(QtCore.QRect(120, 530, 121, 31))
        self.btnAbbrechen.setObjectName("btnAbbrechen")
        self.groupBox = QtWidgets.QGroupBox(frmGFZ)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 311, 281))
        self.groupBox.setObjectName("groupBox")
        self.btnGFZ = QtWidgets.QPushButton(self.groupBox)
        self.btnGFZ.setGeometry(QtCore.QRect(100, 232, 111, 31))
        self.btnGFZ.setObjectName("btnGFZ")
        self.btGmdChoice = QtWidgets.QPushButton(self.groupBox)
        self.btGmdChoice.setGeometry(QtCore.QRect(210, 190, 31, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btGmdChoice.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btGmdChoice.setFont(font)
        self.btGmdChoice.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btGmdChoice.setCheckable(True)
        self.btGmdChoice.setChecked(False)
        self.btGmdChoice.setObjectName("btGmdChoice")
        self.lstGemeinden = QtWidgets.QListView(self.groupBox)
        self.lstGemeinden.setGeometry(QtCore.QRect(30, 20, 256, 161))
        self.lstGemeinden.setObjectName("lstGemeinden")
        self.btnVorarlberg = QtWidgets.QPushButton(self.groupBox)
        self.btnVorarlberg.setGeometry(QtCore.QRect(50, 190, 111, 23))
        self.btnVorarlberg.setObjectName("btnVorarlberg")
        self.groupBox_2 = QtWidgets.QGroupBox(frmGFZ)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 310, 311, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnGFZVIId = QtWidgets.QPushButton(self.groupBox_2)
        self.btnGFZVIId.setGeometry(QtCore.QRect(180, 70, 111, 23))
        self.btnGFZVIId.setObjectName("btnGFZVIId")
        self.GfzBwv = QtWidgets.QRadioButton(self.groupBox_2)
        self.GfzBwv.setGeometry(QtCore.QRect(10, 60, 131, 18))
        self.GfzBwv.setChecked(True)
        self.GfzBwv.setObjectName("GfzBwv")
        self.buttonGroup = QtWidgets.QButtonGroup(frmGFZ)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.GfzBwv)
        self.btnKompetenzgrenzen = QtWidgets.QPushButton(self.groupBox_2)
        self.btnKompetenzgrenzen.setGeometry(QtCore.QRect(70, 150, 161, 31))
        self.btnKompetenzgrenzen.setObjectName("btnKompetenzgrenzen")
        self.ckUeberflutungsflaechen = QtWidgets.QRadioButton(self.groupBox_2)
        self.ckUeberflutungsflaechen.setGeometry(QtCore.QRect(10, 90, 161, 18))
        self.ckUeberflutungsflaechen.setObjectName("ckUeberflutungsflaechen")
        self.buttonGroup.addButton(self.ckUeberflutungsflaechen)

        self.retranslateUi(frmGFZ)
        self.btnAbbrechen.clicked.connect(frmGFZ.closeEvent)
        self.btnGFZ.clicked.connect(frmGFZ.ladeGemeinde)
        self.btGmdChoice.clicked.connect(frmGFZ.gmd_choice_toggled)
        self.lstGemeinden.clicked['QModelIndex'].connect(frmGFZ.auswahlaenderung)
        self.btnGFZVIId.clicked.connect(frmGFZ.ladeGFZWB)
        self.btnKompetenzgrenzen.clicked.connect(frmGFZ.ladeKompetenzgrenzen)
        self.btnVorarlberg.clicked.connect(frmGFZ.landesflaeche)
        QtCore.QMetaObject.connectSlotsByName(frmGFZ)

    def retranslateUi(self, frmGFZ):
        _translate = QtCore.QCoreApplication.translate
        frmGFZ.setWindowTitle(_translate("frmGFZ", "Gefahrenzonenpläne"))
        self.btnAbbrechen.setText(_translate("frmGFZ", "Schließen"))
        self.groupBox.setTitle(_translate("frmGFZ", "Wildbach- und Lawinenverbauung"))
        self.btnGFZ.setText(_translate("frmGFZ", "GFZ laden"))
        self.btGmdChoice.setText(_translate("frmGFZ", "+"))
        self.btnVorarlberg.setText(_translate("frmGFZ", "Landesfläche Vlbg."))
        self.groupBox_2.setTitle(_translate("frmGFZ", "Abt. VIId - Wasserwirtschaft"))
        self.btnGFZVIId.setText(_translate("frmGFZ", "Daten laden"))
        self.GfzBwv.setText(_translate("frmGFZ", "Gefahrenzonen BWV"))
        self.btnKompetenzgrenzen.setText(_translate("frmGFZ", "Kompetenzgrenzen  BWV - WLV"))
        self.ckUeberflutungsflaechen.setText(_translate("frmGFZ", "Abflussuntersuchungen BWV"))

