# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_wasser.ui'
#
# Created: Tue Jul 12 12:31:39 2016
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmWasser(object):
    def setupUi(self, frmWasser):
        frmWasser.setObjectName(_fromUtf8("frmWasser"))
        frmWasser.resize(362, 480)
        self.toolBox = QtGui.QToolBox(frmWasser)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 361, 411))
        self.toolBox.setFrameShape(QtGui.QFrame.Panel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Sunken)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.toolBoxPage1 = QtGui.QWidget()
        self.toolBoxPage1.setGeometry(QtCore.QRect(0, 0, 359, 166))
        self.toolBoxPage1.setObjectName(_fromUtf8("toolBoxPage1"))
        self.layoutWidget = QtGui.QWidget(self.toolBoxPage1)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 151, 68))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ckQuellen = QtGui.QCheckBox(self.layoutWidget)
        self.ckQuellen.setObjectName(_fromUtf8("ckQuellen"))
        self.ckButtons = QtGui.QButtonGroup(frmWasser)
        self.ckButtons.setObjectName(_fromUtf8("ckButtons"))
        self.ckButtons.addButton(self.ckQuellen)
        self.verticalLayout.addWidget(self.ckQuellen)
        self.ckBrunnen = QtGui.QCheckBox(self.layoutWidget)
        self.ckBrunnen.setObjectName(_fromUtf8("ckBrunnen"))
        self.ckButtons.addButton(self.ckBrunnen)
        self.verticalLayout.addWidget(self.ckBrunnen)
        self.ckSchutzSchongebiete = QtGui.QCheckBox(self.layoutWidget)
        self.ckSchutzSchongebiete.setObjectName(_fromUtf8("ckSchutzSchongebiete"))
        self.ckButtons.addButton(self.ckSchutzSchongebiete)
        self.verticalLayout.addWidget(self.ckSchutzSchongebiete)
        self.toolBox.addItem(self.toolBoxPage1, _fromUtf8(""))
        self.toolBoxPage2 = QtGui.QWidget()
        self.toolBoxPage2.setGeometry(QtCore.QRect(0, 0, 359, 166))
        self.toolBoxPage2.setObjectName(_fromUtf8("toolBoxPage2"))
        self.layoutWidget1 = QtGui.QWidget(self.toolBoxPage2)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 11, 259, 116))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ckGWWaermepumpen = QtGui.QCheckBox(self.layoutWidget1)
        self.ckGWWaermepumpen.setObjectName(_fromUtf8("ckGWWaermepumpen"))
        self.ckButtons.addButton(self.ckGWWaermepumpen)
        self.verticalLayout_2.addWidget(self.ckGWWaermepumpen)
        self.ckErdwaermeanlagen = QtGui.QCheckBox(self.layoutWidget1)
        self.ckErdwaermeanlagen.setObjectName(_fromUtf8("ckErdwaermeanlagen"))
        self.ckButtons.addButton(self.ckErdwaermeanlagen)
        self.verticalLayout_2.addWidget(self.ckErdwaermeanlagen)
        self.ckKuehlwasseranlagenGW = QtGui.QCheckBox(self.layoutWidget1)
        self.ckKuehlwasseranlagenGW.setObjectName(_fromUtf8("ckKuehlwasseranlagenGW"))
        self.ckButtons.addButton(self.ckKuehlwasseranlagenGW)
        self.verticalLayout_2.addWidget(self.ckKuehlwasseranlagenGW)
        self.ckKuehlwasseranlagenOG = QtGui.QCheckBox(self.layoutWidget1)
        self.ckKuehlwasseranlagenOG.setObjectName(_fromUtf8("ckKuehlwasseranlagenOG"))
        self.ckButtons.addButton(self.ckKuehlwasseranlagenOG)
        self.verticalLayout_2.addWidget(self.ckKuehlwasseranlagenOG)
        self.ckWeitereAnlagen = QtGui.QCheckBox(self.layoutWidget1)
        self.ckWeitereAnlagen.setObjectName(_fromUtf8("ckWeitereAnlagen"))
        self.ckButtons.addButton(self.ckWeitereAnlagen)
        self.verticalLayout_2.addWidget(self.ckWeitereAnlagen)
        self.toolBox.addItem(self.toolBoxPage2, _fromUtf8(""))
        self.toolBoxPage3 = QtGui.QWidget()
        self.toolBoxPage3.setGeometry(QtCore.QRect(0, 0, 359, 166))
        self.toolBoxPage3.setObjectName(_fromUtf8("toolBoxPage3"))
        self.layoutWidget2 = QtGui.QWidget(self.toolBoxPage3)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 10, 246, 116))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.ckKraftwerke = QtGui.QCheckBox(self.layoutWidget2)
        self.ckKraftwerke.setObjectName(_fromUtf8("ckKraftwerke"))
        self.ckButtons.addButton(self.ckKraftwerke)
        self.verticalLayout_3.addWidget(self.ckKraftwerke)
        self.ckSonstigeBetriebe = QtGui.QCheckBox(self.layoutWidget2)
        self.ckSonstigeBetriebe.setObjectName(_fromUtf8("ckSonstigeBetriebe"))
        self.ckButtons.addButton(self.ckSonstigeBetriebe)
        self.verticalLayout_3.addWidget(self.ckSonstigeBetriebe)
        self.ckGeschiebe = QtGui.QCheckBox(self.layoutWidget2)
        self.ckGeschiebe.setObjectName(_fromUtf8("ckGeschiebe"))
        self.ckButtons.addButton(self.ckGeschiebe)
        self.verticalLayout_3.addWidget(self.ckGeschiebe)
        self.ckSonstigeAnlagen = QtGui.QCheckBox(self.layoutWidget2)
        self.ckSonstigeAnlagen.setObjectName(_fromUtf8("ckSonstigeAnlagen"))
        self.ckButtons.addButton(self.ckSonstigeAnlagen)
        self.verticalLayout_3.addWidget(self.ckSonstigeAnlagen)
        self.ckUeberflutungsflaechen = QtGui.QCheckBox(self.layoutWidget2)
        self.ckUeberflutungsflaechen.setObjectName(_fromUtf8("ckUeberflutungsflaechen"))
        self.ckButtons.addButton(self.ckUeberflutungsflaechen)
        self.verticalLayout_3.addWidget(self.ckUeberflutungsflaechen)
        self.toolBox.addItem(self.toolBoxPage3, _fromUtf8(""))
        self.toolBoxPage4 = QtGui.QWidget()
        self.toolBoxPage4.setGeometry(QtCore.QRect(0, 0, 359, 166))
        self.toolBoxPage4.setObjectName(_fromUtf8("toolBoxPage4"))
        self.layoutWidget3 = QtGui.QWidget(self.toolBoxPage4)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 20, 146, 92))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.ckKommunaleKlaeranlagen = QtGui.QCheckBox(self.layoutWidget3)
        self.ckKommunaleKlaeranlagen.setObjectName(_fromUtf8("ckKommunaleKlaeranlagen"))
        self.ckButtons.addButton(self.ckKommunaleKlaeranlagen)
        self.verticalLayout_4.addWidget(self.ckKommunaleKlaeranlagen)
        self.ckKleinklaeranlagen = QtGui.QCheckBox(self.layoutWidget3)
        self.ckKleinklaeranlagen.setObjectName(_fromUtf8("ckKleinklaeranlagen"))
        self.ckButtons.addButton(self.ckKleinklaeranlagen)
        self.verticalLayout_4.addWidget(self.ckKleinklaeranlagen)
        self.ckBetrieblicheKlaeranlagen = QtGui.QCheckBox(self.layoutWidget3)
        self.ckBetrieblicheKlaeranlagen.setObjectName(_fromUtf8("ckBetrieblicheKlaeranlagen"))
        self.ckButtons.addButton(self.ckBetrieblicheKlaeranlagen)
        self.verticalLayout_4.addWidget(self.ckBetrieblicheKlaeranlagen)
        self.ckOeffentlicheTankstellen = QtGui.QCheckBox(self.layoutWidget3)
        self.ckOeffentlicheTankstellen.setObjectName(_fromUtf8("ckOeffentlicheTankstellen"))
        self.ckButtons.addButton(self.ckOeffentlicheTankstellen)
        self.verticalLayout_4.addWidget(self.ckOeffentlicheTankstellen)
        self.toolBox.addItem(self.toolBoxPage4, _fromUtf8(""))
        self.toolBoxPage5 = QtGui.QWidget()
        self.toolBoxPage5.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.toolBoxPage5.setObjectName(_fromUtf8("toolBoxPage5"))
        self.layoutWidget4 = QtGui.QWidget(self.toolBoxPage5)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 0, 184, 140))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.ckNiederschlagmessstellen = QtGui.QCheckBox(self.layoutWidget4)
        self.ckNiederschlagmessstellen.setObjectName(_fromUtf8("ckNiederschlagmessstellen"))
        self.ckButtons.addButton(self.ckNiederschlagmessstellen)
        self.verticalLayout_5.addWidget(self.ckNiederschlagmessstellen)
        self.ckOberflaechenwassermessstellen = QtGui.QCheckBox(self.layoutWidget4)
        self.ckOberflaechenwassermessstellen.setObjectName(_fromUtf8("ckOberflaechenwassermessstellen"))
        self.ckButtons.addButton(self.ckOberflaechenwassermessstellen)
        self.verticalLayout_5.addWidget(self.ckOberflaechenwassermessstellen)
        self.ckGrundwassermessstellen = QtGui.QCheckBox(self.layoutWidget4)
        self.ckGrundwassermessstellen.setObjectName(_fromUtf8("ckGrundwassermessstellen"))
        self.ckButtons.addButton(self.ckGrundwassermessstellen)
        self.verticalLayout_5.addWidget(self.ckGrundwassermessstellen)
        self.ckGrundwasserfelder = QtGui.QCheckBox(self.layoutWidget4)
        self.ckGrundwasserfelder.setObjectName(_fromUtf8("ckGrundwasserfelder"))
        self.ckButtons.addButton(self.ckGrundwasserfelder)
        self.verticalLayout_5.addWidget(self.ckGrundwasserfelder)
        self.toolBox.addItem(self.toolBoxPage5, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayoutWidget = QtGui.QWidget(self.page_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 184, 101))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.ckEzFliessgewaesser = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.ckEzFliessgewaesser.setObjectName(_fromUtf8("ckEzFliessgewaesser"))
        self.ckButtons.addButton(self.ckEzFliessgewaesser)
        self.verticalLayout_8.addWidget(self.ckEzFliessgewaesser)
        self.ckEzOberflaechenwasserMesstellen = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.ckEzOberflaechenwasserMesstellen.setObjectName(_fromUtf8("ckEzOberflaechenwasserMesstellen"))
        self.ckButtons.addButton(self.ckEzOberflaechenwasserMesstellen)
        self.verticalLayout_8.addWidget(self.ckEzOberflaechenwasserMesstellen)
        self.ckEzQuellen = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.ckEzQuellen.setObjectName(_fromUtf8("ckEzQuellen"))
        self.ckButtons.addButton(self.ckEzQuellen)
        self.verticalLayout_8.addWidget(self.ckEzQuellen)
        self.ckEzWasserscheideRheinDonau = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.ckEzWasserscheideRheinDonau.setObjectName(_fromUtf8("ckEzWasserscheideRheinDonau"))
        self.ckButtons.addButton(self.ckEzWasserscheideRheinDonau)
        self.verticalLayout_8.addWidget(self.ckEzWasserscheideRheinDonau)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 359, 126))
        self.page.setObjectName(_fromUtf8("page"))
        self.layoutWidget5 = QtGui.QWidget(self.page)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 20, 325, 92))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.ckGewaessernetz2012Vlbg = QtGui.QCheckBox(self.layoutWidget5)
        self.ckGewaessernetz2012Vlbg.setObjectName(_fromUtf8("ckGewaessernetz2012Vlbg"))
        self.ckButtons.addButton(self.ckGewaessernetz2012Vlbg)
        self.verticalLayout_6.addWidget(self.ckGewaessernetz2012Vlbg)
        self.ckGewaessernetz2012Umgebung = QtGui.QCheckBox(self.layoutWidget5)
        self.ckGewaessernetz2012Umgebung.setObjectName(_fromUtf8("ckGewaessernetz2012Umgebung"))
        self.ckButtons.addButton(self.ckGewaessernetz2012Umgebung)
        self.verticalLayout_6.addWidget(self.ckGewaessernetz2012Umgebung)
        self.ckGewaessernetz2000Vlbg = QtGui.QCheckBox(self.layoutWidget5)
        self.ckGewaessernetz2000Vlbg.setEnabled(True)
        self.ckGewaessernetz2000Vlbg.setObjectName(_fromUtf8("ckGewaessernetz2000Vlbg"))
        self.ckButtons.addButton(self.ckGewaessernetz2000Vlbg)
        self.verticalLayout_6.addWidget(self.ckGewaessernetz2000Vlbg)
        self.ckGewaessernetz2000Umgebung = QtGui.QCheckBox(self.layoutWidget5)
        self.ckGewaessernetz2000Umgebung.setEnabled(True)
        self.ckGewaessernetz2000Umgebung.setObjectName(_fromUtf8("ckGewaessernetz2000Umgebung"))
        self.ckButtons.addButton(self.ckGewaessernetz2000Umgebung)
        self.verticalLayout_6.addWidget(self.ckGewaessernetz2000Umgebung)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 359, 166))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.layoutWidget6 = QtGui.QWidget(self.page_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(50, 10, 170, 116))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget6)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.ckDirekteinleitungen = QtGui.QCheckBox(self.layoutWidget6)
        self.ckDirekteinleitungen.setObjectName(_fromUtf8("ckDirekteinleitungen"))
        self.ckButtons.addButton(self.ckDirekteinleitungen)
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.ckDirekteinleitungen)
        self.ckKontinuumsunterbrechungen = QtGui.QCheckBox(self.layoutWidget6)
        self.ckKontinuumsunterbrechungen.setObjectName(_fromUtf8("ckKontinuumsunterbrechungen"))
        self.ckButtons.addButton(self.ckKontinuumsunterbrechungen)
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ckKontinuumsunterbrechungen)
        self.ckSohleBoeschung = QtGui.QCheckBox(self.layoutWidget6)
        self.ckSohleBoeschung.setObjectName(_fromUtf8("ckSohleBoeschung"))
        self.ckButtons.addButton(self.ckSohleBoeschung)
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.ckSohleBoeschung)
        self.ckStrukturzustand = QtGui.QCheckBox(self.layoutWidget6)
        self.ckStrukturzustand.setObjectName(_fromUtf8("ckStrukturzustand"))
        self.ckButtons.addButton(self.ckStrukturzustand)
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.ckStrukturzustand)
        self.ckUfervegetation = QtGui.QCheckBox(self.layoutWidget6)
        self.ckUfervegetation.setObjectName(_fromUtf8("ckUfervegetation"))
        self.ckButtons.addButton(self.ckUfervegetation)
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.ckUfervegetation)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 359, 166))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.btnSeen = QtGui.QPushButton(self.page_2)
        self.btnSeen.setGeometry(QtCore.QRect(280, 105, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.btnSeen.setFont(font)
        self.btnSeen.setObjectName(_fromUtf8("btnSeen"))
        self.layoutWidget7 = QtGui.QWidget(self.page_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(20, 3, 256, 141))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.ckBodenseeAlles = QtGui.QCheckBox(self.layoutWidget7)
        self.ckBodenseeAlles.setEnabled(True)
        self.ckBodenseeAlles.setObjectName(_fromUtf8("ckBodenseeAlles"))
        self.ckButtons.addButton(self.ckBodenseeAlles)
        self.verticalLayout_7.addWidget(self.ckBodenseeAlles)
        self.ckBodenseeWasserflaeche = QtGui.QCheckBox(self.layoutWidget7)
        self.ckBodenseeWasserflaeche.setEnabled(True)
        self.ckBodenseeWasserflaeche.setObjectName(_fromUtf8("ckBodenseeWasserflaeche"))
        self.ckButtons.addButton(self.ckBodenseeWasserflaeche)
        self.verticalLayout_7.addWidget(self.ckBodenseeWasserflaeche)
        self.ckBodensee25m = QtGui.QCheckBox(self.layoutWidget7)
        self.ckBodensee25m.setEnabled(True)
        self.ckBodensee25m.setObjectName(_fromUtf8("ckBodensee25m"))
        self.ckButtons.addButton(self.ckBodensee25m)
        self.verticalLayout_7.addWidget(self.ckBodensee25m)
        self.ckBodensee5m = QtGui.QCheckBox(self.layoutWidget7)
        self.ckBodensee5m.setEnabled(True)
        self.ckBodensee5m.setObjectName(_fromUtf8("ckBodensee5m"))
        self.ckButtons.addButton(self.ckBodensee5m)
        self.verticalLayout_7.addWidget(self.ckBodensee5m)
        self.ckBodenseeUferlinie = QtGui.QCheckBox(self.layoutWidget7)
        self.ckBodenseeUferlinie.setEnabled(True)
        self.ckBodenseeUferlinie.setObjectName(_fromUtf8("ckBodenseeUferlinie"))
        self.ckButtons.addButton(self.ckBodenseeUferlinie)
        self.verticalLayout_7.addWidget(self.ckBodenseeUferlinie)
        self.ckSeen = QtGui.QCheckBox(self.layoutWidget7)
        self.ckSeen.setEnabled(True)
        self.ckSeen.setObjectName(_fromUtf8("ckSeen"))
        self.ckButtons.addButton(self.ckSeen)
        self.verticalLayout_7.addWidget(self.ckSeen)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.pushButton = QtGui.QPushButton(frmWasser)
        self.pushButton.setGeometry(QtCore.QRect(30, 440, 101, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(frmWasser)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 440, 101, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))

        self.retranslateUi(frmWasser)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), frmWasser.abbrechen)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), frmWasser.datenladen)
        QtCore.QObject.connect(self.btnSeen, QtCore.SIGNAL(_fromUtf8("clicked()")), frmWasser.infobuttton)
        QtCore.QMetaObject.connectSlotsByName(frmWasser)

    def retranslateUi(self, frmWasser):
        frmWasser.setWindowTitle(QtGui.QApplication.translate("frmWasser", "Themenbereich Wasser", None, QtGui.QApplication.UnicodeUTF8))
        self.ckQuellen.setText(QtGui.QApplication.translate("frmWasser", "Quellen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckBrunnen.setText(QtGui.QApplication.translate("frmWasser", "Brunnen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckSchutzSchongebiete.setText(QtGui.QApplication.translate("frmWasser", "Schutz- und Schongebiete", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage1), QtGui.QApplication.translate("frmWasser", "Wasserversorgung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckGWWaermepumpen.setText(QtGui.QApplication.translate("frmWasser", "Grundwasserwärme-Pumpen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckErdwaermeanlagen.setText(QtGui.QApplication.translate("frmWasser", "Erdwärmeanlagen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckKuehlwasseranlagenGW.setText(QtGui.QApplication.translate("frmWasser", "Kühlwasseranlagen Grundwasser", None, QtGui.QApplication.UnicodeUTF8))
        self.ckKuehlwasseranlagenOG.setText(QtGui.QApplication.translate("frmWasser", "Kühlwasseranlagen Oberflächengewässer", None, QtGui.QApplication.UnicodeUTF8))
        self.ckWeitereAnlagen.setText(QtGui.QApplication.translate("frmWasser", "weitere Grundwasseranlagen (z.B. Versickerung)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage2), QtGui.QApplication.translate("frmWasser", "Thermische Nutzung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckKraftwerke.setText(QtGui.QApplication.translate("frmWasser", "Kraftwerke", None, QtGui.QApplication.UnicodeUTF8))
        self.ckSonstigeBetriebe.setText(QtGui.QApplication.translate("frmWasser", "Betriebe (z.B. Beschneiungsanlagen)", None, QtGui.QApplication.UnicodeUTF8))
        self.ckGeschiebe.setText(QtGui.QApplication.translate("frmWasser", "Geschieberückhalteeinrichtungen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckSonstigeAnlagen.setText(QtGui.QApplication.translate("frmWasser", " Anlagen an Gewässern (z.B. Entnahmen)", None, QtGui.QApplication.UnicodeUTF8))
        self.ckUeberflutungsflaechen.setText(QtGui.QApplication.translate("frmWasser", "Überflutungsflächen in Bearbeitung", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage3), QtGui.QApplication.translate("frmWasser", "Wassernutzung / Schutzwasserbau", None, QtGui.QApplication.UnicodeUTF8))
        self.ckKommunaleKlaeranlagen.setText(QtGui.QApplication.translate("frmWasser", "Kommunale Kläranlagen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckKleinklaeranlagen.setText(QtGui.QApplication.translate("frmWasser", "Kleinkläranalgen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckBetrieblicheKlaeranlagen.setText(QtGui.QApplication.translate("frmWasser", "Betriebliche Kläranlagen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckOeffentlicheTankstellen.setText(QtGui.QApplication.translate("frmWasser", "Öffentliche Tankstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage4), QtGui.QApplication.translate("frmWasser", "Abwasserentsorgung / Gefährdung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckNiederschlagmessstellen.setText(QtGui.QApplication.translate("frmWasser", "Niederschlag-Messstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckOberflaechenwassermessstellen.setText(QtGui.QApplication.translate("frmWasser", "Oberflächenwasser-Messstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckGrundwassermessstellen.setText(QtGui.QApplication.translate("frmWasser", "Grundwasser-Messstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckGrundwasserfelder.setText(QtGui.QApplication.translate("frmWasser", "Grundwasserfelder", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage5), QtGui.QApplication.translate("frmWasser", "Hydrographie", None, QtGui.QApplication.UnicodeUTF8))
        self.ckEzFliessgewaesser.setText(QtGui.QApplication.translate("frmWasser", "Fließgewässer", None, QtGui.QApplication.UnicodeUTF8))
        self.ckEzOberflaechenwasserMesstellen.setText(QtGui.QApplication.translate("frmWasser", "Oberflächenwasser - Messstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckEzQuellen.setText(QtGui.QApplication.translate("frmWasser", "Quellen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckEzWasserscheideRheinDonau.setText(QtGui.QApplication.translate("frmWasser", "Rhein Donau Wasserscheide", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), QtGui.QApplication.translate("frmWasser", "Einzugsgebiete", None, QtGui.QApplication.UnicodeUTF8))
        self.ckGewaessernetz2012Vlbg.setText(QtGui.QApplication.translate("frmWasser", "Gewässernetz 2012 Vorarlberg", None, QtGui.QApplication.UnicodeUTF8))
        self.ckGewaessernetz2012Umgebung.setText(QtGui.QApplication.translate("frmWasser", "Gewaessernetz 2012 Vorarlberg + Umgebung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckGewaessernetz2000Vlbg.setText(QtGui.QApplication.translate("frmWasser", "Gewässernetz 2000 Vorarlberg", None, QtGui.QApplication.UnicodeUTF8))
        self.ckGewaessernetz2000Umgebung.setText(QtGui.QApplication.translate("frmWasser", "Gewaessernetz 2000 Vorarlberg + Umgebung", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("frmWasser", "Fließgewässer Netz (FGW)", None, QtGui.QApplication.UnicodeUTF8))
        self.ckDirekteinleitungen.setText(QtGui.QApplication.translate("frmWasser", "Direkteinleitungen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckKontinuumsunterbrechungen.setText(QtGui.QApplication.translate("frmWasser", "Kontinuumsunterbrechungen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckSohleBoeschung.setText(QtGui.QApplication.translate("frmWasser", "Sohle Böschung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckStrukturzustand.setText(QtGui.QApplication.translate("frmWasser", "Strukturzustand", None, QtGui.QApplication.UnicodeUTF8))
        self.ckUfervegetation.setText(QtGui.QApplication.translate("frmWasser", "Ufervegetation", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("frmWasser", "Fließgewässer Strukturgüte", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSeen.setText(QtGui.QApplication.translate("frmWasser", "i", None, QtGui.QApplication.UnicodeUTF8))
        self.ckBodenseeAlles.setText(QtGui.QApplication.translate("frmWasser", "Bodensee -> alles", None, QtGui.QApplication.UnicodeUTF8))
        self.ckBodenseeWasserflaeche.setText(QtGui.QApplication.translate("frmWasser", "Bodensee -> nur Wasserfläche", None, QtGui.QApplication.UnicodeUTF8))
        self.ckBodensee25m.setText(QtGui.QApplication.translate("frmWasser", "Bodensee -> nur 25m Tiefenlinien", None, QtGui.QApplication.UnicodeUTF8))
        self.ckBodensee5m.setText(QtGui.QApplication.translate("frmWasser", "Bodensee -> nur 5m Tiefenlinien", None, QtGui.QApplication.UnicodeUTF8))
        self.ckBodenseeUferlinie.setText(QtGui.QApplication.translate("frmWasser", "Bodensee -> nur Uferlinie", None, QtGui.QApplication.UnicodeUTF8))
        self.ckSeen.setText(QtGui.QApplication.translate("frmWasser", "Andere Seen u. stehende Gewässer Vorarlbergs", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("frmWasser", "Stehende Gewässer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("frmWasser", "Themen Laden", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("frmWasser", "Schließen", None, QtGui.QApplication.UnicodeUTF8))

