# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_vermessung.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmVermessung(object):
    def setupUi(self, frmVermessung):
        frmVermessung.setObjectName("frmVermessung")
        frmVermessung.resize(578, 345)
        self.ButtonBlattschnitteOk = QtWidgets.QPushButton(frmVermessung)
        self.ButtonBlattschnitteOk.setEnabled(True)
        self.ButtonBlattschnitteOk.setGeometry(QtCore.QRect(120, 300, 111, 31))
        self.ButtonBlattschnitteOk.setObjectName("ButtonBlattschnitteOk")
        self.ButtonBlattschnitteCancel = QtWidgets.QPushButton(frmVermessung)
        self.ButtonBlattschnitteCancel.setEnabled(True)
        self.ButtonBlattschnitteCancel.setGeometry(QtCore.QRect(330, 300, 111, 31))
        self.ButtonBlattschnitteCancel.setObjectName("ButtonBlattschnitteCancel")
        self.progressBar = QtWidgets.QProgressBar(frmVermessung)
        self.progressBar.setGeometry(QtCore.QRect(20, 270, 551, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_3 = QtWidgets.QGroupBox(frmVermessung)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 311, 231))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.lstPolgem = QtWidgets.QListView(self.groupBox_3)
        self.lstPolgem.setGeometry(QtCore.QRect(10, 20, 131, 191))
        self.lstPolgem.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Austria))
        self.lstPolgem.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.lstPolgem.setTabKeyNavigation(False)
        self.lstPolgem.setObjectName("lstPolgem")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 20, 161, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ckPolygonpunkte = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckPolygonpunkte.setChecked(False)
        self.ckPolygonpunkte.setObjectName("ckPolygonpunkte")
        self.buttonGroup = QtWidgets.QButtonGroup(frmVermessung)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.setExclusive(False)
        self.buttonGroup.addButton(self.ckPolygonpunkte)
        self.verticalLayout.addWidget(self.ckPolygonpunkte)
        self.ckNivellement = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckNivellement.setChecked(False)
        self.ckNivellement.setObjectName("ckNivellement")
        self.buttonGroup.addButton(self.ckNivellement)
        self.verticalLayout.addWidget(self.ckNivellement)
        self.ckTriangulierungspunkte = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckTriangulierungspunkte.setChecked(False)
        self.ckTriangulierungspunkte.setObjectName("ckTriangulierungspunkte")
        self.buttonGroup.addButton(self.ckTriangulierungspunkte)
        self.verticalLayout.addWidget(self.ckTriangulierungspunkte)
        self.ckEinschaltpunkte = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckEinschaltpunkte.setChecked(False)
        self.ckEinschaltpunkte.setObjectName("ckEinschaltpunkte")
        self.buttonGroup.addButton(self.ckEinschaltpunkte)
        self.verticalLayout.addWidget(self.ckEinschaltpunkte)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(150, 160, 151, 61))
        self.groupBox.setObjectName("groupBox")
        self.btGmdChoice = QtWidgets.QPushButton(self.groupBox)
        self.btGmdChoice.setGeometry(QtCore.QRect(60, 20, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btGmdChoice.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btGmdChoice.setFont(font)
        self.btGmdChoice.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btGmdChoice.setCheckable(True)
        self.btGmdChoice.setChecked(False)
        self.btGmdChoice.setObjectName("btGmdChoice")
        self.groupBox.raise_()
        self.lstPolgem.raise_()
        self.layoutWidget.raise_()
        self.groupBox_4 = QtWidgets.QGroupBox(frmVermessung)
        self.groupBox_4.setGeometry(QtCore.QRect(330, 20, 221, 231))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 198, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ckIllwerke = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ckIllwerke.setChecked(False)
        self.ckIllwerke.setObjectName("ckIllwerke")
        self.buttonGroup.addButton(self.ckIllwerke)
        self.verticalLayout_2.addWidget(self.ckIllwerke)
        self.ckNaniv = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ckNaniv.setChecked(False)
        self.ckNaniv.setObjectName("ckNaniv")
        self.buttonGroup.addButton(self.ckNaniv)
        self.verticalLayout_2.addWidget(self.ckNaniv)
        self.ckOniv = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ckOniv.setChecked(False)
        self.ckOniv.setObjectName("ckOniv")
        self.buttonGroup.addButton(self.ckOniv)
        self.verticalLayout_2.addWidget(self.ckOniv)
        self.ckLva = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ckLva.setChecked(False)
        self.ckLva.setObjectName("ckLva")
        self.buttonGroup.addButton(self.ckLva)
        self.verticalLayout_2.addWidget(self.ckLva)
        self.ckUmrisspolygone = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ckUmrisspolygone.setChecked(False)
        self.ckUmrisspolygone.setObjectName("ckUmrisspolygone")
        self.buttonGroup.addButton(self.ckUmrisspolygone)
        self.verticalLayout_2.addWidget(self.ckUmrisspolygone)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 201, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btTopo = QtWidgets.QPushButton(self.groupBox_2)
        self.btTopo.setGeometry(QtCore.QRect(70, 20, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btTopo.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btTopo.setFont(font)
        self.btTopo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btTopo.setCheckable(True)
        self.btTopo.setChecked(False)
        self.btTopo.setObjectName("btTopo")

        self.retranslateUi(frmVermessung)
        self.ButtonBlattschnitteOk.clicked.connect(frmVermessung.accept)
        self.ButtonBlattschnitteCancel.clicked.connect(frmVermessung.closeEvent)
        self.btGmdChoice.clicked.connect(frmVermessung.gmd_choice_toggled)
        self.lstPolgem.clicked['QModelIndex'].connect(frmVermessung.auswahlaenderung)
        self.btTopo.clicked.connect(frmVermessung.topo_choice_toggled)
        self.ckUmrisspolygone.clicked.connect(frmVermessung.uncheck)
        QtCore.QMetaObject.connectSlotsByName(frmVermessung)

    def retranslateUi(self, frmVermessung):
        _translate = QtCore.QCoreApplication.translate
        frmVermessung.setWindowTitle(_translate("frmVermessung", "Vermessung"))
        self.ButtonBlattschnitteOk.setText(_translate("frmVermessung", "Themen laden"))
        self.ButtonBlattschnitteCancel.setText(_translate("frmVermessung", "Schließen"))
        self.groupBox_3.setTitle(_translate("frmVermessung", "Datenauswahl - Gemeinde"))
        self.ckPolygonpunkte.setText(_translate("frmVermessung", "VKW Polygonpunkte"))
        self.ckNivellement.setText(_translate("frmVermessung", "Nivellement (BEV)"))
        self.ckTriangulierungspunkte.setText(_translate("frmVermessung", "Triangulierungspunkte (BEV)"))
        self.ckEinschaltpunkte.setText(_translate("frmVermessung", "Einschaltpunkte (BEV)"))
        self.groupBox.setTitle(_translate("frmVermessung", "Gemeinde auswählen"))
        self.btGmdChoice.setText(_translate("frmVermessung", "+"))
        self.groupBox_4.setTitle(_translate("frmVermessung", "Datenauswahl - Landesfläche"))
        self.ckIllwerke.setText(_translate("frmVermessung", "Illwerke Flusssteine (Landesfläche)"))
        self.ckNaniv.setText(_translate("frmVermessung", "Nachgereihtes Nivellement"))
        self.ckOniv.setText(_translate("frmVermessung", "Ortsnivellements"))
        self.ckLva.setText(_translate("frmVermessung", "LVG Punkte (Landesfläche)"))
        self.ckUmrisspolygone.setText(_translate("frmVermessung", "LVG Vermessungen: Umrisspolygone"))
        self.groupBox_2.setTitle(_translate("frmVermessung", "LVA Punkte: Topografie abfragen"))
        self.btTopo.setText(_translate("frmVermessung", "+"))

