# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_luftbilder.ui'
#
# Created: Mon Jun 15 09:18:02 2015
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmLuftbilder(object):
    def setupUi(self, frmLuftbilder):
        frmLuftbilder.setObjectName(_fromUtf8("frmLuftbilder"))
        frmLuftbilder.resize(560, 489)
        self.groupBox = QtGui.QGroupBox(frmLuftbilder)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 261, 401))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pe198x = QtGui.QRadioButton(self.groupBox)
        self.pe198x.setGeometry(QtCore.QRect(10, 270, 143, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pe198x.setFont(font)
        self.pe198x.setObjectName(_fromUtf8("pe198x"))
        self.buttonGroup = QtGui.QButtonGroup(frmLuftbilder)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.pe198x)
        self.ir2001 = QtGui.QRadioButton(self.groupBox)
        self.ir2001.setGeometry(QtCore.QRect(10, 210, 163, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ir2001.setFont(font)
        self.ir2001.setObjectName(_fromUtf8("ir2001"))
        self.buttonGroup.addButton(self.ir2001)
        self.sw199x = QtGui.QRadioButton(self.groupBox)
        self.sw199x.setGeometry(QtCore.QRect(10, 240, 181, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sw199x.setFont(font)
        self.sw199x.setObjectName(_fromUtf8("sw199x"))
        self.buttonGroup.addButton(self.sw199x)
        self.sw195x = QtGui.QRadioButton(self.groupBox)
        self.sw195x.setGeometry(QtCore.QRect(10, 340, 142, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sw195x.setFont(font)
        self.sw195x.setObjectName(_fromUtf8("sw195x"))
        self.buttonGroup.addButton(self.sw195x)
        self.pe2001 = QtGui.QRadioButton(self.groupBox)
        self.pe2001.setGeometry(QtCore.QRect(10, 190, 163, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pe2001.setFont(font)
        self.pe2001.setObjectName(_fromUtf8("pe2001"))
        self.buttonGroup.addButton(self.pe2001)
        self.sw197x = QtGui.QRadioButton(self.groupBox)
        self.sw197x.setGeometry(QtCore.QRect(10, 320, 142, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sw197x.setFont(font)
        self.sw197x.setObjectName(_fromUtf8("sw197x"))
        self.buttonGroup.addButton(self.sw197x)
        self.ef2005 = QtGui.QRadioButton(self.groupBox)
        self.ef2005.setGeometry(QtCore.QRect(10, 160, 211, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ef2005.setFont(font)
        self.ef2005.setObjectName(_fromUtf8("ef2005"))
        self.buttonGroup.addButton(self.ef2005)
        self.ef2006 = QtGui.QRadioButton(self.groupBox)
        self.ef2006.setGeometry(QtCore.QRect(10, 130, 141, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ef2006.setFont(font)
        self.ef2006.setObjectName(_fromUtf8("ef2006"))
        self.buttonGroup.addButton(self.ef2006)
        self.ir2009 = QtGui.QRadioButton(self.groupBox)
        self.ir2009.setGeometry(QtCore.QRect(10, 100, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ir2009.setFont(font)
        self.ir2009.setObjectName(_fromUtf8("ir2009"))
        self.buttonGroup.addButton(self.ir2009)
        self.ef2009 = QtGui.QRadioButton(self.groupBox)
        self.ef2009.setGeometry(QtCore.QRect(10, 80, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ef2009.setFont(font)
        self.ef2009.setObjectName(_fromUtf8("ef2009"))
        self.buttonGroup.addButton(self.ef2009)
        self.ir198x = QtGui.QRadioButton(self.groupBox)
        self.ir198x.setGeometry(QtCore.QRect(10, 290, 143, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ir198x.setFont(font)
        self.ir198x.setObjectName(_fromUtf8("ir198x"))
        self.buttonGroup.addButton(self.ir198x)
        self.ir2012 = QtGui.QRadioButton(self.groupBox)
        self.ir2012.setGeometry(QtCore.QRect(10, 50, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ir2012.setFont(font)
        self.ir2012.setObjectName(_fromUtf8("ir2012"))
        self.buttonGroup.addButton(self.ir2012)
        self.ef2012 = QtGui.QRadioButton(self.groupBox)
        self.ef2012.setGeometry(QtCore.QRect(10, 30, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ef2012.setFont(font)
        self.ef2012.setObjectName(_fromUtf8("ef2012"))
        self.buttonGroup.addButton(self.ef2012)
        self.sw193x = QtGui.QRadioButton(self.groupBox)
        self.sw193x.setGeometry(QtCore.QRect(10, 360, 142, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sw193x.setFont(font)
        self.sw193x.setObjectName(_fromUtf8("sw193x"))
        self.buttonGroup.addButton(self.sw193x)
        self.groupBox_2 = QtGui.QGroupBox(frmLuftbilder)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 20, 261, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.wi2005 = QtGui.QRadioButton(self.groupBox_2)
        self.wi2005.setGeometry(QtCore.QRect(10, 150, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wi2005.setFont(font)
        self.wi2005.setObjectName(_fromUtf8("wi2005"))
        self.buttonGroup.addButton(self.wi2005)
        self.wi2009 = QtGui.QRadioButton(self.groupBox_2)
        self.wi2009.setGeometry(QtCore.QRect(10, 120, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wi2009.setFont(font)
        self.wi2009.setObjectName(_fromUtf8("wi2009"))
        self.buttonGroup.addButton(self.wi2009)
        self.wi2010 = QtGui.QRadioButton(self.groupBox_2)
        self.wi2010.setGeometry(QtCore.QRect(10, 60, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wi2010.setFont(font)
        self.wi2010.setObjectName(_fromUtf8("wi2010"))
        self.buttonGroup.addButton(self.wi2010)
        self.wi20xx = QtGui.QRadioButton(self.groupBox_2)
        self.wi20xx.setGeometry(QtCore.QRect(10, 90, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wi20xx.setFont(font)
        self.wi20xx.setObjectName(_fromUtf8("wi20xx"))
        self.buttonGroup.addButton(self.wi20xx)
        self.wi2015 = QtGui.QRadioButton(self.groupBox_2)
        self.wi2015.setGeometry(QtCore.QRect(10, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wi2015.setFont(font)
        self.wi2015.setObjectName(_fromUtf8("wi2015"))
        self.buttonGroup.addButton(self.wi2015)
        self.groupBox_3 = QtGui.QGroupBox(frmLuftbilder)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 210, 261, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.Orthophotos_Teilgebiete = QtGui.QRadioButton(self.groupBox_3)
        self.Orthophotos_Teilgebiete.setGeometry(QtCore.QRect(10, 60, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Orthophotos_Teilgebiete.setFont(font)
        self.Orthophotos_Teilgebiete.setObjectName(_fromUtf8("Orthophotos_Teilgebiete"))
        self.buttonGroup.addButton(self.Orthophotos_Teilgebiete)
        self.luftbilder_punkte = QtGui.QRadioButton(self.groupBox_3)
        self.luftbilder_punkte.setGeometry(QtCore.QRect(10, 30, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.luftbilder_punkte.setFont(font)
        self.luftbilder_punkte.setObjectName(_fromUtf8("luftbilder_punkte"))
        self.buttonGroup.addButton(self.luftbilder_punkte)
        self.ef2010 = QtGui.QRadioButton(self.groupBox_3)
        self.ef2010.setGeometry(QtCore.QRect(10, 90, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ef2010.setFont(font)
        self.ef2010.setObjectName(_fromUtf8("ef2010"))
        self.buttonGroup.addButton(self.ef2010)
        self.btnOK = QtGui.QPushButton(frmLuftbilder)
        self.btnOK.setGeometry(QtCore.QRect(154, 440, 101, 31))
        self.btnOK.setObjectName(_fromUtf8("btnOK"))
        self.btnCancel = QtGui.QPushButton(frmLuftbilder)
        self.btnCancel.setGeometry(QtCore.QRect(290, 440, 111, 31))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))

        self.retranslateUi(frmLuftbilder)
        QtCore.QObject.connect(self.btnCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), frmLuftbilder.abbrechen)
        QtCore.QObject.connect(self.btnOK, QtCore.SIGNAL(_fromUtf8("clicked()")), frmLuftbilder.laden)
        QtCore.QMetaObject.connectSlotsByName(frmLuftbilder)

    def retranslateUi(self, frmLuftbilder):
        frmLuftbilder.setWindowTitle(QtGui.QApplication.translate("frmLuftbilder", "Luftbilder", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmLuftbilder", "Vorarlberg großräumig", None, QtGui.QApplication.UnicodeUTF8))
        self.pe198x.setText(QtGui.QApplication.translate("frmLuftbilder", "PEF Orthophoto 198x", None, QtGui.QApplication.UnicodeUTF8))
        self.ir2001.setText(QtGui.QApplication.translate("frmLuftbilder", "IR Orthophoto 2001/02", None, QtGui.QApplication.UnicodeUTF8))
        self.sw199x.setText(QtGui.QApplication.translate("frmLuftbilder", "SW Orthophoto 1987/94/95", None, QtGui.QApplication.UnicodeUTF8))
        self.sw195x.setText(QtGui.QApplication.translate("frmLuftbilder", "SW Orthophoto 195x", None, QtGui.QApplication.UnicodeUTF8))
        self.pe2001.setText(QtGui.QApplication.translate("frmLuftbilder", "PEF Orthophoto 2001/02", None, QtGui.QApplication.UnicodeUTF8))
        self.sw197x.setText(QtGui.QApplication.translate("frmLuftbilder", "SW Orthophoto 197x", None, QtGui.QApplication.UnicodeUTF8))
        self.ef2005.setText(QtGui.QApplication.translate("frmLuftbilder", "EF Orthophoto Hochwasser 2005", None, QtGui.QApplication.UnicodeUTF8))
        self.ef2006.setText(QtGui.QApplication.translate("frmLuftbilder", "EF Orthophoto 2006", None, QtGui.QApplication.UnicodeUTF8))
        self.ir2009.setText(QtGui.QApplication.translate("frmLuftbilder", "IR Orthophoto 2009", None, QtGui.QApplication.UnicodeUTF8))
        self.ef2009.setText(QtGui.QApplication.translate("frmLuftbilder", "EF Orthophoto 2009", None, QtGui.QApplication.UnicodeUTF8))
        self.ir198x.setText(QtGui.QApplication.translate("frmLuftbilder", "IR Orthophoto 198x", None, QtGui.QApplication.UnicodeUTF8))
        self.ir2012.setText(QtGui.QApplication.translate("frmLuftbilder", "IR Orthophoto 2012", None, QtGui.QApplication.UnicodeUTF8))
        self.ef2012.setText(QtGui.QApplication.translate("frmLuftbilder", "EF Orthophoto 2012", None, QtGui.QApplication.UnicodeUTF8))
        self.sw193x.setText(QtGui.QApplication.translate("frmLuftbilder", "SW Orthophoto 193x", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmLuftbilder", "Winterbilder", None, QtGui.QApplication.UnicodeUTF8))
        self.wi2005.setText(QtGui.QApplication.translate("frmLuftbilder", "Winterorthophoto 2005", None, QtGui.QApplication.UnicodeUTF8))
        self.wi2009.setText(QtGui.QApplication.translate("frmLuftbilder", "Winterorthophoto 2009", None, QtGui.QApplication.UnicodeUTF8))
        self.wi2010.setText(QtGui.QApplication.translate("frmLuftbilder", "Winterorthophoto 2010", None, QtGui.QApplication.UnicodeUTF8))
        self.wi20xx.setText(QtGui.QApplication.translate("frmLuftbilder", "Winterorthophoto 2005 - 2011", None, QtGui.QApplication.UnicodeUTF8))
        self.wi2015.setText(QtGui.QApplication.translate("frmLuftbilder", "Winterorthophoto 2015", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("frmLuftbilder", "Sonstige Projekte", None, QtGui.QApplication.UnicodeUTF8))
        self.Orthophotos_Teilgebiete.setText(QtGui.QApplication.translate("frmLuftbilder", "Teilflächen", None, QtGui.QApplication.UnicodeUTF8))
        self.luftbilder_punkte.setText(QtGui.QApplication.translate("frmLuftbilder", "Übersicht der verfügbaren Luftbilder", None, QtGui.QApplication.UnicodeUTF8))
        self.ef2010.setText(QtGui.QApplication.translate("frmLuftbilder", "EF Orthophotos 2010 (Pfänder HW u.a.)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOK.setText(QtGui.QApplication.translate("frmLuftbilder", "Themen laden", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("frmLuftbilder", "Schließen", None, QtGui.QApplication.UnicodeUTF8))

