# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_geologie.ui'
#
# Created: Mon Aug 01 08:26:16 2016
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmGeologie(object):
    def setupUi(self, frmGeologie):
        frmGeologie.setObjectName(_fromUtf8("frmGeologie"))
        frmGeologie.resize(813, 638)
        self.ButtonGeolgoieOk = QtGui.QPushButton(frmGeologie)
        self.ButtonGeolgoieOk.setGeometry(QtCore.QRect(236, 588, 121, 23))
        self.ButtonGeolgoieOk.setObjectName(_fromUtf8("ButtonGeolgoieOk"))
        self.ButtonGeologieCancel = QtGui.QPushButton(frmGeologie)
        self.ButtonGeologieCancel.setGeometry(QtCore.QRect(436, 588, 121, 23))
        self.ButtonGeologieCancel.setObjectName(_fromUtf8("ButtonGeologieCancel"))
        self.tabWidget = QtGui.QTabWidget(frmGeologie)
        self.tabWidget.setGeometry(QtCore.QRect(32, 24, 757, 537))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(176, 40, 345, 449))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(12, 30, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkButtonsGroup = QtGui.QButtonGroup(frmGeologie)
        self.checkButtonsGroup.setObjectName(_fromUtf8("checkButtonsGroup"))
        self.checkButtonsGroup.addButton(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(12, 60, 272, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkButtonsGroup.addButton(self.checkBox_2)
        self.Button_Legend_Geologie_2007 = QtGui.QPushButton(self.groupBox)
        self.Button_Legend_Geologie_2007.setEnabled(True)
        self.Button_Legend_Geologie_2007.setGeometry(QtCore.QRect(280, 30, 20, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Legend_Geologie_2007.sizePolicy().hasHeightForWidth())
        self.Button_Legend_Geologie_2007.setSizePolicy(sizePolicy)
        self.Button_Legend_Geologie_2007.setBaseSize(QtCore.QSize(23, 23))
        self.Button_Legend_Geologie_2007.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/VogisMenu/icons/gui-rv.info.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Legend_Geologie_2007.setIcon(icon)
        self.Button_Legend_Geologie_2007.setObjectName(_fromUtf8("Button_Legend_Geologie_2007"))
        self.Button_Legend_Tektonisch_1998 = QtGui.QPushButton(self.groupBox)
        self.Button_Legend_Tektonisch_1998.setEnabled(True)
        self.Button_Legend_Tektonisch_1998.setGeometry(QtCore.QRect(280, 60, 20, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Legend_Tektonisch_1998.sizePolicy().hasHeightForWidth())
        self.Button_Legend_Tektonisch_1998.setSizePolicy(sizePolicy)
        self.Button_Legend_Tektonisch_1998.setBaseSize(QtCore.QSize(23, 23))
        self.Button_Legend_Tektonisch_1998.setText(_fromUtf8(""))
        self.Button_Legend_Tektonisch_1998.setIcon(icon)
        self.Button_Legend_Tektonisch_1998.setObjectName(_fromUtf8("Button_Legend_Tektonisch_1998"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(31, 90, 130, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.Profilschintt_Vorarlberg = QtGui.QPushButton(self.groupBox)
        self.Profilschintt_Vorarlberg.setEnabled(True)
        self.Profilschintt_Vorarlberg.setGeometry(QtCore.QRect(280, 92, 20, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profilschintt_Vorarlberg.sizePolicy().hasHeightForWidth())
        self.Profilschintt_Vorarlberg.setSizePolicy(sizePolicy)
        self.Profilschintt_Vorarlberg.setBaseSize(QtCore.QSize(23, 23))
        self.Profilschintt_Vorarlberg.setText(_fromUtf8(""))
        self.Profilschintt_Vorarlberg.setIcon(icon)
        self.Profilschintt_Vorarlberg.setObjectName(_fromUtf8("Profilschintt_Vorarlberg"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(12, 128, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkButtonsGroup.addButton(self.checkBox_3)
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(12, 176, 219, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkButtonsGroup.addButton(self.checkBox_5)
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(12, 200, 180, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkButtonsGroup.addButton(self.checkBox_6)
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(12, 224, 209, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkButtonsGroup.addButton(self.checkBox_7)
        self.checkBox_8 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_8.setEnabled(True)
        self.checkBox_8.setGeometry(QtCore.QRect(11, 296, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.checkButtonsGroup.addButton(self.checkBox_8)
        self.checkBox_9 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_9.setGeometry(QtCore.QRect(11, 320, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.checkButtonsGroup.addButton(self.checkBox_9)
        self.checkBox_23 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_23.setGeometry(QtCore.QRect(11, 356, 116, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_23.setFont(font)
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.checkButtonsGroup.addButton(self.checkBox_23)
        self.checkBox_25 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_25.setGeometry(QtCore.QRect(11, 392, 270, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_25.setFont(font)
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.checkButtonsGroup.addButton(self.checkBox_25)
        self.checkBox_24 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_24.setEnabled(True)
        self.checkBox_24.setGeometry(QtCore.QRect(11, 416, 309, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_24.setFont(font)
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.checkButtonsGroup.addButton(self.checkBox_24)
        self.checkBox_11 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_11.setGeometry(QtCore.QRect(12, 248, 269, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.checkButtonsGroup.addButton(self.checkBox_11)
        self.checkBox_19 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_19.setGeometry(QtCore.QRect(12, 152, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_19.setFont(font)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.checkButtonsGroup.addButton(self.checkBox_19)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(164, 28, 429, 461))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 30, 397, 417))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_4 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkButtonsGroup2 = QtGui.QButtonGroup(frmGeologie)
        self.checkButtonsGroup2.setObjectName(_fromUtf8("checkButtonsGroup2"))
        self.checkButtonsGroup2.addButton(self.checkBox_4)
        self.gridLayout.addWidget(self.checkBox_4, 0, 0, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.checkButtonsGroup2.addButton(self.checkBox_10)
        self.gridLayout.addWidget(self.checkBox_10, 1, 0, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.checkButtonsGroup2.addButton(self.checkBox_12)
        self.gridLayout.addWidget(self.checkBox_12, 2, 0, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.checkButtonsGroup2.addButton(self.checkBox_13)
        self.gridLayout.addWidget(self.checkBox_13, 3, 0, 1, 1)
        self.checkBox_14 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.checkButtonsGroup2.addButton(self.checkBox_14)
        self.gridLayout.addWidget(self.checkBox_14, 4, 0, 1, 1)
        self.checkBox_15 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.checkButtonsGroup2.addButton(self.checkBox_15)
        self.gridLayout.addWidget(self.checkBox_15, 5, 0, 1, 1)
        self.checkBox_16 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_16.setFont(font)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.checkButtonsGroup2.addButton(self.checkBox_16)
        self.gridLayout.addWidget(self.checkBox_16, 6, 0, 1, 1)
        self.checkBox_17 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_17.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_17.setFont(font)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.checkButtonsGroup2.addButton(self.checkBox_17)
        self.gridLayout.addWidget(self.checkBox_17, 7, 0, 1, 1)
        self.checkBox_18 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_18.setFont(font)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.checkButtonsGroup2.addButton(self.checkBox_18)
        self.gridLayout.addWidget(self.checkBox_18, 8, 0, 1, 1)
        self.checkBox_26 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_26.setFont(font)
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.checkButtonsGroup2.addButton(self.checkBox_26)
        self.gridLayout.addWidget(self.checkBox_26, 9, 0, 1, 1)
        self.checkBox_27 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_27.setFont(font)
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.checkButtonsGroup2.addButton(self.checkBox_27)
        self.gridLayout.addWidget(self.checkBox_27, 10, 0, 1, 1)
        self.checkBox_28 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_28.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_28.setFont(font)
        self.checkBox_28.setObjectName(_fromUtf8("checkBox_28"))
        self.checkButtonsGroup2.addButton(self.checkBox_28)
        self.gridLayout.addWidget(self.checkBox_28, 11, 0, 1, 1)
        self.checkBox_29 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_29.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_29.setFont(font)
        self.checkBox_29.setObjectName(_fromUtf8("checkBox_29"))
        self.checkButtonsGroup2.addButton(self.checkBox_29)
        self.gridLayout.addWidget(self.checkBox_29, 12, 0, 1, 1)
        self.checkBox_30 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_30.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_30.setFont(font)
        self.checkBox_30.setObjectName(_fromUtf8("checkBox_30"))
        self.checkButtonsGroup2.addButton(self.checkBox_30)
        self.gridLayout.addWidget(self.checkBox_30, 13, 0, 1, 1)
        self.checkBox_33 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_33.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_33.setFont(font)
        self.checkBox_33.setObjectName(_fromUtf8("checkBox_33"))
        self.checkButtonsGroup2.addButton(self.checkBox_33)
        self.gridLayout.addWidget(self.checkBox_33, 14, 0, 1, 1)
        self.checkBox_37 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_37.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_37.setFont(font)
        self.checkBox_37.setObjectName(_fromUtf8("checkBox_37"))
        self.checkButtonsGroup2.addButton(self.checkBox_37)
        self.gridLayout.addWidget(self.checkBox_37, 5, 1, 1, 1)
        self.checkBox_38 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_38.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_38.setFont(font)
        self.checkBox_38.setObjectName(_fromUtf8("checkBox_38"))
        self.checkButtonsGroup2.addButton(self.checkBox_38)
        self.gridLayout.addWidget(self.checkBox_38, 6, 1, 1, 1)
        self.checkBox_36 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_36.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_36.setFont(font)
        self.checkBox_36.setObjectName(_fromUtf8("checkBox_36"))
        self.checkButtonsGroup2.addButton(self.checkBox_36)
        self.gridLayout.addWidget(self.checkBox_36, 4, 1, 1, 1)
        self.checkBox_35 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_35.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_35.setFont(font)
        self.checkBox_35.setObjectName(_fromUtf8("checkBox_35"))
        self.checkButtonsGroup2.addButton(self.checkBox_35)
        self.gridLayout.addWidget(self.checkBox_35, 3, 1, 1, 1)
        self.checkBox_31 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_31.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_31.setFont(font)
        self.checkBox_31.setObjectName(_fromUtf8("checkBox_31"))
        self.checkButtonsGroup2.addButton(self.checkBox_31)
        self.gridLayout.addWidget(self.checkBox_31, 2, 1, 1, 1)
        self.checkBox_34 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_34.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_34.setFont(font)
        self.checkBox_34.setObjectName(_fromUtf8("checkBox_34"))
        self.checkButtonsGroup2.addButton(self.checkBox_34)
        self.gridLayout.addWidget(self.checkBox_34, 1, 1, 1, 1)
        self.checkBox_32 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_32.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_32.setFont(font)
        self.checkBox_32.setObjectName(_fromUtf8("checkBox_32"))
        self.checkButtonsGroup2.addButton(self.checkBox_32)
        self.gridLayout.addWidget(self.checkBox_32, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(180, 36, 345, 397))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.checkBox_20 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_20.setGeometry(QtCore.QRect(13, 40, 272, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_20.setFont(font)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.checkButtonsGroup3 = QtGui.QButtonGroup(frmGeologie)
        self.checkButtonsGroup3.setObjectName(_fromUtf8("checkButtonsGroup3"))
        self.checkButtonsGroup3.addButton(self.checkBox_20)
        self.checkBox_21 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_21.setGeometry(QtCore.QRect(13, 64, 165, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_21.setFont(font)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.checkButtonsGroup3.addButton(self.checkBox_21)
        self.checkBox_22 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_22.setGeometry(QtCore.QRect(13, 88, 219, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_22.setFont(font)
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.checkButtonsGroup3.addButton(self.checkBox_22)
        self.checkBox_39 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_39.setGeometry(QtCore.QRect(13, 112, 180, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_39.setFont(font)
        self.checkBox_39.setObjectName(_fromUtf8("checkBox_39"))
        self.checkButtonsGroup3.addButton(self.checkBox_39)
        self.checkBox_40 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_40.setGeometry(QtCore.QRect(13, 136, 209, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_40.setFont(font)
        self.checkBox_40.setObjectName(_fromUtf8("checkBox_40"))
        self.checkButtonsGroup3.addButton(self.checkBox_40)
        self.checkBox_41 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_41.setGeometry(QtCore.QRect(13, 160, 279, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_41.setFont(font)
        self.checkBox_41.setObjectName(_fromUtf8("checkBox_41"))
        self.checkButtonsGroup3.addButton(self.checkBox_41)
        self.checkBox_42 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_42.setEnabled(True)
        self.checkBox_42.setGeometry(QtCore.QRect(12, 184, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_42.setFont(font)
        self.checkBox_42.setObjectName(_fromUtf8("checkBox_42"))
        self.checkButtonsGroup3.addButton(self.checkBox_42)
        self.checkBox_43 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_43.setGeometry(QtCore.QRect(12, 208, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_43.setFont(font)
        self.checkBox_43.setObjectName(_fromUtf8("checkBox_43"))
        self.checkButtonsGroup3.addButton(self.checkBox_43)
        self.checkBox_44 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_44.setGeometry(QtCore.QRect(12, 232, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_44.setFont(font)
        self.checkBox_44.setObjectName(_fromUtf8("checkBox_44"))
        self.checkButtonsGroup3.addButton(self.checkBox_44)
        self.checkBox_45 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_45.setGeometry(QtCore.QRect(12, 256, 270, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_45.setFont(font)
        self.checkBox_45.setObjectName(_fromUtf8("checkBox_45"))
        self.checkButtonsGroup3.addButton(self.checkBox_45)
        self.checkBox_46 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_46.setEnabled(True)
        self.checkBox_46.setGeometry(QtCore.QRect(12, 280, 309, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_46.setFont(font)
        self.checkBox_46.setObjectName(_fromUtf8("checkBox_46"))
        self.checkButtonsGroup3.addButton(self.checkBox_46)
        self.checkBox_47 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_47.setEnabled(True)
        self.checkBox_47.setGeometry(QtCore.QRect(12, 304, 309, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_47.setFont(font)
        self.checkBox_47.setObjectName(_fromUtf8("checkBox_47"))
        self.checkButtonsGroup3.addButton(self.checkBox_47)
        self.checkBox_48 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_48.setEnabled(True)
        self.checkBox_48.setGeometry(QtCore.QRect(12, 328, 309, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_48.setFont(font)
        self.checkBox_48.setObjectName(_fromUtf8("checkBox_48"))
        self.checkButtonsGroup3.addButton(self.checkBox_48)
        self.checkBox_49 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_49.setEnabled(True)
        self.checkBox_49.setGeometry(QtCore.QRect(12, 352, 309, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_49.setFont(font)
        self.checkBox_49.setObjectName(_fromUtf8("checkBox_49"))
        self.checkButtonsGroup3.addButton(self.checkBox_49)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(12, 28, 169, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(208, 168, 213, 169))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.checkBox_55 = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_55.setGeometry(QtCore.QRect(13, 24, 257, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_55.setFont(font)
        self.checkBox_55.setObjectName(_fromUtf8("checkBox_55"))
        self.checkBox_56 = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_56.setGeometry(QtCore.QRect(13, 48, 165, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_56.setFont(font)
        self.checkBox_56.setObjectName(_fromUtf8("checkBox_56"))
        self.checkBox_57 = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_57.setGeometry(QtCore.QRect(13, 72, 219, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_57.setFont(font)
        self.checkBox_57.setObjectName(_fromUtf8("checkBox_57"))
        self.checkBox_58 = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_58.setGeometry(QtCore.QRect(13, 96, 180, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_58.setFont(font)
        self.checkBox_58.setObjectName(_fromUtf8("checkBox_58"))
        self.checkBox_59 = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_59.setGeometry(QtCore.QRect(13, 120, 209, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_59.setFont(font)
        self.checkBox_59.setObjectName(_fromUtf8("checkBox_59"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(13, 24, 133, 116))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_50 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_50.setFont(font)
        self.checkBox_50.setObjectName(_fromUtf8("checkBox_50"))
        self.checkButtonsGroup4 = QtGui.QButtonGroup(frmGeologie)
        self.checkButtonsGroup4.setObjectName(_fromUtf8("checkButtonsGroup4"))
        self.checkButtonsGroup4.addButton(self.checkBox_50)
        self.verticalLayout_3.addWidget(self.checkBox_50)
        self.checkBox_51 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_51.setFont(font)
        self.checkBox_51.setObjectName(_fromUtf8("checkBox_51"))
        self.checkButtonsGroup4.addButton(self.checkBox_51)
        self.verticalLayout_3.addWidget(self.checkBox_51)
        self.checkBox_52 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_52.setFont(font)
        self.checkBox_52.setObjectName(_fromUtf8("checkBox_52"))
        self.checkButtonsGroup4.addButton(self.checkBox_52)
        self.verticalLayout_3.addWidget(self.checkBox_52)
        self.checkBox_53 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_53.setFont(font)
        self.checkBox_53.setObjectName(_fromUtf8("checkBox_53"))
        self.checkButtonsGroup4.addButton(self.checkBox_53)
        self.verticalLayout_3.addWidget(self.checkBox_53)
        self.checkBox_54 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_54.setFont(font)
        self.checkBox_54.setObjectName(_fromUtf8("checkBox_54"))
        self.checkButtonsGroup4.addButton(self.checkBox_54)
        self.verticalLayout_3.addWidget(self.checkBox_54)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(364, 28, 137, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(208, 168, 213, 169))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.checkBox_65 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_65.setGeometry(QtCore.QRect(13, 24, 257, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_65.setFont(font)
        self.checkBox_65.setObjectName(_fromUtf8("checkBox_65"))
        self.checkBox_66 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_66.setGeometry(QtCore.QRect(13, 48, 165, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_66.setFont(font)
        self.checkBox_66.setObjectName(_fromUtf8("checkBox_66"))
        self.checkBox_67 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_67.setGeometry(QtCore.QRect(13, 72, 219, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_67.setFont(font)
        self.checkBox_67.setObjectName(_fromUtf8("checkBox_67"))
        self.checkBox_68 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_68.setGeometry(QtCore.QRect(13, 96, 180, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_68.setFont(font)
        self.checkBox_68.setObjectName(_fromUtf8("checkBox_68"))
        self.checkBox_69 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_69.setGeometry(QtCore.QRect(13, 120, 209, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_69.setFont(font)
        self.checkBox_69.setObjectName(_fromUtf8("checkBox_69"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget2.setGeometry(QtCore.QRect(13, 24, 99, 116))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBox_60 = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_60.setFont(font)
        self.checkBox_60.setObjectName(_fromUtf8("checkBox_60"))
        self.checkButtonsGroup4.addButton(self.checkBox_60)
        self.verticalLayout_4.addWidget(self.checkBox_60)
        self.checkBox_61 = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_61.setFont(font)
        self.checkBox_61.setObjectName(_fromUtf8("checkBox_61"))
        self.checkButtonsGroup4.addButton(self.checkBox_61)
        self.verticalLayout_4.addWidget(self.checkBox_61)
        self.checkBox_62 = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_62.setFont(font)
        self.checkBox_62.setObjectName(_fromUtf8("checkBox_62"))
        self.checkButtonsGroup4.addButton(self.checkBox_62)
        self.verticalLayout_4.addWidget(self.checkBox_62)
        self.checkBox_63 = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_63.setFont(font)
        self.checkBox_63.setObjectName(_fromUtf8("checkBox_63"))
        self.checkButtonsGroup4.addButton(self.checkBox_63)
        self.verticalLayout_4.addWidget(self.checkBox_63)
        self.checkBox_64 = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_64.setFont(font)
        self.checkBox_64.setObjectName(_fromUtf8("checkBox_64"))
        self.checkButtonsGroup4.addButton(self.checkBox_64)
        self.verticalLayout_4.addWidget(self.checkBox_64)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(192, 28, 153, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(208, 168, 213, 169))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.checkBox_75 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_75.setGeometry(QtCore.QRect(13, 24, 257, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_75.setFont(font)
        self.checkBox_75.setObjectName(_fromUtf8("checkBox_75"))
        self.checkBox_76 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_76.setGeometry(QtCore.QRect(13, 48, 165, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_76.setFont(font)
        self.checkBox_76.setObjectName(_fromUtf8("checkBox_76"))
        self.checkBox_77 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_77.setGeometry(QtCore.QRect(13, 72, 219, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_77.setFont(font)
        self.checkBox_77.setObjectName(_fromUtf8("checkBox_77"))
        self.checkBox_78 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_78.setGeometry(QtCore.QRect(13, 96, 180, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_78.setFont(font)
        self.checkBox_78.setObjectName(_fromUtf8("checkBox_78"))
        self.checkBox_79 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_79.setGeometry(QtCore.QRect(13, 120, 209, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_79.setFont(font)
        self.checkBox_79.setObjectName(_fromUtf8("checkBox_79"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_8)
        self.layoutWidget3.setGeometry(QtCore.QRect(13, 24, 94, 116))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.checkBox_70 = QtGui.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_70.setFont(font)
        self.checkBox_70.setObjectName(_fromUtf8("checkBox_70"))
        self.checkButtonsGroup4.addButton(self.checkBox_70)
        self.verticalLayout_5.addWidget(self.checkBox_70)
        self.checkBox_71 = QtGui.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_71.setFont(font)
        self.checkBox_71.setObjectName(_fromUtf8("checkBox_71"))
        self.checkButtonsGroup4.addButton(self.checkBox_71)
        self.verticalLayout_5.addWidget(self.checkBox_71)
        self.checkBox_72 = QtGui.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_72.setFont(font)
        self.checkBox_72.setObjectName(_fromUtf8("checkBox_72"))
        self.checkButtonsGroup4.addButton(self.checkBox_72)
        self.verticalLayout_5.addWidget(self.checkBox_72)
        self.checkBox_73 = QtGui.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_73.setFont(font)
        self.checkBox_73.setObjectName(_fromUtf8("checkBox_73"))
        self.checkButtonsGroup4.addButton(self.checkBox_73)
        self.verticalLayout_5.addWidget(self.checkBox_73)
        self.checkBox_74 = QtGui.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_74.setFont(font)
        self.checkBox_74.setObjectName(_fromUtf8("checkBox_74"))
        self.checkButtonsGroup4.addButton(self.checkBox_74)
        self.verticalLayout_5.addWidget(self.checkBox_74)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_10.setGeometry(QtCore.QRect(528, 28, 177, 345))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.layoutWidget4 = QtGui.QWidget(self.groupBox_10)
        self.layoutWidget4.setGeometry(QtCore.QRect(13, 24, 126, 308))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBox_80 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_80.setFont(font)
        self.checkBox_80.setObjectName(_fromUtf8("checkBox_80"))
        self.checkButtonsGroup4.addButton(self.checkBox_80)
        self.verticalLayout_2.addWidget(self.checkBox_80)
        self.checkBox_81 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_81.setFont(font)
        self.checkBox_81.setObjectName(_fromUtf8("checkBox_81"))
        self.checkButtonsGroup4.addButton(self.checkBox_81)
        self.verticalLayout_2.addWidget(self.checkBox_81)
        self.checkBox_82 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_82.setFont(font)
        self.checkBox_82.setObjectName(_fromUtf8("checkBox_82"))
        self.checkButtonsGroup4.addButton(self.checkBox_82)
        self.verticalLayout_2.addWidget(self.checkBox_82)
        self.checkBox_83 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_83.setFont(font)
        self.checkBox_83.setObjectName(_fromUtf8("checkBox_83"))
        self.checkButtonsGroup4.addButton(self.checkBox_83)
        self.verticalLayout_2.addWidget(self.checkBox_83)
        self.checkBox_84 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_84.setFont(font)
        self.checkBox_84.setObjectName(_fromUtf8("checkBox_84"))
        self.checkButtonsGroup4.addButton(self.checkBox_84)
        self.verticalLayout_2.addWidget(self.checkBox_84)
        self.checkBox_85 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_85.setFont(font)
        self.checkBox_85.setObjectName(_fromUtf8("checkBox_85"))
        self.checkButtonsGroup4.addButton(self.checkBox_85)
        self.verticalLayout_2.addWidget(self.checkBox_85)
        self.checkBox_86 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_86.setFont(font)
        self.checkBox_86.setObjectName(_fromUtf8("checkBox_86"))
        self.checkButtonsGroup4.addButton(self.checkBox_86)
        self.verticalLayout_2.addWidget(self.checkBox_86)
        self.checkBox_87 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_87.setFont(font)
        self.checkBox_87.setObjectName(_fromUtf8("checkBox_87"))
        self.checkButtonsGroup4.addButton(self.checkBox_87)
        self.verticalLayout_2.addWidget(self.checkBox_87)
        self.checkBox_88 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_88.setFont(font)
        self.checkBox_88.setObjectName(_fromUtf8("checkBox_88"))
        self.checkButtonsGroup4.addButton(self.checkBox_88)
        self.verticalLayout_2.addWidget(self.checkBox_88)
        self.checkBox_89 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_89.setFont(font)
        self.checkBox_89.setObjectName(_fromUtf8("checkBox_89"))
        self.checkButtonsGroup4.addButton(self.checkBox_89)
        self.verticalLayout_2.addWidget(self.checkBox_89)
        self.checkBox_90 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_90.setFont(font)
        self.checkBox_90.setObjectName(_fromUtf8("checkBox_90"))
        self.checkButtonsGroup4.addButton(self.checkBox_90)
        self.verticalLayout_2.addWidget(self.checkBox_90)
        self.checkBox_91 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_91.setFont(font)
        self.checkBox_91.setObjectName(_fromUtf8("checkBox_91"))
        self.checkButtonsGroup4.addButton(self.checkBox_91)
        self.verticalLayout_2.addWidget(self.checkBox_91)
        self.checkBox_92 = QtGui.QCheckBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_92.setFont(font)
        self.checkBox_92.setObjectName(_fromUtf8("checkBox_92"))
        self.checkButtonsGroup4.addButton(self.checkBox_92)
        self.verticalLayout_2.addWidget(self.checkBox_92)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_11.setGeometry(QtCore.QRect(72, 20, 549, 473))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.layoutWidget5 = QtGui.QWidget(self.groupBox_11)
        self.layoutWidget5.setGeometry(QtCore.QRect(356, 28, 164, 428))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.checkBox_122 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_122.setFont(font)
        self.checkBox_122.setObjectName(_fromUtf8("checkBox_122"))
        self.checkButtonsGroup5 = QtGui.QButtonGroup(frmGeologie)
        self.checkButtonsGroup5.setObjectName(_fromUtf8("checkButtonsGroup5"))
        self.checkButtonsGroup5.addButton(self.checkBox_122)
        self.verticalLayout_6.addWidget(self.checkBox_122)
        self.checkBox_123 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_123.setFont(font)
        self.checkBox_123.setObjectName(_fromUtf8("checkBox_123"))
        self.checkButtonsGroup5.addButton(self.checkBox_123)
        self.verticalLayout_6.addWidget(self.checkBox_123)
        self.checkBox_124 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_124.setFont(font)
        self.checkBox_124.setObjectName(_fromUtf8("checkBox_124"))
        self.checkButtonsGroup5.addButton(self.checkBox_124)
        self.verticalLayout_6.addWidget(self.checkBox_124)
        self.checkBox_125 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_125.setFont(font)
        self.checkBox_125.setObjectName(_fromUtf8("checkBox_125"))
        self.checkButtonsGroup5.addButton(self.checkBox_125)
        self.verticalLayout_6.addWidget(self.checkBox_125)
        self.checkBox_126 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_126.setFont(font)
        self.checkBox_126.setObjectName(_fromUtf8("checkBox_126"))
        self.checkButtonsGroup5.addButton(self.checkBox_126)
        self.verticalLayout_6.addWidget(self.checkBox_126)
        self.checkBox_127 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_127.setFont(font)
        self.checkBox_127.setObjectName(_fromUtf8("checkBox_127"))
        self.checkButtonsGroup5.addButton(self.checkBox_127)
        self.verticalLayout_6.addWidget(self.checkBox_127)
        self.checkBox_128 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_128.setFont(font)
        self.checkBox_128.setObjectName(_fromUtf8("checkBox_128"))
        self.checkButtonsGroup5.addButton(self.checkBox_128)
        self.verticalLayout_6.addWidget(self.checkBox_128)
        self.checkBox_129 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_129.setFont(font)
        self.checkBox_129.setObjectName(_fromUtf8("checkBox_129"))
        self.checkButtonsGroup5.addButton(self.checkBox_129)
        self.verticalLayout_6.addWidget(self.checkBox_129)
        self.checkBox_130 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_130.setFont(font)
        self.checkBox_130.setObjectName(_fromUtf8("checkBox_130"))
        self.checkButtonsGroup5.addButton(self.checkBox_130)
        self.verticalLayout_6.addWidget(self.checkBox_130)
        self.checkBox_131 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_131.setFont(font)
        self.checkBox_131.setObjectName(_fromUtf8("checkBox_131"))
        self.checkButtonsGroup5.addButton(self.checkBox_131)
        self.verticalLayout_6.addWidget(self.checkBox_131)
        self.checkBox_132 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_132.setFont(font)
        self.checkBox_132.setObjectName(_fromUtf8("checkBox_132"))
        self.checkButtonsGroup5.addButton(self.checkBox_132)
        self.verticalLayout_6.addWidget(self.checkBox_132)
        self.checkBox_133 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_133.setFont(font)
        self.checkBox_133.setObjectName(_fromUtf8("checkBox_133"))
        self.checkButtonsGroup5.addButton(self.checkBox_133)
        self.verticalLayout_6.addWidget(self.checkBox_133)
        self.checkBox_134 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_134.setFont(font)
        self.checkBox_134.setObjectName(_fromUtf8("checkBox_134"))
        self.checkButtonsGroup5.addButton(self.checkBox_134)
        self.verticalLayout_6.addWidget(self.checkBox_134)
        self.checkBox_135 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_135.setFont(font)
        self.checkBox_135.setObjectName(_fromUtf8("checkBox_135"))
        self.checkButtonsGroup5.addButton(self.checkBox_135)
        self.verticalLayout_6.addWidget(self.checkBox_135)
        self.checkBox_136 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_136.setFont(font)
        self.checkBox_136.setObjectName(_fromUtf8("checkBox_136"))
        self.checkButtonsGroup5.addButton(self.checkBox_136)
        self.verticalLayout_6.addWidget(self.checkBox_136)
        self.checkBox_137 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_137.setFont(font)
        self.checkBox_137.setObjectName(_fromUtf8("checkBox_137"))
        self.checkButtonsGroup5.addButton(self.checkBox_137)
        self.verticalLayout_6.addWidget(self.checkBox_137)
        self.checkBox_138 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_138.setFont(font)
        self.checkBox_138.setObjectName(_fromUtf8("checkBox_138"))
        self.checkButtonsGroup5.addButton(self.checkBox_138)
        self.verticalLayout_6.addWidget(self.checkBox_138)
        self.checkBox_139 = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_139.setFont(font)
        self.checkBox_139.setObjectName(_fromUtf8("checkBox_139"))
        self.checkButtonsGroup5.addButton(self.checkBox_139)
        self.verticalLayout_6.addWidget(self.checkBox_139)
        self.layoutWidget6 = QtGui.QWidget(self.groupBox_11)
        self.layoutWidget6.setGeometry(QtCore.QRect(40, 92, 200, 361))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.checkBox_108 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_108.setFont(font)
        self.checkBox_108.setObjectName(_fromUtf8("checkBox_108"))
        self.checkButtonsGroup5.addButton(self.checkBox_108)
        self.verticalLayout_7.addWidget(self.checkBox_108)
        self.checkBox_109 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_109.setFont(font)
        self.checkBox_109.setObjectName(_fromUtf8("checkBox_109"))
        self.checkButtonsGroup5.addButton(self.checkBox_109)
        self.verticalLayout_7.addWidget(self.checkBox_109)
        self.checkBox_110 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_110.setFont(font)
        self.checkBox_110.setObjectName(_fromUtf8("checkBox_110"))
        self.checkButtonsGroup5.addButton(self.checkBox_110)
        self.verticalLayout_7.addWidget(self.checkBox_110)
        self.checkBox_111 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_111.setFont(font)
        self.checkBox_111.setObjectName(_fromUtf8("checkBox_111"))
        self.checkButtonsGroup5.addButton(self.checkBox_111)
        self.verticalLayout_7.addWidget(self.checkBox_111)
        self.checkBox_112 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_112.setFont(font)
        self.checkBox_112.setObjectName(_fromUtf8("checkBox_112"))
        self.checkButtonsGroup5.addButton(self.checkBox_112)
        self.verticalLayout_7.addWidget(self.checkBox_112)
        self.checkBox_113 = QtGui.QCheckBox(self.layoutWidget6)
        self.checkBox_113.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_113.sizePolicy().hasHeightForWidth())
        self.checkBox_113.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_113.setFont(font)
        self.checkBox_113.setObjectName(_fromUtf8("checkBox_113"))
        self.checkButtonsGroup5.addButton(self.checkBox_113)
        self.verticalLayout_7.addWidget(self.checkBox_113)
        self.checkBox_114 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_114.setFont(font)
        self.checkBox_114.setObjectName(_fromUtf8("checkBox_114"))
        self.checkButtonsGroup5.addButton(self.checkBox_114)
        self.verticalLayout_7.addWidget(self.checkBox_114)
        self.checkBox_115 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_115.setFont(font)
        self.checkBox_115.setObjectName(_fromUtf8("checkBox_115"))
        self.checkButtonsGroup5.addButton(self.checkBox_115)
        self.verticalLayout_7.addWidget(self.checkBox_115)
        self.checkBox_116 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_116.setFont(font)
        self.checkBox_116.setObjectName(_fromUtf8("checkBox_116"))
        self.checkButtonsGroup5.addButton(self.checkBox_116)
        self.verticalLayout_7.addWidget(self.checkBox_116)
        self.checkBox_117 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_117.setFont(font)
        self.checkBox_117.setObjectName(_fromUtf8("checkBox_117"))
        self.checkButtonsGroup5.addButton(self.checkBox_117)
        self.verticalLayout_7.addWidget(self.checkBox_117)
        self.checkBox_118 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_118.setFont(font)
        self.checkBox_118.setObjectName(_fromUtf8("checkBox_118"))
        self.checkButtonsGroup5.addButton(self.checkBox_118)
        self.verticalLayout_7.addWidget(self.checkBox_118)
        self.checkBox_119 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_119.setFont(font)
        self.checkBox_119.setObjectName(_fromUtf8("checkBox_119"))
        self.checkButtonsGroup5.addButton(self.checkBox_119)
        self.verticalLayout_7.addWidget(self.checkBox_119)
        self.checkBox_120 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_120.setFont(font)
        self.checkBox_120.setObjectName(_fromUtf8("checkBox_120"))
        self.checkButtonsGroup5.addButton(self.checkBox_120)
        self.verticalLayout_7.addWidget(self.checkBox_120)
        self.checkBox_121 = QtGui.QCheckBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_121.setFont(font)
        self.checkBox_121.setObjectName(_fromUtf8("checkBox_121"))
        self.checkButtonsGroup5.addButton(self.checkBox_121)
        self.verticalLayout_7.addWidget(self.checkBox_121)
        self.Button_Legend_Geomorpg_Orig = QtGui.QPushButton(self.groupBox_11)
        self.Button_Legend_Geomorpg_Orig.setEnabled(True)
        self.Button_Legend_Geomorpg_Orig.setGeometry(QtCore.QRect(40, 28, 21, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Legend_Geomorpg_Orig.sizePolicy().hasHeightForWidth())
        self.Button_Legend_Geomorpg_Orig.setSizePolicy(sizePolicy)
        self.Button_Legend_Geomorpg_Orig.setBaseSize(QtCore.QSize(23, 23))
        self.Button_Legend_Geomorpg_Orig.setText(_fromUtf8(""))
        self.Button_Legend_Geomorpg_Orig.setIcon(icon)
        self.Button_Legend_Geomorpg_Orig.setObjectName(_fromUtf8("Button_Legend_Geomorpg_Orig"))
        self.label_3 = QtGui.QLabel(self.groupBox_11)
        self.label_3.setGeometry(QtCore.QRect(76, 56, 153, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_11)
        self.label_2.setGeometry(QtCore.QRect(76, 32, 153, 18))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Button_Legend_Geomorph_Deutsch = QtGui.QPushButton(self.groupBox_11)
        self.Button_Legend_Geomorph_Deutsch.setEnabled(True)
        self.Button_Legend_Geomorph_Deutsch.setGeometry(QtCore.QRect(40, 52, 21, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Legend_Geomorph_Deutsch.sizePolicy().hasHeightForWidth())
        self.Button_Legend_Geomorph_Deutsch.setSizePolicy(sizePolicy)
        self.Button_Legend_Geomorph_Deutsch.setBaseSize(QtCore.QSize(23, 23))
        self.Button_Legend_Geomorph_Deutsch.setText(_fromUtf8(""))
        self.Button_Legend_Geomorph_Deutsch.setIcon(icon)
        self.Button_Legend_Geomorph_Deutsch.setObjectName(_fromUtf8("Button_Legend_Geomorph_Deutsch"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))

        self.retranslateUi(frmGeologie)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.ButtonGeolgoieOk, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGeologie.accept)
        QtCore.QObject.connect(self.ButtonGeologieCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGeologie.close)
        QtCore.QObject.connect(self.Button_Legend_Geologie_2007, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGeologie.clicked)
        QtCore.QObject.connect(self.Button_Legend_Tektonisch_1998, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGeologie.clicked)
        QtCore.QObject.connect(self.Profilschintt_Vorarlberg, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGeologie.clicked)
        QtCore.QObject.connect(self.Button_Legend_Geomorpg_Orig, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGeologie.clicked)
        QtCore.QObject.connect(self.Button_Legend_Geomorph_Deutsch, QtCore.SIGNAL(_fromUtf8("clicked()")), frmGeologie.clicked)
        QtCore.QMetaObject.connectSlotsByName(frmGeologie)

    def retranslateUi(self, frmGeologie):
        frmGeologie.setWindowTitle(QtGui.QApplication.translate("frmGeologie", "Geologie", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonGeolgoieOk.setText(QtGui.QApplication.translate("frmGeologie", "Themen laden", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonGeologieCancel.setText(QtGui.QApplication.translate("frmGeologie", "Schließen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmGeologie", "Allgemein", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("frmGeologie", "Geologische Karte Vorarlberg (GBA, 2007)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("frmGeologie", "Geologische_Tektonische Karte (GBA, 1998)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmGeologie", "Profilschnitt Vorarlberg", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("frmGeologie", "Bohrprofile", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("frmGeologie", "Geologische Detailuntersuchungen", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("frmGeologie", "Geologische Karte (Richter)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("frmGeologie", "Geologie Rheintal (Starck, 1970)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("frmGeologie", "Gefahrenhinweiskarte (GBA, 2006)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("frmGeologie", "Georisken Montafon (Bertle, 1995)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_23.setText(QtGui.QApplication.translate("frmGeologie", "Geotop-Inventar", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_25.setText(QtGui.QApplication.translate("frmGeologie", "Grundwasser-Chemismus Rheintal (Starck)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_24.setText(QtGui.QApplication.translate("frmGeologie", "Grundwasser-Schichten_Linien Rheintal (nur VIIa)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("frmGeologie", "Historische Übersichtskarte (Schmidt 1839-1841)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_19.setText(QtGui.QApplication.translate("frmGeologie", "Ereigniskataster (Starck, 1974-2003)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("frmGeologie", "Allgemein", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmGeologie", "Geologische Gebietskarten", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("frmGeologie", "Übersichtskarten", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("frmGeologie", "Arlberggebiet (GBA, 1932)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("frmGeologie", "Bezau (GBA, Manuskript)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setText(QtGui.QApplication.translate("frmGeologie", "Bregenz (GBA, 1982)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_14.setText(QtGui.QApplication.translate("frmGeologie", "Dornbirn Nord (GBA, 1994)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_15.setText(QtGui.QApplication.translate("frmGeologie", "Dornbirn Süd (GBA, 1982)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_16.setText(QtGui.QApplication.translate("frmGeologie", "Flexenpass (Doert und Helmcke, 1975)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_17.setText(QtGui.QApplication.translate("frmGeologie", "Heiterwand (Tirol) (GBA, 1932)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_18.setText(QtGui.QApplication.translate("frmGeologie", "Klostertal (Helmcke, 1972)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_26.setText(QtGui.QApplication.translate("frmGeologie", "Klostertaler Alpen (GBA, 1932)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_27.setText(QtGui.QApplication.translate("frmGeologie", "Liechtenstein (RFL, 1985)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_28.setText(QtGui.QApplication.translate("frmGeologie", "Mittelberg (GBA, 1990)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_29.setText(QtGui.QApplication.translate("frmGeologie", "Parseiergruppe (Tirol)  (GBA, 1932)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_30.setText(QtGui.QApplication.translate("frmGeologie", "Partenen Ost (GBA, 1980)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_33.setText(QtGui.QApplication.translate("frmGeologie", "Partenen West (GBA, 1980)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_37.setText(QtGui.QApplication.translate("frmGeologie", "Walgau (GBA, 1967)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_38.setText(QtGui.QApplication.translate("frmGeologie", "Walsertal (Otte und Helmcke)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_36.setText(QtGui.QApplication.translate("frmGeologie", "Vorderwald (Muheim, 1934)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_35.setText(QtGui.QApplication.translate("frmGeologie", "Sulzberg (GBA, 1984)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_31.setText(QtGui.QApplication.translate("frmGeologie", "Stuben (GBA, 1937)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_34.setText(QtGui.QApplication.translate("frmGeologie", "Schönenbach", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_32.setText(QtGui.QApplication.translate("frmGeologie", "Rätikon (GBA)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("frmGeologie", "Geologische Gebietskarten", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("frmGeologie", "Geologische Detailkarten", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_20.setText(QtGui.QApplication.translate("frmGeologie", "Ausser Montafon (Bertha, 1978)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_21.setText(QtGui.QApplication.translate("frmGeologie", "Dalaas (Koehler, 1977)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_22.setText(QtGui.QApplication.translate("frmGeologie", "Davenna (Kasper, 1990)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_39.setText(QtGui.QApplication.translate("frmGeologie", "Firstkette (Golde, 1993)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_40.setText(QtGui.QApplication.translate("frmGeologie", "Gafadura (Post, 1996)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_41.setText(QtGui.QApplication.translate("frmGeologie", "Gargellen (Bertle, 1972)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_42.setText(QtGui.QApplication.translate("frmGeologie", "Gopfberg (Oberhauser M., 1993)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_43.setText(QtGui.QApplication.translate("frmGeologie", "Rätikon östlich (Steinacher, 2004)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_44.setText(QtGui.QApplication.translate("frmGeologie", "Rätikon östlich (Mayerl, 2005)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_45.setText(QtGui.QApplication.translate("frmGeologie", "Sibratsgfäll (Haak, 1995)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_46.setText(QtGui.QApplication.translate("frmGeologie", "Tschagguns - Mauren (Bertle, 1995)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_47.setText(QtGui.QApplication.translate("frmGeologie", "Tschöppa (Bertle, 1992)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_48.setText(QtGui.QApplication.translate("frmGeologie", "Winterstaude (Oberhauser)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_49.setText(QtGui.QApplication.translate("frmGeologie", "Winterstaude (Alexander)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("frmGeologie", "Geologische Detailkarten", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("frmGeologie", "Geologie", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("frmGeologie", "Geologie", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_55.setText(QtGui.QApplication.translate("frmGeologie", "Alberschwende", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_56.setText(QtGui.QApplication.translate("frmGeologie", "Au", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_57.setText(QtGui.QApplication.translate("frmGeologie", "Faschina", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_58.setText(QtGui.QApplication.translate("frmGeologie", "Hochtannberg/Arlberg", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_59.setText(QtGui.QApplication.translate("frmGeologie", "Sibratsgfaell", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_50.setText(QtGui.QApplication.translate("frmGeologie", "Alberschwende", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_51.setText(QtGui.QApplication.translate("frmGeologie", "Au", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_52.setText(QtGui.QApplication.translate("frmGeologie", "Faschina", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_53.setText(QtGui.QApplication.translate("frmGeologie", "Hochtannberg/Arlberg", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_54.setText(QtGui.QApplication.translate("frmGeologie", "Sibratsgfäll", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("frmGeologie", "Rutschung", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("frmGeologie", "Geologie", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_65.setText(QtGui.QApplication.translate("frmGeologie", "Alberschwende", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_66.setText(QtGui.QApplication.translate("frmGeologie", "Au", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_67.setText(QtGui.QApplication.translate("frmGeologie", "Faschina", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_68.setText(QtGui.QApplication.translate("frmGeologie", "Hochtannberg/Arlberg", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_69.setText(QtGui.QApplication.translate("frmGeologie", "Sibratsgfaell", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_60.setText(QtGui.QApplication.translate("frmGeologie", "Alberschwende", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_61.setText(QtGui.QApplication.translate("frmGeologie", "Faschina", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_62.setText(QtGui.QApplication.translate("frmGeologie", "Hochtannberg", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_63.setText(QtGui.QApplication.translate("frmGeologie", "Schoppernau", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_64.setText(QtGui.QApplication.translate("frmGeologie", "Walgau", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("frmGeologie", "Steinschlag", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("frmGeologie", "Geologie", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_75.setText(QtGui.QApplication.translate("frmGeologie", "Alberschwende", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_76.setText(QtGui.QApplication.translate("frmGeologie", "Au", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_77.setText(QtGui.QApplication.translate("frmGeologie", "Faschina", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_78.setText(QtGui.QApplication.translate("frmGeologie", "Hochtannberg/Arlberg", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_79.setText(QtGui.QApplication.translate("frmGeologie", "Sibratsgfaell", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_70.setText(QtGui.QApplication.translate("frmGeologie", "Hochtannberg", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_71.setText(QtGui.QApplication.translate("frmGeologie", "Klostertal", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_72.setText(QtGui.QApplication.translate("frmGeologie", "Mellau", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_73.setText(QtGui.QApplication.translate("frmGeologie", "Schröcken", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_74.setText(QtGui.QApplication.translate("frmGeologie", "Walgau", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("frmGeologie", "Geotechnik", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_80.setText(QtGui.QApplication.translate("frmGeologie", "Alberschwende Nord", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_81.setText(QtGui.QApplication.translate("frmGeologie", "Alberschwende Süd", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_82.setText(QtGui.QApplication.translate("frmGeologie", "Au", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_83.setText(QtGui.QApplication.translate("frmGeologie", "Flexenpass", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_84.setText(QtGui.QApplication.translate("frmGeologie", "Ippacherwald", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_85.setText(QtGui.QApplication.translate("frmGeologie", "Lech", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_86.setText(QtGui.QApplication.translate("frmGeologie", "Mellau", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_87.setText(QtGui.QApplication.translate("frmGeologie", "Schoppernau", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_88.setText(QtGui.QApplication.translate("frmGeologie", "Schröcken", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_89.setText(QtGui.QApplication.translate("frmGeologie", "Schwarzachtobel", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_90.setText(QtGui.QApplication.translate("frmGeologie", "Sibratsgfäll", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_91.setText(QtGui.QApplication.translate("frmGeologie", "Warth", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_92.setText(QtGui.QApplication.translate("frmGeologie", "Warth/Saloberkopf", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("frmGeologie", "Georisiko-Karten (AGK)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("frmGeologie", "Geomophologische Karten (Uni-Amsterdam)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_122.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Hopfreben:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_123.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Ludesch:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_124.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Marul:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_125.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Mellau:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_126.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Mellenspitze:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_127.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Mittleres Silbertal:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_128.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Nenzinger Himmel:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_129.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Rellstal-Golm:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_130.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Rellstal-Zimba:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_131.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Satteins:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_132.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Schnepfau:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_133.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Schnifis:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_134.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Schoppernau:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_135.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Schönenbach:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_136.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Silbertal:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_137.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Sonntag:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_138.setText(QtGui.QApplication.translate("frmGeologie", "Blatt St. Gallenkirch:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_139.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Zitterklapfen:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_108.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Au:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_109.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Bartholomäberg:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_110.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Bezau:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_111.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Bizau:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_112.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Brand-Nord:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_113.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Brand-Süd:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_114.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Damüls:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_115.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Damülser Mittagsspitze:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_116.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Diedamskopf:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_117.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Dunza-Tschengla:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_118.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Fundelkopf:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_119.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Gampberg:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_120.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Gurtis:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_121.setText(QtGui.QApplication.translate("frmGeologie", "Blatt Klaus-Weiler:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmGeologie", "Geomorph. Legende (Deutsch)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmGeologie", "Geomorph. Legende (Orginal)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("frmGeologie", "Geomorphologische Karten (Uni Amsterdam)", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
import resources_rc
