# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_verkehr.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmVerkehr(object):
    def setupUi(self, frmVerkehr):
        frmVerkehr.setObjectName("frmVerkehr")
        frmVerkehr.resize(410, 359)
        self.toolBox = QtWidgets.QToolBox(frmVerkehr)
        self.toolBox.setGeometry(QtCore.QRect(10, 0, 391, 271))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 391, 109))
        self.page.setObjectName("page")
        self.ckHauptstrassen = QtWidgets.QCheckBox(self.page)
        self.ckHauptstrassen.setGeometry(QtCore.QRect(30, 20, 281, 18))
        self.ckHauptstrassen.setObjectName("ckHauptstrassen")
        self.ckButtons = QtWidgets.QButtonGroup(frmVerkehr)
        self.ckButtons.setObjectName("ckButtons")
        self.ckButtons.addButton(self.ckHauptstrassen)
        self.ckGemeindestrassen = QtWidgets.QCheckBox(self.page)
        self.ckGemeindestrassen.setGeometry(QtCore.QRect(30, 50, 231, 18))
        self.ckGemeindestrassen.setToolTip("")
        self.ckGemeindestrassen.setStatusTip("")
        self.ckGemeindestrassen.setWhatsThis("")
        self.ckGemeindestrassen.setObjectName("ckGemeindestrassen")
        self.ckButtons.addButton(self.ckGemeindestrassen)
        self.toolBox.addItem(self.page, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.ckBeleuchtungsanlagen = QtWidgets.QCheckBox(self.page_6)
        self.ckBeleuchtungsanlagen.setGeometry(QtCore.QRect(30, 20, 281, 18))
        self.ckBeleuchtungsanlagen.setObjectName("ckBeleuchtungsanlagen")
        self.ckButtons.addButton(self.ckBeleuchtungsanlagen)
        self.toolBox.addItem(self.page_6, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 391, 109))
        self.page_5.setObjectName("page_5")
        self.ckOepnv_Verkehr = QtWidgets.QCheckBox(self.page_5)
        self.ckOepnv_Verkehr.setGeometry(QtCore.QRect(40, 30, 271, 18))
        self.ckOepnv_Verkehr.setObjectName("ckOepnv_Verkehr")
        self.ckButtons.addButton(self.ckOepnv_Verkehr)
        self.ckSeilbahn = QtWidgets.QCheckBox(self.page_5)
        self.ckSeilbahn.setGeometry(QtCore.QRect(40, 90, 271, 18))
        self.ckSeilbahn.setObjectName("ckSeilbahn")
        self.ckButtons.addButton(self.ckSeilbahn)
        self.ckHindernisse = QtWidgets.QCheckBox(self.page_5)
        self.ckHindernisse.setGeometry(QtCore.QRect(40, 120, 271, 18))
        self.ckHindernisse.setObjectName("ckHindernisse")
        self.ckButtons.addButton(self.ckHindernisse)
        self.ckBahn = QtWidgets.QCheckBox(self.page_5)
        self.ckBahn.setEnabled(True)
        self.ckBahn.setGeometry(QtCore.QRect(40, 0, 171, 18))
        self.ckBahn.setObjectName("ckBahn")
        self.ckButtons.addButton(self.ckBahn)
        self.ckOepnv_Qualitaet = QtWidgets.QCheckBox(self.page_5)
        self.ckOepnv_Qualitaet.setGeometry(QtCore.QRect(40, 60, 271, 18))
        self.ckOepnv_Qualitaet.setObjectName("ckOepnv_Qualitaet")
        self.ckButtons.addButton(self.ckOepnv_Qualitaet)
        self.toolBox.addItem(self.page_5, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 391, 109))
        self.page_2.setObjectName("page_2")
        self.ckForstweg = QtWidgets.QCheckBox(self.page_2)
        self.ckForstweg.setGeometry(QtCore.QRect(70, 28, 131, 20))
        self.ckForstweg.setObjectName("ckForstweg")
        self.ckButtons.addButton(self.ckForstweg)
        self.ckGueterweg = QtWidgets.QCheckBox(self.page_2)
        self.ckGueterweg.setEnabled(True)
        self.ckGueterweg.setGeometry(QtCore.QRect(70, 70, 71, 18))
        self.ckGueterweg.setObjectName("ckGueterweg")
        self.ckButtons.addButton(self.ckGueterweg)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 391, 109))
        self.page_3.setObjectName("page_3")
        self.ckWanderwege = QtWidgets.QCheckBox(self.page_3)
        self.ckWanderwege.setGeometry(QtCore.QRect(40, 20, 141, 18))
        self.ckWanderwege.setObjectName("ckWanderwege")
        self.ckButtons.addButton(self.ckWanderwege)
        self.ckWinterwanderwege = QtWidgets.QCheckBox(self.page_3)
        self.ckWinterwanderwege.setGeometry(QtCore.QRect(40, 60, 161, 18))
        self.ckWinterwanderwege.setObjectName("ckWinterwanderwege")
        self.ckButtons.addButton(self.ckWinterwanderwege)
        self.btnWegtafeln = QtWidgets.QPushButton(self.page_3)
        self.btnWegtafeln.setGeometry(QtCore.QRect(230, 20, 75, 23))
        self.btnWegtafeln.setObjectName("btnWegtafeln")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 391, 109))
        self.page_4.setObjectName("page_4")
        self.ckMountainbike = QtWidgets.QCheckBox(self.page_4)
        self.ckMountainbike.setGeometry(QtCore.QRect(60, 60, 141, 18))
        self.ckMountainbike.setObjectName("ckMountainbike")
        self.ckButtons.addButton(self.ckMountainbike)
        self.ckLandesradrouten = QtWidgets.QCheckBox(self.page_4)
        self.ckLandesradrouten.setGeometry(QtCore.QRect(60, 0, 141, 18))
        self.ckLandesradrouten.setObjectName("ckLandesradrouten")
        self.ckButtons.addButton(self.ckLandesradrouten)
        self.ckLrr_beschildert = QtWidgets.QCheckBox(self.page_4)
        self.ckLrr_beschildert.setGeometry(QtCore.QRect(60, 30, 171, 18))
        self.ckLrr_beschildert.setObjectName("ckLrr_beschildert")
        self.ckButtons.addButton(self.ckLrr_beschildert)
        self.ckRadschnellverbindungen = QtWidgets.QCheckBox(self.page_4)
        self.ckRadschnellverbindungen.setGeometry(QtCore.QRect(60, 90, 141, 18))
        self.ckRadschnellverbindungen.setObjectName("ckRadschnellverbindungen")
        self.ckButtons.addButton(self.ckRadschnellverbindungen)
        self.toolBox.addItem(self.page_4, "")
        self.btnRadAbbrechen = QtWidgets.QPushButton(frmVerkehr)
        self.btnRadAbbrechen.setGeometry(QtCore.QRect(250, 310, 91, 23))
        self.btnRadAbbrechen.setObjectName("btnRadAbbrechen")
        self.btnRadLaden = QtWidgets.QPushButton(frmVerkehr)
        self.btnRadLaden.setGeometry(QtCore.QRect(60, 310, 101, 23))
        self.btnRadLaden.setObjectName("btnRadLaden")
        self.line = QtWidgets.QFrame(frmVerkehr)
        self.line.setGeometry(QtCore.QRect(0, 280, 411, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(frmVerkehr)
        self.toolBox.setCurrentIndex(0)
        self.btnRadLaden.clicked.connect(frmVerkehr.lade_daten)
        self.btnRadAbbrechen.clicked.connect(frmVerkehr.abbrechen)
        self.btnWegtafeln.clicked.connect(frmVerkehr.suche_wegtafeln)
        QtCore.QMetaObject.connectSlotsByName(frmVerkehr)

    def retranslateUi(self, frmVerkehr):
        _translate = QtCore.QCoreApplication.translate
        frmVerkehr.setWindowTitle(_translate("frmVerkehr", "Verkehr, Transport, Tourismus"))
        self.ckHauptstrassen.setText(_translate("frmVerkehr", "Autobahn, Schnellstraßen, Landesstraßen"))
        self.ckGemeindestrassen.setText(_translate("frmVerkehr", "Örtliches Straßennetz (Gemeindestraßen)"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("frmVerkehr", "Strassen"))
        self.ckBeleuchtungsanlagen.setText(_translate("frmVerkehr", "Beleuchtungsanlagen"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("frmVerkehr", "Leitungskataster"))
        self.ckOepnv_Verkehr.setText(_translate("frmVerkehr", "Öffentlicher Personenverkehr (ÖPNV)"))
        self.ckSeilbahn.setText(_translate("frmVerkehr", "Seilbahnen und Aufstiegshilfen"))
        self.ckHindernisse.setText(_translate("frmVerkehr", "Flughindernisse"))
        self.ckBahn.setText(_translate("frmVerkehr", "Bahnlinien"))
        self.ckOepnv_Qualitaet.setText(_translate("frmVerkehr", "ÖPNV Bedienqualität"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("frmVerkehr", "Öffentlicher Verkehr, Seilbahnen, Flughindernisse"))
        self.ckForstweg.setText(_translate("frmVerkehr", "Forstwege"))
        self.ckGueterweg.setText(_translate("frmVerkehr", "Güterwege"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("frmVerkehr", "Forst- und Güterwege"))
        self.ckWanderwege.setText(_translate("frmVerkehr", "Wanderwege"))
        self.ckWinterwanderwege.setText(_translate("frmVerkehr", "Winterwanderwege"))
        self.btnWegtafeln.setText(_translate("frmVerkehr", "Wegtafeln"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("frmVerkehr", "Wanderwege"))
        self.ckMountainbike.setText(_translate("frmVerkehr", "Mountainbikerouten"))
        self.ckLandesradrouten.setText(_translate("frmVerkehr", "Landesradrouten"))
        self.ckLrr_beschildert.setText(_translate("frmVerkehr", "Landesradrouten beschildert"))
        self.ckRadschnellverbindungen.setText(_translate("frmVerkehr", "Radschnellverbindungen"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("frmVerkehr", "Radwege und Mountainbikerouten"))
        self.btnRadAbbrechen.setText(_translate("frmVerkehr", "Schließen"))
        self.btnRadLaden.setText(_translate("frmVerkehr", "Daten laden"))

