# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_luftbilder.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmLuftbilder(object):
    def setupUi(self, frmLuftbilder):
        frmLuftbilder.setObjectName("frmLuftbilder")
        frmLuftbilder.resize(560, 506)
        self.groupBox = QtWidgets.QGroupBox(frmLuftbilder)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 261, 471))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pe198x = QtWidgets.QRadioButton(self.groupBox)
        self.pe198x.setGeometry(QtCore.QRect(10, 340, 143, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pe198x.setFont(font)
        self.pe198x.setObjectName("pe198x")
        self.buttonGroup = QtWidgets.QButtonGroup(frmLuftbilder)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pe198x)
        self.ir2001 = QtWidgets.QRadioButton(self.groupBox)
        self.ir2001.setGeometry(QtCore.QRect(10, 260, 163, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ir2001.setFont(font)
        self.ir2001.setObjectName("ir2001")
        self.buttonGroup.addButton(self.ir2001)
        self.sw199x = QtWidgets.QRadioButton(self.groupBox)
        self.sw199x.setGeometry(QtCore.QRect(10, 390, 181, 18))
        self.sw199x.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sw199x.setFont(font)
        self.sw199x.setObjectName("sw199x")
        self.buttonGroup.addButton(self.sw199x)
        self.sw195x = QtWidgets.QRadioButton(self.groupBox)
        self.sw195x.setGeometry(QtCore.QRect(10, 430, 142, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sw195x.setFont(font)
        self.sw195x.setObjectName("sw195x")
        self.buttonGroup.addButton(self.sw195x)
        self.pe2001 = QtWidgets.QRadioButton(self.groupBox)
        self.pe2001.setGeometry(QtCore.QRect(10, 240, 163, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pe2001.setFont(font)
        self.pe2001.setObjectName("pe2001")
        self.buttonGroup.addButton(self.pe2001)
        self.sw197x = QtWidgets.QRadioButton(self.groupBox)
        self.sw197x.setGeometry(QtCore.QRect(10, 410, 142, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sw197x.setFont(font)
        self.sw197x.setObjectName("sw197x")
        self.buttonGroup.addButton(self.sw197x)
        self.ef2005 = QtWidgets.QRadioButton(self.groupBox)
        self.ef2005.setGeometry(QtCore.QRect(10, 210, 211, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ef2005.setFont(font)
        self.ef2005.setObjectName("ef2005")
        self.buttonGroup.addButton(self.ef2005)
        self.ef2006 = QtWidgets.QRadioButton(self.groupBox)
        self.ef2006.setGeometry(QtCore.QRect(10, 180, 141, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ef2006.setFont(font)
        self.ef2006.setObjectName("ef2006")
        self.buttonGroup.addButton(self.ef2006)
        self.ir2009 = QtWidgets.QRadioButton(self.groupBox)
        self.ir2009.setGeometry(QtCore.QRect(10, 150, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ir2009.setFont(font)
        self.ir2009.setObjectName("ir2009")
        self.buttonGroup.addButton(self.ir2009)
        self.ef2009 = QtWidgets.QRadioButton(self.groupBox)
        self.ef2009.setGeometry(QtCore.QRect(10, 130, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ef2009.setFont(font)
        self.ef2009.setObjectName("ef2009")
        self.buttonGroup.addButton(self.ef2009)
        self.ir198x = QtWidgets.QRadioButton(self.groupBox)
        self.ir198x.setGeometry(QtCore.QRect(10, 360, 143, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ir198x.setFont(font)
        self.ir198x.setObjectName("ir198x")
        self.buttonGroup.addButton(self.ir198x)
        self.ir2012 = QtWidgets.QRadioButton(self.groupBox)
        self.ir2012.setGeometry(QtCore.QRect(10, 100, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ir2012.setFont(font)
        self.ir2012.setObjectName("ir2012")
        self.buttonGroup.addButton(self.ir2012)
        self.ef2012 = QtWidgets.QRadioButton(self.groupBox)
        self.ef2012.setGeometry(QtCore.QRect(10, 80, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ef2012.setFont(font)
        self.ef2012.setObjectName("ef2012")
        self.buttonGroup.addButton(self.ef2012)
        self.sw193x = QtWidgets.QRadioButton(self.groupBox)
        self.sw193x.setGeometry(QtCore.QRect(10, 450, 142, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sw193x.setFont(font)
        self.sw193x.setObjectName("sw193x")
        self.buttonGroup.addButton(self.sw193x)
        self.ef2015 = QtWidgets.QRadioButton(self.groupBox)
        self.ef2015.setGeometry(QtCore.QRect(10, 30, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ef2015.setFont(font)
        self.ef2015.setObjectName("ef2015")
        self.buttonGroup.addButton(self.ef2015)
        self.ir2015 = QtWidgets.QRadioButton(self.groupBox)
        self.ir2015.setGeometry(QtCore.QRect(10, 50, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ir2015.setFont(font)
        self.ir2015.setObjectName("ir2015")
        self.buttonGroup.addButton(self.ir2015)
        self.pe199x = QtWidgets.QRadioButton(self.groupBox)
        self.pe199x.setGeometry(QtCore.QRect(10, 288, 143, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pe199x.setFont(font)
        self.pe199x.setObjectName("pe199x")
        self.buttonGroup.addButton(self.pe199x)
        self.ir199x = QtWidgets.QRadioButton(self.groupBox)
        self.ir199x.setGeometry(QtCore.QRect(10, 308, 143, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ir199x.setFont(font)
        self.ir199x.setObjectName("ir199x")
        self.buttonGroup.addButton(self.ir199x)
        self.groupBox_2 = QtWidgets.QGroupBox(frmLuftbilder)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 20, 261, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.wi2005 = QtWidgets.QRadioButton(self.groupBox_2)
        self.wi2005.setGeometry(QtCore.QRect(10, 150, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.wi2005.setFont(font)
        self.wi2005.setObjectName("wi2005")
        self.buttonGroup.addButton(self.wi2005)
        self.wi2009 = QtWidgets.QRadioButton(self.groupBox_2)
        self.wi2009.setGeometry(QtCore.QRect(10, 120, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.wi2009.setFont(font)
        self.wi2009.setObjectName("wi2009")
        self.buttonGroup.addButton(self.wi2009)
        self.wi2010 = QtWidgets.QRadioButton(self.groupBox_2)
        self.wi2010.setGeometry(QtCore.QRect(10, 60, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.wi2010.setFont(font)
        self.wi2010.setObjectName("wi2010")
        self.buttonGroup.addButton(self.wi2010)
        self.wi20xx = QtWidgets.QRadioButton(self.groupBox_2)
        self.wi20xx.setGeometry(QtCore.QRect(10, 90, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.wi20xx.setFont(font)
        self.wi20xx.setObjectName("wi20xx")
        self.buttonGroup.addButton(self.wi20xx)
        self.wi2015 = QtWidgets.QRadioButton(self.groupBox_2)
        self.wi2015.setGeometry(QtCore.QRect(10, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.wi2015.setFont(font)
        self.wi2015.setObjectName("wi2015")
        self.buttonGroup.addButton(self.wi2015)
        self.groupBox_3 = QtWidgets.QGroupBox(frmLuftbilder)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 210, 261, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.Orthophotos_Teilgebiete = QtWidgets.QRadioButton(self.groupBox_3)
        self.Orthophotos_Teilgebiete.setGeometry(QtCore.QRect(10, 60, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Orthophotos_Teilgebiete.setFont(font)
        self.Orthophotos_Teilgebiete.setObjectName("Orthophotos_Teilgebiete")
        self.buttonGroup.addButton(self.Orthophotos_Teilgebiete)
        self.luftbilder_punkte = QtWidgets.QRadioButton(self.groupBox_3)
        self.luftbilder_punkte.setGeometry(QtCore.QRect(10, 30, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.luftbilder_punkte.setFont(font)
        self.luftbilder_punkte.setObjectName("luftbilder_punkte")
        self.buttonGroup.addButton(self.luftbilder_punkte)
        self.ef2010 = QtWidgets.QRadioButton(self.groupBox_3)
        self.ef2010.setGeometry(QtCore.QRect(10, 90, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ef2010.setFont(font)
        self.ef2010.setObjectName("ef2010")
        self.buttonGroup.addButton(self.ef2010)
        self.btnOK = QtWidgets.QPushButton(frmLuftbilder)
        self.btnOK.setGeometry(QtCore.QRect(290, 460, 101, 31))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(frmLuftbilder)
        self.btnCancel.setGeometry(QtCore.QRect(410, 460, 111, 31))
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(frmLuftbilder)
        self.btnCancel.clicked.connect(frmLuftbilder.abbrechen)
        self.btnOK.clicked.connect(frmLuftbilder.laden)
        QtCore.QMetaObject.connectSlotsByName(frmLuftbilder)

    def retranslateUi(self, frmLuftbilder):
        _translate = QtCore.QCoreApplication.translate
        frmLuftbilder.setWindowTitle(_translate("frmLuftbilder", "Luftbilder"))
        self.groupBox.setTitle(_translate("frmLuftbilder", "Vorarlberg großräumig"))
        self.pe198x.setText(_translate("frmLuftbilder", "PEF Orthophoto 198x"))
        self.ir2001.setText(_translate("frmLuftbilder", "IR Orthophoto 2001/02"))
        self.sw199x.setText(_translate("frmLuftbilder", "SW Orthophoto 1987/94/95"))
        self.sw195x.setText(_translate("frmLuftbilder", "SW Orthophoto 195x"))
        self.pe2001.setText(_translate("frmLuftbilder", "PEF Orthophoto 2001/02"))
        self.sw197x.setText(_translate("frmLuftbilder", "SW Orthophoto 197x"))
        self.ef2005.setText(_translate("frmLuftbilder", "EF Orthophoto Hochwasser 2005"))
        self.ef2006.setText(_translate("frmLuftbilder", "EF Orthophoto 2006"))
        self.ir2009.setText(_translate("frmLuftbilder", "IR Orthophoto 2009"))
        self.ef2009.setText(_translate("frmLuftbilder", "EF Orthophoto 2009"))
        self.ir198x.setText(_translate("frmLuftbilder", "IR Orthophoto 198x"))
        self.ir2012.setText(_translate("frmLuftbilder", "IR Orthophoto 2012"))
        self.ef2012.setText(_translate("frmLuftbilder", "EF Orthophoto 2012"))
        self.sw193x.setText(_translate("frmLuftbilder", "SW Orthophoto 193x"))
        self.ef2015.setText(_translate("frmLuftbilder", "EF Orthophoto 2015"))
        self.ir2015.setText(_translate("frmLuftbilder", "IR Orthophoto 2015"))
        self.pe199x.setText(_translate("frmLuftbilder", "PEF Orthophoto 199x"))
        self.ir199x.setText(_translate("frmLuftbilder", "IR Orthophoto 199x"))
        self.groupBox_2.setTitle(_translate("frmLuftbilder", "Winterbilder"))
        self.wi2005.setText(_translate("frmLuftbilder", "Winterorthophoto 2005"))
        self.wi2009.setText(_translate("frmLuftbilder", "Winterorthophoto 2009"))
        self.wi2010.setText(_translate("frmLuftbilder", "Winterorthophoto 2010"))
        self.wi20xx.setText(_translate("frmLuftbilder", "Winterorthophoto 2005 - 2011"))
        self.wi2015.setText(_translate("frmLuftbilder", "Winterorthophoto 2015"))
        self.groupBox_3.setTitle(_translate("frmLuftbilder", "Sonstige Projekte"))
        self.Orthophotos_Teilgebiete.setText(_translate("frmLuftbilder", "Teilflächen"))
        self.luftbilder_punkte.setText(_translate("frmLuftbilder", "Übersicht der verfügbaren Luftbilder"))
        self.ef2010.setText(_translate("frmLuftbilder", "EF Orthophotos 2010 (Pfänder HW u.a.)"))
        self.btnOK.setText(_translate("frmLuftbilder", "Themen laden"))
        self.btnCancel.setText(_translate("frmLuftbilder", "Schließen"))

