# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_hoehenmodell_pg.ui'
#
# Created: Wed Feb 22 13:30:54 2017
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmHoehenmodell(object):
    def setupUi(self, frmHoehenmodell):
        frmHoehenmodell.setObjectName(_fromUtf8("frmHoehenmodell"))
        frmHoehenmodell.resize(326, 705)
        self.btnAbbrechen = QtGui.QPushButton(frmHoehenmodell)
        self.btnAbbrechen.setGeometry(QtCore.QRect(170, 660, 81, 31))
        self.btnAbbrechen.setObjectName(_fromUtf8("btnAbbrechen"))
        self.btnLaden = QtGui.QPushButton(frmHoehenmodell)
        self.btnLaden.setGeometry(QtCore.QRect(50, 660, 81, 31))
        self.btnLaden.setObjectName(_fromUtf8("btnLaden"))
        self.toolBox = QtGui.QToolBox(frmHoehenmodell)
        self.toolBox.setGeometry(QtCore.QRect(10, 20, 311, 451))
        self.toolBox.setFrameShape(QtGui.QFrame.Panel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 309, 395))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.groupBox_8 = QtGui.QGroupBox(self.page_2)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 20, 261, 291))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.layoutWidget_5 = QtGui.QWidget(self.groupBox_8)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 27, 241, 251))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.ckBLaserIsolinien_11 = QtGui.QCheckBox(self.layoutWidget_5)
        self.ckBLaserIsolinien_11.setChecked(False)
        self.ckBLaserIsolinien_11.setObjectName(_fromUtf8("ckBLaserIsolinien_11"))
        self.ckButtons = QtGui.QButtonGroup(frmHoehenmodell)
        self.ckButtons.setObjectName(_fromUtf8("ckButtons"))
        self.ckButtons.addButton(self.ckBLaserIsolinien_11)
        self.verticalLayout_7.addWidget(self.ckBLaserIsolinien_11)
        self.ckBLaserIsolinien_04 = QtGui.QCheckBox(self.layoutWidget_5)
        self.ckBLaserIsolinien_04.setChecked(False)
        self.ckBLaserIsolinien_04.setObjectName(_fromUtf8("ckBLaserIsolinien_04"))
        self.ckButtons.addButton(self.ckBLaserIsolinien_04)
        self.verticalLayout_7.addWidget(self.ckBLaserIsolinien_04)
        self.ckB5LaserIsolinien = QtGui.QCheckBox(self.layoutWidget_5)
        self.ckB5LaserIsolinien.setCheckable(True)
        self.ckB5LaserIsolinien.setChecked(False)
        self.ckB5LaserIsolinien.setObjectName(_fromUtf8("ckB5LaserIsolinien"))
        self.ckButtons.addButton(self.ckB5LaserIsolinien)
        self.verticalLayout_7.addWidget(self.ckB5LaserIsolinien)
        self.ckOEKIsolinien = QtGui.QCheckBox(self.layoutWidget_5)
        self.ckOEKIsolinien.setCheckable(True)
        self.ckOEKIsolinien.setChecked(False)
        self.ckOEKIsolinien.setObjectName(_fromUtf8("ckOEKIsolinien"))
        self.ckButtons.addButton(self.ckOEKIsolinien)
        self.verticalLayout_7.addWidget(self.ckOEKIsolinien)
        self.ckUMGIsolinien = QtGui.QCheckBox(self.layoutWidget_5)
        self.ckUMGIsolinien.setCheckable(True)
        self.ckUMGIsolinien.setChecked(False)
        self.ckUMGIsolinien.setObjectName(_fromUtf8("ckUMGIsolinien"))
        self.ckButtons.addButton(self.ckUMGIsolinien)
        self.verticalLayout_7.addWidget(self.ckUMGIsolinien)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 309, 395))
        self.page.setObjectName(_fromUtf8("page"))
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 291, 71))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 297, 52))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ckVBEVumgebung = QtGui.QCheckBox(self.layoutWidget)
        self.ckVBEVumgebung.setAutoExclusive(True)
        self.ckVBEVumgebung.setObjectName(_fromUtf8("ckVBEVumgebung"))
        self.ckButtons.addButton(self.ckVBEVumgebung)
        self.verticalLayout.addWidget(self.ckVBEVumgebung)
        self.ckHSZentraleuropa = QtGui.QCheckBox(self.layoutWidget)
        self.ckHSZentraleuropa.setAutoExclusive(True)
        self.ckHSZentraleuropa.setObjectName(_fromUtf8("ckHSZentraleuropa"))
        self.ckButtons.addButton(self.ckHSZentraleuropa)
        self.verticalLayout.addWidget(self.ckHSZentraleuropa)
        self.toolBox_2 = QtGui.QToolBox(self.page)
        self.toolBox_2.setGeometry(QtCore.QRect(10, 80, 291, 301))
        self.toolBox_2.setFrameShape(QtGui.QFrame.Box)
        self.toolBox_2.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.groupBox_6 = QtGui.QGroupBox(self.page_3)
        self.groupBox_6.setGeometry(QtCore.QRect(11, 11, 251, 71))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 242, 52))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ckVLaserVegetation_04 = QtGui.QCheckBox(self.layoutWidget_2)
        self.ckVLaserVegetation_04.setAutoExclusive(True)
        self.ckVLaserVegetation_04.setObjectName(_fromUtf8("ckVLaserVegetation_04"))
        self.ckButtons.addButton(self.ckVLaserVegetation_04)
        self.verticalLayout_2.addWidget(self.ckVLaserVegetation_04)
        self.ckVDgmVegetation_04 = QtGui.QCheckBox(self.layoutWidget_2)
        self.ckVDgmVegetation_04.setAutoExclusive(True)
        self.ckVDgmVegetation_04.setObjectName(_fromUtf8("ckVDgmVegetation_04"))
        self.ckButtons.addButton(self.ckVDgmVegetation_04)
        self.verticalLayout_2.addWidget(self.ckVDgmVegetation_04)
        self.groupBox_7 = QtGui.QGroupBox(self.page_3)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 90, 251, 148))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 242, 52))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.ckVLaserGelaende_04 = QtGui.QCheckBox(self.layoutWidget_4)
        self.ckVLaserGelaende_04.setAutoExclusive(True)
        self.ckVLaserGelaende_04.setObjectName(_fromUtf8("ckVLaserGelaende_04"))
        self.ckButtons.addButton(self.ckVLaserGelaende_04)
        self.verticalLayout_4.addWidget(self.ckVLaserGelaende_04)
        self.ckVDgmGelaende_04 = QtGui.QCheckBox(self.layoutWidget_4)
        self.ckVDgmGelaende_04.setAutoExclusive(True)
        self.ckVDgmGelaende_04.setObjectName(_fromUtf8("ckVDgmGelaende_04"))
        self.ckButtons.addButton(self.ckVDgmGelaende_04)
        self.verticalLayout_4.addWidget(self.ckVDgmGelaende_04)
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 70, 296, 80))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.ckVNeigungGrad_04 = QtGui.QCheckBox(self.layoutWidget_3)
        self.ckVNeigungGrad_04.setEnabled(True)
        self.ckVNeigungGrad_04.setAutoExclusive(True)
        self.ckVNeigungGrad_04.setObjectName(_fromUtf8("ckVNeigungGrad_04"))
        self.ckButtons.addButton(self.ckVNeigungGrad_04)
        self.verticalLayout_3.addWidget(self.ckVNeigungGrad_04)
        self.ckVNeigungProzent_04 = QtGui.QCheckBox(self.layoutWidget_3)
        self.ckVNeigungProzent_04.setEnabled(True)
        self.ckVNeigungProzent_04.setAutoExclusive(True)
        self.ckVNeigungProzent_04.setObjectName(_fromUtf8("ckVNeigungProzent_04"))
        self.ckButtons.addButton(self.ckVNeigungProzent_04)
        self.verticalLayout_3.addWidget(self.ckVNeigungProzent_04)
        self.ckVExposition_04 = QtGui.QCheckBox(self.layoutWidget_3)
        self.ckVExposition_04.setEnabled(True)
        self.ckVExposition_04.setAutoExclusive(True)
        self.ckVExposition_04.setObjectName(_fromUtf8("ckVExposition_04"))
        self.ckButtons.addButton(self.ckVExposition_04)
        self.verticalLayout_3.addWidget(self.ckVExposition_04)
        self.toolBox_2.addItem(self.page_3, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 289, 245))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.groupBox_9 = QtGui.QGroupBox(self.page_4)
        self.groupBox_9.setGeometry(QtCore.QRect(11, 1, 251, 71))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.layoutWidget_6 = QtGui.QWidget(self.groupBox_9)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 20, 257, 52))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.ckVLaserVegetation_11 = QtGui.QCheckBox(self.layoutWidget_6)
        self.ckVLaserVegetation_11.setAutoExclusive(True)
        self.ckVLaserVegetation_11.setObjectName(_fromUtf8("ckVLaserVegetation_11"))
        self.ckButtons.addButton(self.ckVLaserVegetation_11)
        self.verticalLayout_5.addWidget(self.ckVLaserVegetation_11)
        self.ckVDgmVegetation_11 = QtGui.QCheckBox(self.layoutWidget_6)
        self.ckVDgmVegetation_11.setAutoExclusive(True)
        self.ckVDgmVegetation_11.setObjectName(_fromUtf8("ckVDgmVegetation_11"))
        self.ckButtons.addButton(self.ckVDgmVegetation_11)
        self.verticalLayout_5.addWidget(self.ckVDgmVegetation_11)
        self.groupBox_10 = QtGui.QGroupBox(self.page_4)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 80, 251, 148))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.layoutWidget_7 = QtGui.QWidget(self.groupBox_10)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 20, 242, 52))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.ckVLaserGelaende_11 = QtGui.QCheckBox(self.layoutWidget_7)
        self.ckVLaserGelaende_11.setAutoExclusive(True)
        self.ckVLaserGelaende_11.setObjectName(_fromUtf8("ckVLaserGelaende_11"))
        self.ckButtons.addButton(self.ckVLaserGelaende_11)
        self.verticalLayout_8.addWidget(self.ckVLaserGelaende_11)
        self.ckVDgmGelaende_11 = QtGui.QCheckBox(self.layoutWidget_7)
        self.ckVDgmGelaende_11.setAutoExclusive(True)
        self.ckVDgmGelaende_11.setObjectName(_fromUtf8("ckVDgmGelaende_11"))
        self.ckButtons.addButton(self.ckVDgmGelaende_11)
        self.verticalLayout_8.addWidget(self.ckVDgmGelaende_11)
        self.layoutWidget_8 = QtGui.QWidget(self.groupBox_10)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 70, 296, 80))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.ckVNeigungGrad_11 = QtGui.QCheckBox(self.layoutWidget_8)
        self.ckVNeigungGrad_11.setEnabled(True)
        self.ckVNeigungGrad_11.setAutoExclusive(True)
        self.ckVNeigungGrad_11.setObjectName(_fromUtf8("ckVNeigungGrad_11"))
        self.ckButtons.addButton(self.ckVNeigungGrad_11)
        self.verticalLayout_9.addWidget(self.ckVNeigungGrad_11)
        self.ckVNeigungProzent_11 = QtGui.QCheckBox(self.layoutWidget_8)
        self.ckVNeigungProzent_11.setEnabled(True)
        self.ckVNeigungProzent_11.setAutoExclusive(True)
        self.ckVNeigungProzent_11.setObjectName(_fromUtf8("ckVNeigungProzent_11"))
        self.ckButtons.addButton(self.ckVNeigungProzent_11)
        self.verticalLayout_9.addWidget(self.ckVNeigungProzent_11)
        self.ckVExposition_11 = QtGui.QCheckBox(self.layoutWidget_8)
        self.ckVExposition_11.setEnabled(True)
        self.ckVExposition_11.setAutoExclusive(True)
        self.ckVExposition_11.setObjectName(_fromUtf8("ckVExposition_11"))
        self.ckButtons.addButton(self.ckVExposition_11)
        self.verticalLayout_9.addWidget(self.ckVExposition_11)
        self.toolBox_2.addItem(self.page_4, _fromUtf8(""))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(frmHoehenmodell)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 482, 251, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.btHoehenabfrage = QtGui.QPushButton(self.groupBox_2)
        self.btHoehenabfrage.setGeometry(QtCore.QRect(140, 40, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btHoehenabfrage.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btHoehenabfrage.setFont(font)
        self.btHoehenabfrage.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btHoehenabfrage.setCheckable(True)
        self.btHoehenabfrage.setChecked(False)
        self.btHoehenabfrage.setObjectName(_fromUtf8("btHoehenabfrage"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(100, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.leX = QtGui.QLineEdit(self.groupBox_2)
        self.leX.setGeometry(QtCore.QRect(10, 50, 71, 20))
        self.leX.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leX.setObjectName(_fromUtf8("leX"))
        self.leY = QtGui.QLineEdit(self.groupBox_2)
        self.leY.setGeometry(QtCore.QRect(10, 90, 71, 20))
        self.leY.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leY.setObjectName(_fromUtf8("leY"))
        self.leZ = QtGui.QLineEdit(self.groupBox_2)
        self.leZ.setGeometry(QtCore.QRect(10, 130, 71, 20))
        self.leZ.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leZ.setObjectName(_fromUtf8("leZ"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.btnAbbrechen_2 = QtGui.QPushButton(self.groupBox_2)
        self.btnAbbrechen_2.setGeometry(QtCore.QRect(100, 100, 131, 41))
        self.btnAbbrechen_2.setObjectName(_fromUtf8("btnAbbrechen_2"))
        self.line = QtGui.QFrame(frmHoehenmodell)
        self.line.setGeometry(QtCore.QRect(0, 471, 321, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))

        self.retranslateUi(frmHoehenmodell)
        self.toolBox.setCurrentIndex(1)
        self.toolBox_2.setCurrentIndex(1)
        QtCore.QObject.connect(self.btnLaden, QtCore.SIGNAL(_fromUtf8("clicked()")), frmHoehenmodell.laden)
        QtCore.QObject.connect(self.btnAbbrechen, QtCore.SIGNAL(_fromUtf8("clicked()")), frmHoehenmodell.closeEvent)
        QtCore.QObject.connect(self.btHoehenabfrage, QtCore.SIGNAL(_fromUtf8("clicked()")), frmHoehenmodell.hoehenklick)
        QtCore.QObject.connect(self.btnAbbrechen_2, QtCore.SIGNAL(_fromUtf8("clicked()")), frmHoehenmodell.hoeheClear)
        QtCore.QMetaObject.connectSlotsByName(frmHoehenmodell)

    def retranslateUi(self, frmHoehenmodell):
        frmHoehenmodell.setWindowTitle(QtGui.QApplication.translate("frmHoehenmodell", "Digitales Geländemodell", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAbbrechen.setText(QtGui.QApplication.translate("frmHoehenmodell", "Schließen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLaden.setText(QtGui.QApplication.translate("frmHoehenmodell", "Thema laden", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("frmHoehenmodell", "Landesfläche", None, QtGui.QApplication.UnicodeUTF8))
        self.ckBLaserIsolinien_11.setText(QtGui.QApplication.translate("frmHoehenmodell", "50cm-Höhenschichtenlinien\n"
"(Lasermodell 2011, ab 1:25000)", None, QtGui.QApplication.UnicodeUTF8))
        self.ckBLaserIsolinien_04.setText(QtGui.QApplication.translate("frmHoehenmodell", "1m-Höhenschichtenlinien\n"
"(Lasermodell 2002-04, ab 1:25000)", None, QtGui.QApplication.UnicodeUTF8))
        self.ckB5LaserIsolinien.setText(QtGui.QApplication.translate("frmHoehenmodell", "5m-Höhenschichtenlinien (Vlbg.)\n"
"(ab 1:25000)", None, QtGui.QApplication.UnicodeUTF8))
        self.ckOEKIsolinien.setText(QtGui.QApplication.translate("frmHoehenmodell", "OEK50-Höhenschichtenlinien (Vlbg.)\n"
"(ab 1:50000)", None, QtGui.QApplication.UnicodeUTF8))
        self.ckUMGIsolinien.setText(QtGui.QApplication.translate("frmHoehenmodell", "50m-Höhenschichtenlinien (Vlbg. + Umg.)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("frmHoehenmodell", "Höhenschichtenlinien", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmHoehenmodell", "Schummerungen Vorarlberg und Umgebung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVBEVumgebung.setText(QtGui.QApplication.translate("frmHoehenmodell", "Schummerung 5m Aufl. (Vlbg. und Umg.)", None, QtGui.QApplication.UnicodeUTF8))
        self.ckHSZentraleuropa.setText(QtGui.QApplication.translate("frmHoehenmodell", "Schummerung 50m Aufl. (Zentraleuropa)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("frmHoehenmodell", "Oberflächenmodell", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVLaserVegetation_04.setText(QtGui.QApplication.translate("frmHoehenmodell", "Schummerung 1m Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVDgmVegetation_04.setText(QtGui.QApplication.translate("frmHoehenmodell", "Rasterhöhenmodell 1m Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("frmHoehenmodell", "Geländemodell", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVLaserGelaende_04.setText(QtGui.QApplication.translate("frmHoehenmodell", "Schummerung 1m Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVDgmGelaende_04.setText(QtGui.QApplication.translate("frmHoehenmodell", "Rasterhöhenmodell 1m Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVNeigungGrad_04.setText(QtGui.QApplication.translate("frmHoehenmodell", "Geländeneigung in Grad 5m Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVNeigungProzent_04.setText(QtGui.QApplication.translate("frmHoehenmodell", "Geländeneigung in Prozent 5m Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVExposition_04.setText(QtGui.QApplication.translate("frmHoehenmodell", "Geländeexposition (Orientierung) 5m Aufl.", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_3), QtGui.QApplication.translate("frmHoehenmodell", "Laserscanning Höhenmodelle Vlbg (2002-04)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("frmHoehenmodell", "Oberflächenmodell", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVLaserVegetation_11.setText(QtGui.QApplication.translate("frmHoehenmodell", "Schummerung 50cm Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVDgmVegetation_11.setText(QtGui.QApplication.translate("frmHoehenmodell", "Rasterhöhenmodell 50cm Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("frmHoehenmodell", "Geländemodell", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVLaserGelaende_11.setText(QtGui.QApplication.translate("frmHoehenmodell", "Schummerung 50cm Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVDgmGelaende_11.setText(QtGui.QApplication.translate("frmHoehenmodell", "Rasterhöhenmodell 50cm Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVNeigungGrad_11.setText(QtGui.QApplication.translate("frmHoehenmodell", "Geländeneigung in Grad 5m Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVNeigungProzent_11.setText(QtGui.QApplication.translate("frmHoehenmodell", "Geländeneigung in Prozent 5m Auflösung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckVExposition_11.setText(QtGui.QApplication.translate("frmHoehenmodell", "Geländeexposition (Orientierung) 5m Aufl.", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_4), QtGui.QApplication.translate("frmHoehenmodell", "Laserscanning Höhenmodelle Vlbg (2011)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("frmHoehenmodell", "Rastermodelle", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmHoehenmodell", "Höhenmarken (Modell 2011)", None, QtGui.QApplication.UnicodeUTF8))
        self.btHoehenabfrage.setText(QtGui.QApplication.translate("frmHoehenmodell", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmHoehenmodell", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Höhenmarkierung zeichnen</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmHoehenmodell", "Rechtswert:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmHoehenmodell", "Hochwert:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("frmHoehenmodell", "Hoehe:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAbbrechen_2.setText(QtGui.QApplication.translate("frmHoehenmodell", "Hoehenmarkierungen\n"
"entfernen", None, QtGui.QApplication.UnicodeUTF8))

