# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_klima.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmKlima(object):
    def setupUi(self, frmKlima):
        frmKlima.setObjectName("frmKlima")
        frmKlima.resize(359, 587)
        self.ButtonBlattschnitteOk = QtWidgets.QPushButton(frmKlima)
        self.ButtonBlattschnitteOk.setEnabled(True)
        self.ButtonBlattschnitteOk.setGeometry(QtCore.QRect(10, 480, 101, 23))
        self.ButtonBlattschnitteOk.setObjectName("ButtonBlattschnitteOk")
        self.ButtonBlattschnitteCancel = QtWidgets.QPushButton(frmKlima)
        self.ButtonBlattschnitteCancel.setEnabled(True)
        self.ButtonBlattschnitteCancel.setGeometry(QtCore.QRect(110, 530, 131, 23))
        self.ButtonBlattschnitteCancel.setObjectName("ButtonBlattschnitteCancel")
        self.toolBox = QtWidgets.QToolBox(frmKlima)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 331, 451))
        self.toolBox.setFrameShape(QtWidgets.QFrame.Box)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.toolBox.setObjectName("toolBox")
        self.tbTemp = QtWidgets.QWidget()
        self.tbTemp.setGeometry(QtCore.QRect(0, 0, 327, 177))
        self.tbTemp.setObjectName("tbTemp")
        self.ckTempMaxJahresmittel = QtWidgets.QCheckBox(self.tbTemp)
        self.ckTempMaxJahresmittel.setGeometry(QtCore.QRect(10, 30, 238, 17))
        self.ckTempMaxJahresmittel.setObjectName("ckTempMaxJahresmittel")
        self.ckButtons = QtWidgets.QButtonGroup(frmKlima)
        self.ckButtons.setObjectName("ckButtons")
        self.ckButtons.addButton(self.ckTempMaxJahresmittel)
        self.ckTempJahresmittel = QtWidgets.QCheckBox(self.tbTemp)
        self.ckTempJahresmittel.setGeometry(QtCore.QRect(10, 0, 176, 17))
        self.ckTempJahresmittel.setObjectName("ckTempJahresmittel")
        self.ckButtons.addButton(self.ckTempJahresmittel)
        self.ckHeisstage = QtWidgets.QCheckBox(self.tbTemp)
        self.ckHeisstage.setGeometry(QtCore.QRect(10, 60, 238, 17))
        self.ckHeisstage.setObjectName("ckHeisstage")
        self.ckButtons.addButton(self.ckHeisstage)
        self.ckEistage = QtWidgets.QCheckBox(self.tbTemp)
        self.ckEistage.setGeometry(QtCore.QRect(10, 90, 238, 17))
        self.ckEistage.setObjectName("ckEistage")
        self.ckButtons.addButton(self.ckEistage)
        self.ckHeizgrad = QtWidgets.QCheckBox(self.tbTemp)
        self.ckHeizgrad.setGeometry(QtCore.QRect(10, 120, 238, 17))
        self.ckHeizgrad.setObjectName("ckHeizgrad")
        self.ckButtons.addButton(self.ckHeizgrad)
        self.ckVegetationsperiode = QtWidgets.QCheckBox(self.tbTemp)
        self.ckVegetationsperiode.setGeometry(QtCore.QRect(10, 150, 238, 17))
        self.ckVegetationsperiode.setObjectName("ckVegetationsperiode")
        self.ckButtons.addButton(self.ckVegetationsperiode)
        self.toolBox.addItem(self.tbTemp, "")
        self.tbFeuchte = QtWidgets.QWidget()
        self.tbFeuchte.setGeometry(QtCore.QRect(0, 0, 327, 177))
        self.tbFeuchte.setObjectName("tbFeuchte")
        self.toolBox.addItem(self.tbFeuchte, "")
        self.tabBew = QtWidgets.QWidget()
        self.tabBew.setGeometry(QtCore.QRect(0, 0, 327, 177))
        self.tabBew.setObjectName("tabBew")
        self.toolBox.addItem(self.tabBew, "")
        self.tabNs = QtWidgets.QWidget()
        self.tabNs.setGeometry(QtCore.QRect(0, 0, 327, 177))
        self.tabNs.setObjectName("tabNs")
        self.layoutWidget = QtWidgets.QWidget(self.tabNs)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 247, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ckNsJahrGesamt = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckNsJahrGesamt.setObjectName("ckNsJahrGesamt")
        self.ckButtons.addButton(self.ckNsJahrGesamt)
        self.verticalLayout.addWidget(self.ckNsJahrGesamt)
        self.ckNTage1mm = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckNTage1mm.setObjectName("ckNTage1mm")
        self.ckButtons.addButton(self.ckNTage1mm)
        self.verticalLayout.addWidget(self.ckNTage1mm)
        self.ckNTage10mm = QtWidgets.QCheckBox(self.layoutWidget)
        self.ckNTage10mm.setObjectName("ckNTage10mm")
        self.ckButtons.addButton(self.ckNTage10mm)
        self.verticalLayout.addWidget(self.ckNTage10mm)
        self.toolBox.addItem(self.tabNs, "")
        self.tabSchnee = QtWidgets.QWidget()
        self.tabSchnee.setGeometry(QtCore.QRect(0, 0, 327, 177))
        self.tabSchnee.setObjectName("tabSchnee")
        self.toolBox.addItem(self.tabSchnee, "")
        self.tabVerd = QtWidgets.QWidget()
        self.tabVerd.setGeometry(QtCore.QRect(0, 0, 327, 177))
        self.tabVerd.setObjectName("tabVerd")
        self.toolBox.addItem(self.tabVerd, "")
        self.tabDruck = QtWidgets.QWidget()
        self.tabDruck.setGeometry(QtCore.QRect(0, 0, 327, 177))
        self.tabDruck.setObjectName("tabDruck")
        self.toolBox.addItem(self.tabDruck, "")
        self.tabWind = QtWidgets.QWidget()
        self.tabWind.setGeometry(QtCore.QRect(0, 0, 327, 177))
        self.tabWind.setObjectName("tabWind")
        self.toolBox.addItem(self.tabWind, "")
        self.tabSolar = QtWidgets.QWidget()
        self.tabSolar.setGeometry(QtCore.QRect(0, 0, 327, 177))
        self.tabSolar.setObjectName("tabSolar")
        self.toolBox.addItem(self.tabSolar, "")
        self.tabKomb = QtWidgets.QWidget()
        self.tabKomb.setGeometry(QtCore.QRect(0, 0, 327, 177))
        self.tabKomb.setObjectName("tabKomb")
        self.toolBox.addItem(self.tabKomb, "")
        self.btnKartePDF = QtWidgets.QPushButton(frmKlima)
        self.btnKartePDF.setGeometry(QtCore.QRect(120, 480, 101, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnKartePDF.sizePolicy().hasHeightForWidth())
        self.btnKartePDF.setSizePolicy(sizePolicy)
        self.btnKartePDF.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnKartePDF.setObjectName("btnKartePDF")
        self.btnBeschreibungPDF = QtWidgets.QPushButton(frmKlima)
        self.btnBeschreibungPDF.setGeometry(QtCore.QRect(230, 480, 121, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBeschreibungPDF.sizePolicy().hasHeightForWidth())
        self.btnBeschreibungPDF.setSizePolicy(sizePolicy)
        self.btnBeschreibungPDF.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnBeschreibungPDF.setObjectName("btnBeschreibungPDF")

        self.retranslateUi(frmKlima)
        self.ButtonBlattschnitteOk.clicked.connect(frmKlima.accept)
        self.ButtonBlattschnitteCancel.clicked.connect(frmKlima.close)
        self.btnKartePDF.clicked.connect(frmKlima.Kartebutton)
        self.btnBeschreibungPDF.clicked.connect(frmKlima.Kartebutton)
        QtCore.QMetaObject.connectSlotsByName(frmKlima)

    def retranslateUi(self, frmKlima):
        _translate = QtCore.QCoreApplication.translate
        frmKlima.setWindowTitle(_translate("frmKlima", "Klima"))
        self.ButtonBlattschnitteOk.setText(_translate("frmKlima", "Themen laden"))
        self.ButtonBlattschnitteCancel.setText(_translate("frmKlima", "Schließen"))
        self.ckTempMaxJahresmittel.setText(_translate("frmKlima", "Mittleres Jahresmaximum der Lufttemperatur"))
        self.ckTempJahresmittel.setText(_translate("frmKlima", "Jahresmittel der Lufttemperatur"))
        self.ckHeisstage.setText(_translate("frmKlima", "Mittlere Zahl von heissen Tagen"))
        self.ckEistage.setText(_translate("frmKlima", "Mittlere Zahl von Eistagen"))
        self.ckHeizgrad.setText(_translate("frmKlima", "Mittlere jährliche Heizgradtagszahl"))
        self.ckVegetationsperiode.setText(_translate("frmKlima", "Dauer der Vegetationsperiode"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tbTemp), _translate("frmKlima", "Temperatur"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tbFeuchte), _translate("frmKlima", "Feuchte"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabBew), _translate("frmKlima", "Bewölkung"))
        self.ckNsJahrGesamt.setText(_translate("frmKlima", "Jahresniederschlagssumme"))
        self.ckNTage1mm.setText(_translate("frmKlima", "Anzahl der Tage mit mind. 1 mm Niederschlag"))
        self.ckNTage10mm.setText(_translate("frmKlima", "Anzahl der Tage mit mind. 10 mm Niederschlag"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabNs), _translate("frmKlima", "Niederschlag"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabSchnee), _translate("frmKlima", "Schnee"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabVerd), _translate("frmKlima", "Verdunstung"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabDruck), _translate("frmKlima", "Luftdruck"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabWind), _translate("frmKlima", "Wind"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabSolar), _translate("frmKlima", "Solare Einstrahlung"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tabKomb), _translate("frmKlima", "Kombi-Grössen"))
        self.btnKartePDF.setText(_translate("frmKlima", "PDF Karte laden"))
        self.btnBeschreibungPDF.setText(_translate("frmKlima", "Beschreibung laden"))

