# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_adresssuche_pg.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmAdresssuche(object):
    def setupUi(self, frmAdresssuche):
        frmAdresssuche.setObjectName("frmAdresssuche")
        frmAdresssuche.resize(481, 549)
        self.schliessen = QtWidgets.QPushButton(frmAdresssuche)
        self.schliessen.setGeometry(QtCore.QRect(170, 500, 151, 31))
        self.schliessen.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.schliessen.setAutoDefault(False)
        self.schliessen.setObjectName("schliessen")
        self.groupBox = QtWidgets.QGroupBox(frmAdresssuche)
        self.groupBox.setGeometry(QtCore.QRect(20, 400, 441, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.ButtonAdressenOk = QtWidgets.QPushButton(self.groupBox)
        self.ButtonAdressenOk.setGeometry(QtCore.QRect(240, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ButtonAdressenOk.setFont(font)
        self.ButtonAdressenOk.setAutoDefault(False)
        self.ButtonAdressenOk.setObjectName("ButtonAdressenOk")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 20, 138, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.buttonGroup = QtWidgets.QButtonGroup(frmAdresssuche)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 50, 155, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.buttonGroup.addButton(self.checkBox_2)
        self.groupBox_2 = QtWidgets.QGroupBox(frmAdresssuche)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 441, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.laden = QtWidgets.QPushButton(self.groupBox_2)
        self.laden.setGeometry(QtCore.QRect(20, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.laden.setFont(font)
        self.laden.setAutoDefault(False)
        self.laden.setObjectName("laden")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(310, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 30, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.leStrasse = QtWidgets.QLineEdit(self.groupBox_3)
        self.leStrasse.setGeometry(QtCore.QRect(10, 20, 381, 21))
        self.leStrasse.setObjectName("leStrasse")
        self.treeAdressen = QtWidgets.QTreeView(self.groupBox_2)
        self.treeAdressen.setGeometry(QtCore.QRect(20, 120, 401, 192))
        self.treeAdressen.setObjectName("treeAdressen")
        self.treeAdressen.header().setVisible(False)
        self.btnEinklappen = QtWidgets.QPushButton(self.groupBox_2)
        self.btnEinklappen.setGeometry(QtCore.QRect(20, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnEinklappen.setFont(font)
        self.btnEinklappen.setObjectName("btnEinklappen")

        self.retranslateUi(frmAdresssuche)
        self.laden.clicked.connect(frmAdresssuche.accept)
        self.schliessen.clicked.connect(frmAdresssuche.closeEvent)
        self.ButtonAdressenOk.clicked.connect(frmAdresssuche.themenLaden)
        self.pushButton.clicked.connect(frmAdresssuche.adrClear)
        QtCore.QMetaObject.connectSlotsByName(frmAdresssuche)

    def retranslateUi(self, frmAdresssuche):
        _translate = QtCore.QCoreApplication.translate
        frmAdresssuche.setWindowTitle(_translate("frmAdresssuche", "Adresssuche"))
        self.schliessen.setText(_translate("frmAdresssuche", "Fenster Schließen"))
        self.groupBox.setTitle(_translate("frmAdresssuche", "Adresslayer laden"))
        self.ButtonAdressenOk.setText(_translate("frmAdresssuche", "Thema laden"))
        self.checkBox_3.setText(_translate("frmAdresssuche", "Adressen Gemeinde"))
        self.checkBox_2.setText(_translate("frmAdresssuche", "Adressen Landesfläche"))
        self.groupBox_2.setTitle(_translate("frmAdresssuche", "Adressen suchen und anzeigen"))
        self.laden.setText(_translate("frmAdresssuche", "in View darstellen"))
        self.pushButton.setText(_translate("frmAdresssuche", "in View löschen"))
        self.groupBox_3.setTitle(_translate("frmAdresssuche", "Strassensuche Landesweit"))
        self.btnEinklappen.setText(_translate("frmAdresssuche", "alles einklappen"))

