# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_jagd.ui'
#
# Created: Thu Mar 16 11:36:16 2017
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmJagd(object):
    def setupUi(self, frmJagd):
        frmJagd.setObjectName(_fromUtf8("frmJagd"))
        frmJagd.resize(279, 386)
        self.ButtonBlattschnitteOk = QtGui.QPushButton(frmJagd)
        self.ButtonBlattschnitteOk.setGeometry(QtCore.QRect(30, 330, 101, 23))
        self.ButtonBlattschnitteOk.setObjectName(_fromUtf8("ButtonBlattschnitteOk"))
        self.ButtonBlattschnitteCancel = QtGui.QPushButton(frmJagd)
        self.ButtonBlattschnitteCancel.setGeometry(QtCore.QRect(150, 330, 101, 23))
        self.ButtonBlattschnitteCancel.setObjectName(_fromUtf8("ButtonBlattschnitteCancel"))
        self.layoutWidget = QtGui.QWidget(frmJagd)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 201, 293))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ckJagdreviere = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckJagdreviere.setFont(font)
        self.ckJagdreviere.setObjectName(_fromUtf8("ckJagdreviere"))
        self.ckButtons = QtGui.QButtonGroup(frmJagd)
        self.ckButtons.setObjectName(_fromUtf8("ckButtons"))
        self.ckButtons.addButton(self.ckJagdreviere)
        self.verticalLayout.addWidget(self.ckJagdreviere)
        self.ckRotwildgebiete = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckRotwildgebiete.setFont(font)
        self.ckRotwildgebiete.setObjectName(_fromUtf8("ckRotwildgebiete"))
        self.ckButtons.addButton(self.ckRotwildgebiete)
        self.verticalLayout.addWidget(self.ckRotwildgebiete)
        self.ckWildregionen = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckWildregionen.setFont(font)
        self.ckWildregionen.setObjectName(_fromUtf8("ckWildregionen"))
        self.ckButtons.addButton(self.ckWildregionen)
        self.verticalLayout.addWidget(self.ckWildregionen)
        self.ckWildbehandlungszonen = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckWildbehandlungszonen.setFont(font)
        self.ckWildbehandlungszonen.setObjectName(_fromUtf8("ckWildbehandlungszonen"))
        self.ckButtons.addButton(self.ckWildbehandlungszonen)
        self.verticalLayout.addWidget(self.ckWildbehandlungszonen)
        self.ckWildfreihaltungen = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckWildfreihaltungen.setFont(font)
        self.ckWildfreihaltungen.setObjectName(_fromUtf8("ckWildfreihaltungen"))
        self.ckButtons.addButton(self.ckWildfreihaltungen)
        self.verticalLayout.addWidget(self.ckWildfreihaltungen)
        self.ckWildruhezonen = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckWildruhezonen.setFont(font)
        self.ckWildruhezonen.setObjectName(_fromUtf8("ckWildruhezonen"))
        self.ckButtons.addButton(self.ckWildruhezonen)
        self.verticalLayout.addWidget(self.ckWildruhezonen)
        self.ckGamszonierung = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckGamszonierung.setFont(font)
        self.ckGamszonierung.setObjectName(_fromUtf8("ckGamszonierung"))
        self.ckButtons.addButton(self.ckGamszonierung)
        self.verticalLayout.addWidget(self.ckGamszonierung)
        self.ckWildfuetterungen = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckWildfuetterungen.setFont(font)
        self.ckWildfuetterungen.setObjectName(_fromUtf8("ckWildfuetterungen"))
        self.ckButtons.addButton(self.ckWildfuetterungen)
        self.verticalLayout.addWidget(self.ckWildfuetterungen)
        self.ckRotwildwintergatter = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckRotwildwintergatter.setFont(font)
        self.ckRotwildwintergatter.setObjectName(_fromUtf8("ckRotwildwintergatter"))
        self.ckButtons.addButton(self.ckRotwildwintergatter)
        self.verticalLayout.addWidget(self.ckRotwildwintergatter)

        self.retranslateUi(frmJagd)
        QtCore.QObject.connect(self.ButtonBlattschnitteOk, QtCore.SIGNAL(_fromUtf8("clicked()")), frmJagd.accept)
        QtCore.QObject.connect(self.ButtonBlattschnitteCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), frmJagd.close)
        QtCore.QMetaObject.connectSlotsByName(frmJagd)

    def retranslateUi(self, frmJagd):
        frmJagd.setWindowTitle(QtGui.QApplication.translate("frmJagd", "Jagd", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonBlattschnitteOk.setText(QtGui.QApplication.translate("frmJagd", "Themen laden", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonBlattschnitteCancel.setText(QtGui.QApplication.translate("frmJagd", "Schließen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckJagdreviere.setText(QtGui.QApplication.translate("frmJagd", "Jagdreviere", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRotwildgebiete.setText(QtGui.QApplication.translate("frmJagd", "Rotwildgebiete", None, QtGui.QApplication.UnicodeUTF8))
        self.ckWildregionen.setText(QtGui.QApplication.translate("frmJagd", "Wildregionen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckWildbehandlungszonen.setText(QtGui.QApplication.translate("frmJagd", "Wildbehandlungszonen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckWildfreihaltungen.setText(QtGui.QApplication.translate("frmJagd", "Wildfreihaltungen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckWildruhezonen.setText(QtGui.QApplication.translate("frmJagd", "Wildruhezonen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckGamszonierung.setText(QtGui.QApplication.translate("frmJagd", "Gamszonierung", None, QtGui.QApplication.UnicodeUTF8))
        self.ckWildfuetterungen.setText(QtGui.QApplication.translate("frmJagd", "Wildfütterungen", None, QtGui.QApplication.UnicodeUTF8))
        self.ckRotwildwintergatter.setText(QtGui.QApplication.translate("frmJagd", "Rotwildwintergatter", None, QtGui.QApplication.UnicodeUTF8))

