# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_jagd.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmJagd(object):
    def setupUi(self, frmJagd):
        frmJagd.setObjectName("frmJagd")
        frmJagd.resize(279, 386)
        self.ButtonBlattschnitteOk = QtWidgets.QPushButton(frmJagd)
        self.ButtonBlattschnitteOk.setGeometry(QtCore.QRect(30, 330, 101, 23))
        self.ButtonBlattschnitteOk.setObjectName("ButtonBlattschnitteOk")
        self.ButtonBlattschnitteCancel = QtWidgets.QPushButton(frmJagd)
        self.ButtonBlattschnitteCancel.setGeometry(QtCore.QRect(150, 330, 101, 23))
        self.ButtonBlattschnitteCancel.setObjectName("ButtonBlattschnitteCancel")
        self.layoutWidget = QtWidgets.QWidget(frmJagd)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 201, 293))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ckJagdreviere = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckJagdreviere.setFont(font)
        self.ckJagdreviere.setObjectName("ckJagdreviere")
        self.ckButtons = QtWidgets.QButtonGroup(frmJagd)
        self.ckButtons.setObjectName("ckButtons")
        self.ckButtons.setExclusive(False)
        self.ckButtons.addButton(self.ckJagdreviere)
        self.verticalLayout.addWidget(self.ckJagdreviere)
        self.ckRotwildgebiete = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckRotwildgebiete.setFont(font)
        self.ckRotwildgebiete.setObjectName("ckRotwildgebiete")
        self.ckButtons.addButton(self.ckRotwildgebiete)
        self.verticalLayout.addWidget(self.ckRotwildgebiete)
        self.ckWildregionen = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckWildregionen.setFont(font)
        self.ckWildregionen.setObjectName("ckWildregionen")
        self.ckButtons.addButton(self.ckWildregionen)
        self.verticalLayout.addWidget(self.ckWildregionen)
        self.ckWildbehandlungszonen = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckWildbehandlungszonen.setFont(font)
        self.ckWildbehandlungszonen.setObjectName("ckWildbehandlungszonen")
        self.ckButtons.addButton(self.ckWildbehandlungszonen)
        self.verticalLayout.addWidget(self.ckWildbehandlungszonen)
        self.ckWildfreihaltungen = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckWildfreihaltungen.setFont(font)
        self.ckWildfreihaltungen.setObjectName("ckWildfreihaltungen")
        self.ckButtons.addButton(self.ckWildfreihaltungen)
        self.verticalLayout.addWidget(self.ckWildfreihaltungen)
        self.ckWildruhezonen = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckWildruhezonen.setFont(font)
        self.ckWildruhezonen.setObjectName("ckWildruhezonen")
        self.ckButtons.addButton(self.ckWildruhezonen)
        self.verticalLayout.addWidget(self.ckWildruhezonen)
        self.ckGamszonierung = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckGamszonierung.setFont(font)
        self.ckGamszonierung.setObjectName("ckGamszonierung")
        self.ckButtons.addButton(self.ckGamszonierung)
        self.verticalLayout.addWidget(self.ckGamszonierung)
        self.ckWildfuetterungen = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckWildfuetterungen.setFont(font)
        self.ckWildfuetterungen.setObjectName("ckWildfuetterungen")
        self.ckButtons.addButton(self.ckWildfuetterungen)
        self.verticalLayout.addWidget(self.ckWildfuetterungen)
        self.ckRotwildwintergatter = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckRotwildwintergatter.setFont(font)
        self.ckRotwildwintergatter.setObjectName("ckRotwildwintergatter")
        self.ckButtons.addButton(self.ckRotwildwintergatter)
        self.verticalLayout.addWidget(self.ckRotwildwintergatter)

        self.retranslateUi(frmJagd)
        self.ButtonBlattschnitteOk.clicked.connect(frmJagd.accept)
        self.ButtonBlattschnitteCancel.clicked.connect(frmJagd.close)
        QtCore.QMetaObject.connectSlotsByName(frmJagd)

    def retranslateUi(self, frmJagd):
        _translate = QtCore.QCoreApplication.translate
        frmJagd.setWindowTitle(_translate("frmJagd", "Jagd"))
        self.ButtonBlattschnitteOk.setText(_translate("frmJagd", "Themen laden"))
        self.ButtonBlattschnitteCancel.setText(_translate("frmJagd", "Schließen"))
        self.ckJagdreviere.setText(_translate("frmJagd", "Jagdreviere"))
        self.ckRotwildgebiete.setText(_translate("frmJagd", "Rotwildgebiete"))
        self.ckWildregionen.setText(_translate("frmJagd", "Wildregionen"))
        self.ckWildbehandlungszonen.setText(_translate("frmJagd", "Wildbehandlungszonen"))
        self.ckWildfreihaltungen.setText(_translate("frmJagd", "Wildfreihaltungen"))
        self.ckWildruhezonen.setText(_translate("frmJagd", "Wildruhezonen"))
        self.ckGamszonierung.setText(_translate("frmJagd", "Gamszonierung"))
        self.ckWildfuetterungen.setText(_translate("frmJagd", "Wildfütterungen"))
        self.ckRotwildwintergatter.setText(_translate("frmJagd", "Rotwildwintergatter"))

