# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_wald.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmWald(object):
    def setupUi(self, frmWald):
        frmWald.setObjectName("frmWald")
        frmWald.resize(285, 307)
        self.ButtonBlattschnitteOk = QtWidgets.QPushButton(frmWald)
        self.ButtonBlattschnitteOk.setGeometry(QtCore.QRect(30, 250, 101, 23))
        self.ButtonBlattschnitteOk.setObjectName("ButtonBlattschnitteOk")
        self.ButtonBlattschnitteCancel = QtWidgets.QPushButton(frmWald)
        self.ButtonBlattschnitteCancel.setGeometry(QtCore.QRect(150, 250, 101, 23))
        self.ButtonBlattschnitteCancel.setObjectName("ButtonBlattschnitteCancel")
        self.layoutWidget = QtWidgets.QWidget(frmWald)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 219, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ckAuwald = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ckAuwald.setFont(font)
        self.ckAuwald.setObjectName("ckAuwald")
        self.ckButtons = QtWidgets.QButtonGroup(frmWald)
        self.ckButtons.setObjectName("ckButtons")
        self.ckButtons.setExclusive(False)
        self.ckButtons.addButton(self.ckAuwald)
        self.verticalLayout.addWidget(self.ckAuwald)
        self.ckSaatgut = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ckSaatgut.setFont(font)
        self.ckSaatgut.setObjectName("ckSaatgut")
        self.ckButtons.addButton(self.ckSaatgut)
        self.verticalLayout.addWidget(self.ckSaatgut)
        self.ckUfergehoelz = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ckUfergehoelz.setFont(font)
        self.ckUfergehoelz.setObjectName("ckUfergehoelz")
        self.ckButtons.addButton(self.ckUfergehoelz)
        self.verticalLayout.addWidget(self.ckUfergehoelz)
        self.ckWaldklassifizierung = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ckWaldklassifizierung.setFont(font)
        self.ckWaldklassifizierung.setObjectName("ckWaldklassifizierung")
        self.ckButtons.addButton(self.ckWaldklassifizierung)
        self.verticalLayout.addWidget(self.ckWaldklassifizierung)
        self.ckWaldflaecheOek = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ckWaldflaecheOek.setFont(font)
        self.ckWaldflaecheOek.setObjectName("ckWaldflaecheOek")
        self.ckButtons.addButton(self.ckWaldflaecheOek)
        self.verticalLayout.addWidget(self.ckWaldflaecheOek)
        self.ckWaldentwicklungsplan = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ckWaldentwicklungsplan.setFont(font)
        self.ckWaldentwicklungsplan.setObjectName("ckWaldentwicklungsplan")
        self.ckButtons.addButton(self.ckWaldentwicklungsplan)
        self.verticalLayout.addWidget(self.ckWaldentwicklungsplan)
        self.ckWaldregionen = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ckWaldregionen.setFont(font)
        self.ckWaldregionen.setObjectName("ckWaldregionen")
        self.ckButtons.addButton(self.ckWaldregionen)
        self.verticalLayout.addWidget(self.ckWaldregionen)
        self.ckWaldkarte = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ckWaldkarte.setFont(font)
        self.ckWaldkarte.setObjectName("ckWaldkarte")
        self.ckButtons.addButton(self.ckWaldkarte)
        self.verticalLayout.addWidget(self.ckWaldkarte)

        self.retranslateUi(frmWald)
        self.ButtonBlattschnitteOk.clicked.connect(frmWald.accept)
        self.ButtonBlattschnitteCancel.clicked.connect(frmWald.closeEvent)
        QtCore.QMetaObject.connectSlotsByName(frmWald)

    def retranslateUi(self, frmWald):
        _translate = QtCore.QCoreApplication.translate
        frmWald.setWindowTitle(_translate("frmWald", "Wald"))
        self.ButtonBlattschnitteOk.setText(_translate("frmWald", "Themen laden"))
        self.ButtonBlattschnitteCancel.setText(_translate("frmWald", "Schließen"))
        self.ckAuwald.setText(_translate("frmWald", "Auwald"))
        self.ckSaatgut.setText(_translate("frmWald", "Saatgut"))
        self.ckUfergehoelz.setText(_translate("frmWald", "Ufergehölz"))
        self.ckWaldklassifizierung.setText(_translate("frmWald", "Waldklassifizierung aus Orthofotos 2001"))
        self.ckWaldflaecheOek.setText(_translate("frmWald", "Waldfläche aus ÖK50"))
        self.ckWaldentwicklungsplan.setText(_translate("frmWald", "Waldentwicklungsplan"))
        self.ckWaldregionen.setText(_translate("frmWald", "Waldregionen"))
        self.ckWaldkarte.setText(_translate("frmWald", "Waldkarte"))

