# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_adresssuche_sqlite.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmAdresssuche(object):
    def setupUi(self, frmAdresssuche):
        frmAdresssuche.setObjectName("frmAdresssuche")
        frmAdresssuche.resize(671, 416)
        self.schliessen = QtWidgets.QPushButton(frmAdresssuche)
        self.schliessen.setGeometry(QtCore.QRect(450, 330, 101, 31))
        self.schliessen.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.schliessen.setAutoDefault(False)
        self.schliessen.setObjectName("schliessen")
        self.groupBox = QtWidgets.QGroupBox(frmAdresssuche)
        self.groupBox.setGeometry(QtCore.QRect(20, 300, 361, 91))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 157, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.buttonGroup = QtWidgets.QButtonGroup(frmAdresssuche)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.checkBox_3)
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.buttonGroup.addButton(self.checkBox_2)
        self.verticalLayout.addWidget(self.checkBox_2)
        self.ButtonAdressenOk = QtWidgets.QPushButton(self.groupBox)
        self.ButtonAdressenOk.setGeometry(QtCore.QRect(210, 30, 121, 31))
        self.ButtonAdressenOk.setAutoDefault(False)
        self.ButtonAdressenOk.setObjectName("ButtonAdressenOk")
        self.groupBox_2 = QtWidgets.QGroupBox(frmAdresssuche)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 621, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lstNummer = QtWidgets.QListView(self.groupBox_2)
        self.lstNummer.setGeometry(QtCore.QRect(430, 40, 150, 192))
        self.lstNummer.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lstNummer.setObjectName("lstNummer")
        self.lstGemeinde = QtWidgets.QListView(self.groupBox_2)
        self.lstGemeinde.setGeometry(QtCore.QRect(20, 80, 150, 151))
        self.lstGemeinde.setObjectName("lstGemeinde")
        self.laden = QtWidgets.QPushButton(self.groupBox_2)
        self.laden.setGeometry(QtCore.QRect(190, 240, 111, 31))
        self.laden.setAutoDefault(False)
        self.laden.setObjectName("laden")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(310, 240, 111, 31))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.lstStrasse = QtWidgets.QListView(self.groupBox_2)
        self.lstStrasse.setGeometry(QtCore.QRect(200, 80, 201, 151))
        self.lstStrasse.setObjectName("lstStrasse")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 401, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.leStrasse = QtWidgets.QLineEdit(self.groupBox_3)
        self.leStrasse.setGeometry(QtCore.QRect(10, 20, 381, 21))
        self.leStrasse.setObjectName("leStrasse")

        self.retranslateUi(frmAdresssuche)
        self.laden.clicked.connect(frmAdresssuche.accept)
        self.schliessen.clicked.connect(frmAdresssuche.closeEvent)
        self.lstNummer.clicked['QModelIndex'].connect(frmAdresssuche.lstNummerKlicked)
        self.pushButton.clicked.connect(frmAdresssuche.adrClear)
        self.ButtonAdressenOk.clicked.connect(frmAdresssuche.themenLaden)
        self.leStrasse.returnPressed.connect(frmAdresssuche.strassensuche)
        QtCore.QMetaObject.connectSlotsByName(frmAdresssuche)

    def retranslateUi(self, frmAdresssuche):
        _translate = QtCore.QCoreApplication.translate
        frmAdresssuche.setWindowTitle(_translate("frmAdresssuche", "Adresssuche"))
        self.schliessen.setText(_translate("frmAdresssuche", "Schließen"))
        self.groupBox.setTitle(_translate("frmAdresssuche", "Adresslayer laden"))
        self.checkBox_3.setText(_translate("frmAdresssuche", "Adressen Gemeinde"))
        self.checkBox_2.setText(_translate("frmAdresssuche", "Adressen Landesfläche"))
        self.ButtonAdressenOk.setText(_translate("frmAdresssuche", "Thema laden"))
        self.groupBox_2.setTitle(_translate("frmAdresssuche", "Adressen suchen und anzeigen"))
        self.laden.setText(_translate("frmAdresssuche", "in View darstellen"))
        self.pushButton.setText(_translate("frmAdresssuche", "in View löschen"))
        self.groupBox_3.setTitle(_translate("frmAdresssuche", "Strassensuche Landesweit"))

